# Copyright (C) 2018-2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(CPACK_NSIS_INSTALL_ROOT "Intel")
set(CPACK_NSIS_MUI_ICON "${OpenVINO_SOURCE_DIR}/cmake/templates/openvino.ico")
set(CPACK_NSIS_MUI_UNIICON "${CPACK_NSIS_MUI_ICON}")

set(CPACK_NSIS_DISPLAY_NAME "Display name in Windows Add/Remove Program control panel")
set(CPACK_NSIS_PACKAGE_NAME "The title displayed at the top of the installer")

# we allow to have several OpenVINO versions on the system
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL OFF)
set(CPACK_NSIS_MODIFY_PATH OFF)

message(STATUS "----- CPACK_NSIS_INSTALL_ROOT = ${CPACK_NSIS_INSTALL_ROOT}")
message(STATUS "----- CPACK_NSIS_MUI_ICON = ${CPACK_NSIS_MUI_ICON}")
message(STATUS "----- CPACK_NSIS_MUI_UNIICON = ${CPACK_NSIS_MUI_UNIICON}")
message(STATUS "----- CPACK_NSIS_INSTALLER_MUI_ICON_CODE = ${CPACK_NSIS_INSTALLER_MUI_ICON_CODE}")
message(STATUS "----- CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP = ${CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP}")
message(STATUS "----- CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP = ${CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP}")

message(STATUS "----- CPACK_NSIS_EXTRA_PREINSTALL_COMMANDS = ${CPACK_NSIS_EXTRA_PREINSTALL_COMMANDS}")
message(STATUS "----- CPACK_NSIS_EXTRA_INSTALL_COMMANDS = ${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}")
message(STATUS "----- CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS = ${CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS}")
message(STATUS "----- CPACK_NSIS_COMPRESSOR = ${CPACK_NSIS_COMPRESSOR}")
message(STATUS "----- CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL = ${CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL}")
message(STATUS "----- CPACK_NSIS_MODIFY_PATH = ${CPACK_NSIS_MODIFY_PATH}")
message(STATUS "----- CPACK_NSIS_DISPLAY_NAME = ${CPACK_NSIS_DISPLAY_NAME}")

message(STATUS "----- CPACK_NSIS_PACKAGE_NAME = ${CPACK_NSIS_PACKAGE_NAME}")
message(STATUS "----- CPACK_NSIS_INSTALLED_ICON_NAME = ${CPACK_NSIS_INSTALLED_ICON_NAME}")
message(STATUS "----- CPACK_NSIS_HELP_LINK = ${CPACK_NSIS_HELP_LINK}")
message(STATUS "----- CPACK_NSIS_URL_INFO_ABOUT = ${CPACK_NSIS_URL_INFO_ABOUT}")


message(STATUS "----- CPACK_NSIS_CONTACT = ${CPACK_NSIS_CONTACT}")
message(STATUS "----- CPACK_NSIS_CREATE_ICONS_EXTRA = ${CPACK_NSIS_CREATE_ICONS_EXTRA}")
message(STATUS "----- CPACK_NSIS_DELETE_ICONS_EXTRA = ${CPACK_NSIS_DELETE_ICONS_EXTRA}")
message(STATUS "----- CPACK_NSIS_EXECUTABLES_DIRECTORY = ${CPACK_NSIS_EXECUTABLES_DIRECTORY}")
message(STATUS "----- CPACK_NSIS_MUI_FINISHPAGE_RUN = ${CPACK_NSIS_URL_INFO_ABOUT}")
message(STATUS "----- CPACK_NSIS_MENU_LINKS = ${CPACK_NSIS_MENU_LINKS}")

message(STATUS "----- CPACK_NSIS_UNINSTALL_NAME = ${CPACK_NSIS_UNINSTALL_NAME}")
message(STATUS "----- CPACK_NSIS_WELCOME_TITLE = ${CPACK_NSIS_WELCOME_TITLE}")
message(STATUS "----- CPACK_NSIS_WELCOME_TITLE_3LINES = ${CPACK_NSIS_WELCOME_TITLE_3LINES}")
message(STATUS "----- CPACK_NSIS_FINISH_TITLE = ${CPACK_NSIS_FINISH_TITLE}")
message(STATUS "----- CPACK_NSIS_FINISH_TITLE_3LINES = ${CPACK_NSIS_FINISH_TITLE_3LINES}")

message(STATUS "----- CPACK_NSIS_MUI_HEADERIMAGE = ${CPACK_NSIS_MUI_HEADERIMAGE}")
message(STATUS "----- CPACK_NSIS_MANIFEST_DPI_AWARE = ${CPACK_NSIS_MANIFEST_DPI_AWARE}")
message(STATUS "----- CPACK_NSIS_BRANDING_TEXT = ${CPACK_NSIS_BRANDING_TEXT}")
message(STATUS "----- CPACK_NSIS_BRANDING_TEXT_TRIM_POSITION = ${CPACK_NSIS_BRANDING_TEXT_TRIM_POSITION}")
message(STATUS "----- CPACK_NSIS_EXECUTABLE = ${CPACK_NSIS_EXECUTABLE}")
message(STATUS "----- CPACK_NSIS_IGNORE_LICENSE_PAGE = ${CPACK_NSIS_IGNORE_LICENSE_PAGE}")
