# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Embeds OpenCL kernel sources from src/kernels/*.cl into a single header
# `tp_embedded_kernels.h` which exposes each as a `constexpr const char[]`.
# The header is generated at configure time so it is always current.

set(_tp_kernel_dir "${CMAKE_CURRENT_SOURCE_DIR}/src/kernels")
set(_tp_kernel_out_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(_tp_kernel_out_header "${_tp_kernel_out_dir}/tp_embedded_kernels.h")

file(MAKE_DIRECTORY "${_tp_kernel_out_dir}")

# Add new entries here as more .cl files are introduced.
set(_tp_kernels allreduce_sum)

set(_tp_kernel_header_body "// Auto-generated by embed_kernels.cmake. DO NOT EDIT.\n#pragma once\n\nnamespace ov { namespace tp { namespace kernels {\n\n")

foreach(_kname IN LISTS _tp_kernels)
    set(_kfile "${_tp_kernel_dir}/${_kname}.cl")
    if(NOT EXISTS "${_kfile}")
        message(FATAL_ERROR "TP kernel source not found: ${_kfile}")
    endif()
    file(READ "${_kfile}" _ksrc)
    # Use a raw string with a unique delimiter unlikely to appear in CL code.
    set(_tp_kernel_header_body "${_tp_kernel_header_body}inline constexpr const char ${_kname}_cl[] = R\"OVTPCL(\n${_ksrc}\n)OVTPCL\";\n\n")
endforeach()

set(_tp_kernel_header_body "${_tp_kernel_header_body}}}} // namespace ov::tp::kernels\n")

# Only rewrite if changed, to avoid forcing rebuilds.
if(EXISTS "${_tp_kernel_out_header}")
    file(READ "${_tp_kernel_out_header}" _existing)
else()
    set(_existing "")
endif()
if(NOT "${_existing}" STREQUAL "${_tp_kernel_header_body}")
    file(WRITE "${_tp_kernel_out_header}" "${_tp_kernel_header_body}")
endif()
