# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

#!/usr/bin/env python3
"""Phase 7 helper for enable-operator agent — branch, apply patches, open draft PR.

Reads agent-results/pipeline_state.json to derive op names, creates a branch,
applies all collected patches via 'git am', pushes to the user's fork, and opens
a draft PR against openvinotoolkit/openvino with the required AI-generation banner
and pull_request_template.md structure.

Cross-platform: uses Python subprocess instead of bash. Requires git and gh CLI.

Usage:
    python .github/scripts/meat/create_agent_pr.py [--dry-run]

Exit codes:
  0 — PR opened (or already exists, or dry-run)
  1 — unrecoverable error
"""

import argparse
import json
import pathlib
import subprocess
import sys
import textwrap


def run(cmd: list[str], check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    """Run a command, optionally capturing output."""
    return subprocess.run(
        cmd,
        check=check,
        text=True,
        capture_output=capture,
    )


def gh_login() -> str:
    return run(["gh", "api", "user", "-q", ".login"]).stdout.strip()


def check_existing_pr(login: str, branch: str) -> str | None:
    result = run(
        [
            "gh", "pr", "list",
            "--repo", "openvinotoolkit/openvino",
            "--head", f"{login}:{branch}",
            "--json", "url",
            "-q", ".[0].url",
        ],
        check=False,
    )
    url = result.stdout.strip()
    return url if url else None


def get_op_names(state: dict) -> tuple[list[str], str, str]:
    """Return (ops list, slug for branch, title for PR)."""
    orch = state.get("ov_orchestrator", {})
    ops = orch.get("co_located_ops", [])
    if not ops:
        ctx = orch.get("error_context", "unknown")
        ops = [ctx.split("/")[-1]]

    slug = "-".join(o.lower().replace("::", "-").replace("_", "-") for o in ops)
    title = ", ".join(ops)
    return ops, slug, title


def compose_pr_body(ops: list[str], op_title: str) -> str:
    return textwrap.dedent(f"""\
        > [!IMPORTANT]
        > **This PR was generated by a Copilot coding agent and requires human review.**
        > A maintainer must inspect the changes, run the relevant tests locally, and
        > convert this draft to "Ready for review" only after verifying correctness.
        > Do **not** merge without human sign-off.

        ### Details:
         - Add operator support: {op_title}
         - Agent: Enable Operator (`enable-operator.agent.md`)
         - Ops added: {', '.join(ops)}

        ### Tickets:
         - N/A

        ### AI Assistance:
         - AI assistance used: yes
         - Generated by GitHub Copilot agent (`enable-operator`). Human validation required:
           build verification, unit/functional tests, and inference sanity check.
    """)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Print actions without executing git/gh commands")
    args = parser.parse_args()

    state_path = pathlib.Path("agent-results/pipeline_state.json")
    if not state_path.exists():
        print(f"[ERROR] State file not found: {state_path}", file=sys.stderr)
        return 1

    state = json.loads(state_path.read_text(encoding="utf-8"))
    ops, slug, op_title = get_op_names(state)
    branch = f"fix/add-{slug}-op"

    patches = sorted(
        pathlib.Path("agent-results/enable-operator/patches/openvino").glob("*.patch")
    )
    if not patches:
        print("[WARN] No patches to apply — skipping PR creation")
        return 0

    # Check for existing PR to avoid duplicates
    try:
        login = gh_login()
    except subprocess.CalledProcessError:
        print("[ERROR] gh CLI not available or not authenticated", file=sys.stderr)
        return 1

    existing = check_existing_pr(login, branch)
    if existing:
        print(f"[draft-pr] PR already exists: {existing} — skipping creation")
        return 0

    if args.dry_run:
        print(f"[dry-run] Would create branch: {branch}")
        print(f"[dry-run] Would apply {len(patches)} patch(es)")
        print(f"[dry-run] Would open PR: 'Add operator support: {op_title}'")
        return 0

    # Create branch and apply patches
    run(["git", "checkout", "-b", branch])
    for patch in patches:
        run(["git", "am", str(patch)])

    # Ensure fork exists
    run(["gh", "repo", "fork", "openvinotoolkit/openvino", "--clone=false"], check=False)

    # Add fork remote (ignore error if already present)
    fork_ssh = run(
        ["gh", "repo", "view", f"{login}/openvino", "--json", "sshUrl", "-q", ".sshUrl"]
    ).stdout.strip()
    run(["git", "remote", "add", "fork", fork_ssh], check=False)
    run(["git", "push", "fork", branch])

    # Write PR body
    pr_body_path = pathlib.Path("agent-results/enable-operator/pr_body.md")
    pr_body_path.write_text(compose_pr_body(ops, op_title), encoding="utf-8")

    # Open draft PR
    result = run([
        "gh", "pr", "create",
        "--repo", "openvinotoolkit/openvino",
        "--head", f"{login}:{branch}",
        "--title", f"Add operator support: {op_title}",
        "--body-file", str(pr_body_path),
        "--draft",
    ])
    pr_url = result.stdout.strip()
    print(f"[OV-ORCH] [publish] openvino PR opened: {pr_url}")

    # Update pipeline state
    state.setdefault("ov_orchestrator", {})["pr_url"] = pr_url
    state.setdefault("ov_orchestrator", {})["overall_status"] = "success"
    state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")

    return 0


if __name__ == "__main__":
    sys.exit(main())
