name: 'Verify that Python stub .pyi files are up to date'
description: 'Generates .pyi files and compares them to the committed files'
runs:
  using: 'composite'
  steps:
    - name: List checked-out files
      shell: bash
      run: find action_root

    - name: Verify .pyi files
      shell: bash
      if: runner.os != 'Windows'
      run: |
        action_root/src/bindings/python/scripts/generate_pyapi_stubs.sh \
          "${{ runner.temp }}/generated_pyi_files"
        python3 action_root/src/bindings/python/scripts/compare_pyi_files.py \
          "${{ runner.temp }}/generated_pyi_files" \
          "action_root/src/bindings/python"
