name: 'Verify that Python stub .pyi files are up to date'
description: 'Generates .pyi files and compares them to the committed files'
runs:
  using: 'composite'
  steps:
    - name: Verify .pyi files (Windows)
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        ${{ env.OPENVINO_REPO }}\src\bindings\python\scripts\generate_pyapi_stubs.bat `
          "${{ env.ACTION_PATH }}\generated_pyi_files"
        python ${{ env.ACTION_PATH }}\compare_pyi_files.py `
          "${{ env.ACTION_PATH }}\generated_pyi_files" `
          "${{ env.OPENVINO_REPO }}\src\bindings\python"

    - name: Verify .pyi files (Linux and macOS)
      shell: bash
      if: runner.os != 'Windows'
        ${{ env.OPENVINO_REPO }}/src/bindings/python/scripts/generate_pyapi_stubs.sh \
          "${{ env.ACTION_PATH }}/generated_pyi_files"
        python3 ${{ env.ACTION_PATH }}/compare_pyi_files.py \
          "${{ env.ACTION_PATH }}/generated_pyi_files" \
          "${{ env.OPENVINO_REPO }}/src/bindings/python"
