# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(PYOPENVINO_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/core/async_infer_queue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/compiled_model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/core.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/infer_request.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/offline_transformations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/profiling_info.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/properties/properties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/remote_context.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/remote_tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/variable_state.cpp
    ${CMAKE_CURRENT_LIST_DIR}/core/version.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental/experimental.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/frontend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/input_model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/node_context.cpp
    ${CMAKE_CURRENT_LIST_DIR}/frontend/place.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/attribute_visitor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/axis_set.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/axis_vector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/coordinate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/coordinate_diff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/descriptors/tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/dict_attribute_visitor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/dimension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/discrete_type_info.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/layout_helpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/node_factory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/node_input.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/node_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/op_extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/internal/gqa_extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/paged_attention_extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/parameter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/read_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/result.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/arithmetic_reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/binary_elementwise_arithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/binary_elementwise_comparison.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/binary_elementwise_logical.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/index_reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/multisubgraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/regmodule_graph_op_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/unary_elementwise_arithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/ops/util/variable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/partial_shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/graph_rewrite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/matcher_pass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/model_pass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/pass_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/pattern_ops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/predicate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/regmodule_graph_passes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/passes/transformations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/preprocess/pre_post_process.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/rt_map.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/strides.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/symbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/types/element_type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/types/regmodule_graph_types.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pyopenvino.cpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/utils.cpp
)
