# type: ignore
from __future__ import annotations
from openvino._pyopenvino.experimental.pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_0 import evaluate_as_partial_shape
from openvino._pyopenvino.experimental.pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_0 import evaluate_both_bounds
from openvino._pyopenvino.experimental.pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_0 import set_element_type
from openvino._pyopenvino.experimental.pybind11_detail_function_record_v1_system_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_0 import set_tensor_type
"""

Package: openvino
This module provides access to experimental functionality that is subject to change without prior notice.
"""
__all__ = ['evaluate_as_partial_shape', 'evaluate_both_bounds', 'set_element_type', 'set_tensor_type']
