# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# Explicit source list for the main graph target (impls/* backends are built
# separately as OBJECT libraries via add_subdirectory and excluded here).
set(GPU_GRAPH_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/activation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/adaptive_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/arg_max_min.cpp
    ${CMAKE_CURRENT_LIST_DIR}/assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/border.cpp
    ${CMAKE_CURRENT_LIST_DIR}/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/dispatch_utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/dispatch_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/jit_term.hpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/jitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/jitter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/kernel_generator_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/kernel_generator_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/parallel_mem_streambuf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common_utils/parallel_mem_streambuf.hpp
    ${CMAKE_CURRENT_LIST_DIR}/compilation_context.cpp
    ${CMAKE_CURRENT_LIST_DIR}/concatenation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/condition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert_color.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/crop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/custom_gpu_primitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/debug_helper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/debug_helper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/deconvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embedding_bag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/error_handler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_generate_proposal_single_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_roi_feature_extractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_topk_rois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/extract_image_patches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fake_convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fully_connected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gated_mlp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/add_onednn_optimization_attributes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/add_required_reorders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/basic_memory_dependencies.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/build_implementations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/compile_graph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/concat_input_order.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/fuse_primitives_with_layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/graph_initializations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/handle_reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/mark_nodes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/mark_runtime_skippable_nodes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/mark_shape_of_subgraphs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/mark_state_init_subgraphs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/oooq_memory_dependencies.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/post_input_reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/post_optimize_weights.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/pre_replace_deconv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/prepare_buffer_fusing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/prepare_buffer_fusing.h
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/prepare_padding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/prepare_primitive_fusing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/prepare_primitive_fusing_through.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/prepare_quantization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/propagate_constants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/remove_redundant_reorders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/reorder_inputs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/reorder_transfer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/select_preferred_formats.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/skipped_branch_memory_dependencies.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/trim_to_outputs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_optimizer/update_inner_program_io_map.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grouped_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gru_seq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/include/activation_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/adaptive_pooling_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/allocation_order.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/arg_max_min_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/assign_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/batch_to_space_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/border_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/broadcast_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/bucketize_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/col2im_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/concatenation_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/condition_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/convert_color_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/convolution_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/crop_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/ctc_greedy_decoder_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/ctc_loss_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/cum_sum_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/custom_gpu_primitive_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/data_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/deconvolution_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/depth_to_space_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/detection_output_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/dft_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/dynamic_quantize_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/eltwise_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/embedding_bag_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/experimental_detectron_detection_output_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/experimental_detectron_generate_proposals_single_image_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/experimental_detectron_prior_grid_generator_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/experimental_detectron_roi_feature_extractor_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/experimental_detectron_topk_rois_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/extract_image_patches_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/eye_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/fake_convert_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/fully_connected_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gated_delta_net_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gated_mlp_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gather_elements_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gather_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gather_matmul_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gather_nd_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gather_tree_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gemm_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/generate_proposals_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/grid_sample_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/grn_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/group_normalization_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/grouped_matmul_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/gru_seq_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/input_layout_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/istft_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/json_object.h
    ${CMAKE_CURRENT_LIST_DIR}/include/kv_cache_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/layout_optimizer.h
    ${CMAKE_CURRENT_LIST_DIR}/include/loop_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/lora_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/lrn_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/lstm_cell_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/lstm_seq_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/matrix_nms_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/memory_accessor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/memory_dependency_set.h
    ${CMAKE_CURRENT_LIST_DIR}/include/mlir_primitive_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/moe_3gemm_fused_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/moe_gather_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/moe_gemm_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/moe_mask_gen_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/moe_router_fused_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/moe_scatter_reduction_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/multiclass_nms_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/multinomial_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/mutable_data_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/mvn_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/non_max_suppression_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/non_zero_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/normalize_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/one_hot_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/pa_kv_reorder_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/paged_attention_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/paged_causal_conv1d_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/paged_gated_delta_net_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/paged_selective_ssm_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/pass_manager.h
    ${CMAKE_CURRENT_LIST_DIR}/include/permute_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/pooling_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/primitive_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/primitive_type.h
    ${CMAKE_CURRENT_LIST_DIR}/include/primitive_type_base.h
    ${CMAKE_CURRENT_LIST_DIR}/include/prior_box_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/program_dump_graph.h
    ${CMAKE_CURRENT_LIST_DIR}/include/program_helpers.h
    ${CMAKE_CURRENT_LIST_DIR}/include/program_node.h
    ${CMAKE_CURRENT_LIST_DIR}/include/proposal_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/quantize_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/random_uniform_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/range_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/read_value_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/reduce_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/region_yolo_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/reorder_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/reorg_yolo_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/resample_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/reshape_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/reverse_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/reverse_sequence_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/rms_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/roi_align_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/roi_pooling_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/roll_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/rope_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/scaled_dot_product_attention_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/scatter_elements_update_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/scatter_nd_update_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/scatter_update_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/search_sorted_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/segment_max_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/select_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/selective_ssm_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/shape_of_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/shuffle_channels_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/slice_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/slice_scatter_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sliding_window_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/softmax_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/space_to_batch_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/space_to_depth_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sparse_fill_empty_rows_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/stateless_kv_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/stft_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/strided_slice_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/swiglu_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/tile_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/include/to_string_utils.h
    ${CMAKE_CURRENT_LIST_DIR}/include/unique_inst.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/variable.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/vl_sdpa_inst.h
    ${CMAKE_CURRENT_LIST_DIR}/input_layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_dump_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_impl_params.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kv_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/layout_optimizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lora.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lstm_seq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_primitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe_3gemm_fused.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe_gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe_gemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe_mask_gen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe_router_fused.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe_scatter_reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mutable_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/network.cpp
    ${CMAKE_CURRENT_LIST_DIR}/nodes_ordering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/non_zero.cpp
    ${CMAKE_CURRENT_LIST_DIR}/normalize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_causal_conv1d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass_manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/permute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/primitive_inst.cpp
    ${CMAKE_CURRENT_LIST_DIR}/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/program.cpp
    ${CMAKE_CURRENT_LIST_DIR}/program_dump_graph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/program_helpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/program_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/read_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce.cpp
    ${CMAKE_CURRENT_LIST_DIR}/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/activations_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/arg_max_min_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/broadcast_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/col2im_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/concatenation_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/convolution_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/crop_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/ctc_loss_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/deconvolution_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/detection_output_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/eltwise_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/fake_convert_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/fully_connected_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gated_delta_net_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gated_mlp_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gather_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gather_matmul_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gather_nd_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gemm_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/group_normalization_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/grouped_matmul_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/gru_seq_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/implementation_manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/implementation_manager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/implementation_map.hpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/loop_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/lora_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/lstm_cell_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/lstm_seq_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/mlir_primitive_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/moe_3gemm_swiglu_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/moe_gather_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/moe_gemm_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/moe_mask_gen_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/moe_router_fused_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/moe_scatter_reduction_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/mvn_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/non_max_suppression_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/pa_kv_reorder_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/paged_attention_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/paged_causal_conv1d_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/paged_gated_delta_net_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/paged_selective_ssm_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/pooling_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/predicates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/predicates.hpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/range_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/reduce_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/registry.hpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/reorder_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/reshape_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/rope_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/scatter_elements_update_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/scatter_nd_update_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/scatter_update_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/sdpa_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/segment_max_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/select_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/selective_ssm_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/shape_of_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/slice_scatter_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/softmax_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/strided_slice_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/tile_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registry/vl_sdpa_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/resample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rope.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scaled_dot_product_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_elements_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/search_sorted.cpp
    ${CMAKE_CURRENT_LIST_DIR}/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_of.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stateless_kv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/swiglu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/topology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/vl_sdpa.cpp
)
