// Copyright (C) 2018-2022 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

#include "openvino/pass/pass.hpp"
#include "transformations_visibility.hpp"

namespace ov {
namespace pass {

/**
 * @brief Resolve collisions for autogenerated names
 */
class TRANSFORMATIONS_API ResolveGeneratedNameCollisions : public ModelPass {
public:
    OPENVINO_RTTI("ChangePlaceholderTypes", "0");
    ResolveGeneratedNameCollisions() = default;
    bool run_on_model(const std::shared_ptr<ov::Model>& model) override;
};

}  // namespace pass
}  // namespace ov

