# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# Sources are grouped by the configuration they are built for, see the joining logic at the end.

set(CPU_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/src)

# sources built for every configuration
set(CPU_PLUGIN_SRCS
    ${CPU_SRC_DIR}/allocation_context.hpp
    ${CPU_SRC_DIR}/async_infer_request.cpp
    ${CPU_SRC_DIR}/async_infer_request.h
    ${CPU_SRC_DIR}/cache/cache_entry.h
    ${CPU_SRC_DIR}/cache/lru_cache.h
    ${CPU_SRC_DIR}/cache/multi_cache.cpp
    ${CPU_SRC_DIR}/cache/multi_cache.h
    ${CPU_SRC_DIR}/compiled_model.cpp
    ${CPU_SRC_DIR}/compiled_model.h
    ${CPU_SRC_DIR}/config.cpp
    ${CPU_SRC_DIR}/config.h
    ${CPU_SRC_DIR}/cpu_map_scheduling.cpp
    ${CPU_SRC_DIR}/cpu_map_scheduling.hpp
    ${CPU_SRC_DIR}/cpu_memory.cpp
    ${CPU_SRC_DIR}/cpu_memory.h
    ${CPU_SRC_DIR}/cpu_parallel.cpp
    ${CPU_SRC_DIR}/cpu_parallel.hpp
    ${CPU_SRC_DIR}/cpu_shape.cpp
    ${CPU_SRC_DIR}/cpu_shape.h
    ${CPU_SRC_DIR}/cpu_streams_calculation.cpp
    ${CPU_SRC_DIR}/cpu_streams_calculation.hpp
    ${CPU_SRC_DIR}/cpu_tensor.cpp
    ${CPU_SRC_DIR}/cpu_tensor.h
    ${CPU_SRC_DIR}/cpu_types.cpp
    ${CPU_SRC_DIR}/cpu_types.h
    ${CPU_SRC_DIR}/dnnl_extension_utils.cpp
    ${CPU_SRC_DIR}/dnnl_extension_utils.h
    ${CPU_SRC_DIR}/dnnl_postops_composer.cpp
    ${CPU_SRC_DIR}/dnnl_postops_composer.h
    ${CPU_SRC_DIR}/dnnl_postops_composer_legacy.cpp
    ${CPU_SRC_DIR}/dnnl_postops_composer_legacy.h
    ${CPU_SRC_DIR}/dnnl_scratch_pad.h
    ${CPU_SRC_DIR}/edge.cpp
    ${CPU_SRC_DIR}/edge.h
    ${CPU_SRC_DIR}/emitters/plugin/common/debug_utils.hpp
    ${CPU_SRC_DIR}/emitters/snippets/brgemm_generic.cpp
    ${CPU_SRC_DIR}/emitters/snippets/brgemm_generic.hpp
    ${CPU_SRC_DIR}/emitters/snippets/common/compiled_snippet_cpu.hpp
    ${CPU_SRC_DIR}/emitters/snippets/common/emitter_factory.hpp
    ${CPU_SRC_DIR}/emitters/snippets/common/jit_debug_emitter_base.hpp
    ${CPU_SRC_DIR}/emitters/snippets/common/jit_segfault_detector_emitter_base.hpp
    ${CPU_SRC_DIR}/emitters/snippets/common/verbose_utils.hpp
    ${CPU_SRC_DIR}/emitters/snippets/cpu_kernel_executor_table.hpp
    ${CPU_SRC_DIR}/emitters/snippets/cpu_runtime_configurator.cpp
    ${CPU_SRC_DIR}/emitters/snippets/cpu_runtime_configurator.hpp
    ${CPU_SRC_DIR}/emitters/snippets/input_repacker.cpp
    ${CPU_SRC_DIR}/emitters/snippets/input_repacker.hpp
    ${CPU_SRC_DIR}/emitters/snippets/jit_snippets_call_args.cpp
    ${CPU_SRC_DIR}/emitters/snippets/jit_snippets_call_args.hpp
    ${CPU_SRC_DIR}/emitters/snippets/utils/debug_caps_config.cpp
    ${CPU_SRC_DIR}/emitters/snippets/utils/debug_caps_config.hpp
    ${CPU_SRC_DIR}/emitters/snippets/utils/utils.cpp
    ${CPU_SRC_DIR}/emitters/snippets/utils/utils.hpp
    ${CPU_SRC_DIR}/emitters/utils.cpp
    ${CPU_SRC_DIR}/emitters/utils.hpp
    ${CPU_SRC_DIR}/extension.cpp
    ${CPU_SRC_DIR}/graph.cpp
    ${CPU_SRC_DIR}/graph.h
    ${CPU_SRC_DIR}/graph_context.cpp
    ${CPU_SRC_DIR}/graph_context.h
    ${CPU_SRC_DIR}/graph_dumper.cpp
    ${CPU_SRC_DIR}/graph_dumper.h
    ${CPU_SRC_DIR}/graph_optimizer.cpp
    ${CPU_SRC_DIR}/graph_optimizer.h
    ${CPU_SRC_DIR}/infer_request.cpp
    ${CPU_SRC_DIR}/infer_request.h
    ${CPU_SRC_DIR}/internal_properties.hpp
    ${CPU_SRC_DIR}/itt.h
    ${CPU_SRC_DIR}/memory_control.cpp
    ${CPU_SRC_DIR}/memory_control.hpp
    ${CPU_SRC_DIR}/memory_desc/blocked_memory_desc.cpp
    ${CPU_SRC_DIR}/memory_desc/blocked_memory_desc.h
    ${CPU_SRC_DIR}/memory_desc/cpu_blocked_memory_desc.cpp
    ${CPU_SRC_DIR}/memory_desc/cpu_blocked_memory_desc.h
    ${CPU_SRC_DIR}/memory_desc/cpu_memory_desc.h
    ${CPU_SRC_DIR}/memory_desc/cpu_memory_desc_utils.cpp
    ${CPU_SRC_DIR}/memory_desc/cpu_memory_desc_utils.h
    ${CPU_SRC_DIR}/memory_desc/dnnl_blocked_memory_desc.cpp
    ${CPU_SRC_DIR}/memory_desc/dnnl_blocked_memory_desc.h
    ${CPU_SRC_DIR}/memory_desc/dnnl_memory_desc.cpp
    ${CPU_SRC_DIR}/memory_desc/dnnl_memory_desc.h
    ${CPU_SRC_DIR}/memory_desc/empty_memory_desc.h
    ${CPU_SRC_DIR}/memory_format_filter.hpp
    ${CPU_SRC_DIR}/memory_state.cpp
    ${CPU_SRC_DIR}/memory_state.h
    ${CPU_SRC_DIR}/node.cpp
    ${CPU_SRC_DIR}/node.h
    ${CPU_SRC_DIR}/nodes/adaptive_pooling.cpp
    ${CPU_SRC_DIR}/nodes/adaptive_pooling.h
    ${CPU_SRC_DIR}/nodes/batch_to_space.cpp
    ${CPU_SRC_DIR}/nodes/batch_to_space.h
    ${CPU_SRC_DIR}/nodes/bin_conv.cpp
    ${CPU_SRC_DIR}/nodes/bin_conv.h
    ${CPU_SRC_DIR}/nodes/broadcast.cpp
    ${CPU_SRC_DIR}/nodes/broadcast.h
    ${CPU_SRC_DIR}/nodes/bucketize.cpp
    ${CPU_SRC_DIR}/nodes/bucketize.h
    ${CPU_SRC_DIR}/nodes/causal_mask_preprocess.cpp
    ${CPU_SRC_DIR}/nodes/causal_mask_preprocess.h
    ${CPU_SRC_DIR}/nodes/col2im.cpp
    ${CPU_SRC_DIR}/nodes/col2im.h
    ${CPU_SRC_DIR}/nodes/color_convert.cpp
    ${CPU_SRC_DIR}/nodes/color_convert.h
    ${CPU_SRC_DIR}/nodes/common/arbitrary_order_desc_creator.cpp
    ${CPU_SRC_DIR}/nodes/common/arbitrary_order_desc_creator.h
    ${CPU_SRC_DIR}/nodes/common/blocked_desc_creator.cpp
    ${CPU_SRC_DIR}/nodes/common/blocked_desc_creator.h
    ${CPU_SRC_DIR}/nodes/common/cpu_convert.cpp
    ${CPU_SRC_DIR}/nodes/common/cpu_convert.h
    ${CPU_SRC_DIR}/nodes/common/cpu_memcpy.h
    ${CPU_SRC_DIR}/nodes/common/dnnl_executor.cpp
    ${CPU_SRC_DIR}/nodes/common/dnnl_executor.h
    ${CPU_SRC_DIR}/nodes/common/permute_kernel.cpp
    ${CPU_SRC_DIR}/nodes/common/permute_kernel.h
    ${CPU_SRC_DIR}/nodes/common/reorder_prim.cpp
    ${CPU_SRC_DIR}/nodes/common/reorder_prim.h
    ${CPU_SRC_DIR}/nodes/common/softmax.cpp
    ${CPU_SRC_DIR}/nodes/common/softmax.h
    ${CPU_SRC_DIR}/nodes/common/tile_broadcast_utils.cpp
    ${CPU_SRC_DIR}/nodes/common/tile_broadcast_utils.h
    ${CPU_SRC_DIR}/nodes/composite.cpp
    ${CPU_SRC_DIR}/nodes/composite.h
    ${CPU_SRC_DIR}/nodes/concat.cpp
    ${CPU_SRC_DIR}/nodes/concat.h
    ${CPU_SRC_DIR}/nodes/conv.cpp
    ${CPU_SRC_DIR}/nodes/conv.h
    ${CPU_SRC_DIR}/nodes/convert.cpp
    ${CPU_SRC_DIR}/nodes/convert.h
    ${CPU_SRC_DIR}/nodes/ctc_greedy_decoder.cpp
    ${CPU_SRC_DIR}/nodes/ctc_greedy_decoder.h
    ${CPU_SRC_DIR}/nodes/ctc_greedy_decoder_seq_len.cpp
    ${CPU_SRC_DIR}/nodes/ctc_greedy_decoder_seq_len.h
    ${CPU_SRC_DIR}/nodes/ctc_loss.cpp
    ${CPU_SRC_DIR}/nodes/ctc_loss.h
    ${CPU_SRC_DIR}/nodes/cum_sum.cpp
    ${CPU_SRC_DIR}/nodes/cum_sum.h
    ${CPU_SRC_DIR}/nodes/deconv.cpp
    ${CPU_SRC_DIR}/nodes/deconv.h
    ${CPU_SRC_DIR}/nodes/def_conv.cpp
    ${CPU_SRC_DIR}/nodes/def_conv.h
    ${CPU_SRC_DIR}/nodes/depth_to_space.cpp
    ${CPU_SRC_DIR}/nodes/depth_to_space.h
    ${CPU_SRC_DIR}/nodes/detection_output.cpp
    ${CPU_SRC_DIR}/nodes/detection_output.h
    ${CPU_SRC_DIR}/nodes/dft.cpp
    ${CPU_SRC_DIR}/nodes/dft.h
    ${CPU_SRC_DIR}/nodes/eltwise.cpp
    ${CPU_SRC_DIR}/nodes/eltwise.h
    ${CPU_SRC_DIR}/nodes/embedding_bag.cpp
    ${CPU_SRC_DIR}/nodes/embedding_bag.h
    ${CPU_SRC_DIR}/nodes/embedding_bag_offsets.cpp
    ${CPU_SRC_DIR}/nodes/embedding_bag_offsets.h
    ${CPU_SRC_DIR}/nodes/embedding_bag_packed.cpp
    ${CPU_SRC_DIR}/nodes/embedding_bag_packed.h
    ${CPU_SRC_DIR}/nodes/embedding_segments_sum.cpp
    ${CPU_SRC_DIR}/nodes/embedding_segments_sum.h
    ${CPU_SRC_DIR}/nodes/executors/common/common_utils.hpp
    ${CPU_SRC_DIR}/nodes/executors/common/offset_helper.hpp
    ${CPU_SRC_DIR}/nodes/executors/common/paged_selective_ssm_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/common/paged_selective_ssm_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/common/ref_convert.cpp
    ${CPU_SRC_DIR}/nodes/executors/common/ref_convert.hpp
    ${CPU_SRC_DIR}/nodes/executors/common/ref_opt_transpose.cpp
    ${CPU_SRC_DIR}/nodes/executors/common/ref_opt_transpose.hpp
    ${CPU_SRC_DIR}/nodes/executors/common/ref_transpose.cpp
    ${CPU_SRC_DIR}/nodes/executors/common/ref_transpose.hpp
    ${CPU_SRC_DIR}/nodes/executors/common/selective_ssm_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/common/selective_ssm_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/convert.cpp
    ${CPU_SRC_DIR}/nodes/executors/convert.hpp
    ${CPU_SRC_DIR}/nodes/executors/convert_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/convert_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/convolution_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/convolution_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/debug_messages.hpp
    ${CPU_SRC_DIR}/nodes/executors/deconv.hpp
    ${CPU_SRC_DIR}/nodes/executors/deconv_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/deconv_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_aliases.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_convolution_primitive.cpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_convolution_primitive.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_fullyconnected_primitive.cpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_fullyconnected_primitive.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_gathermatmul_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_gathermatmul_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_matmul_primitive.cpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_matmul_primitive.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_post_op_data.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_shape_agnostic_data.hpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_utils.cpp
    ${CPU_SRC_DIR}/nodes/executors/dnnl/dnnl_utils.hpp
    ${CPU_SRC_DIR}/nodes/executors/eltwise_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/eltwise_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/eltwise_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/eltwise_stateful_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/eltwise_stateful_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/executor_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/executor_factory.hpp
    ${CPU_SRC_DIR}/nodes/executors/executor_implementation.hpp
    ${CPU_SRC_DIR}/nodes/executors/fullyconnected_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/fullyconnected_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/gated_delta_net_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/gathermatmul_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/gathermatmul_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/gdn_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/graph_emitter.hpp
    ${CPU_SRC_DIR}/nodes/executors/implementation_utils.hpp
    ${CPU_SRC_DIR}/nodes/executors/implementations.hpp
    ${CPU_SRC_DIR}/nodes/executors/interpolate.cpp
    ${CPU_SRC_DIR}/nodes/executors/interpolate.hpp
    ${CPU_SRC_DIR}/nodes/executors/interpolate_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/interpolate_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/jit/eltwise.cpp
    ${CPU_SRC_DIR}/nodes/executors/jit/eltwise.h
    ${CPU_SRC_DIR}/nodes/executors/matmul_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/matmul_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/memory_arguments.hpp
    ${CPU_SRC_DIR}/nodes/executors/mvn.cpp
    ${CPU_SRC_DIR}/nodes/executors/mvn.hpp
    ${CPU_SRC_DIR}/nodes/executors/mvn_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/mvn_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/paged_selective_ssm_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/paged_selective_ssm_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/pooling.cpp
    ${CPU_SRC_DIR}/nodes/executors/pooling.hpp
    ${CPU_SRC_DIR}/nodes/executors/pooling_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/pooling_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/precision_matcher.cpp
    ${CPU_SRC_DIR}/nodes/executors/precision_matcher.hpp
    ${CPU_SRC_DIR}/nodes/executors/precision_translation.cpp
    ${CPU_SRC_DIR}/nodes/executors/precision_translation.hpp
    ${CPU_SRC_DIR}/nodes/executors/printers.cpp
    ${CPU_SRC_DIR}/nodes/executors/printers.hpp
    ${CPU_SRC_DIR}/nodes/executors/reduce.cpp
    ${CPU_SRC_DIR}/nodes/executors/reduce.hpp
    ${CPU_SRC_DIR}/nodes/executors/reduce_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/reduce_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/ref/eltwise.cpp
    ${CPU_SRC_DIR}/nodes/executors/ref/eltwise.hpp
    ${CPU_SRC_DIR}/nodes/executors/ref/gdn_ref_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/ref/gdn_ref_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/repacking_subgraph.hpp
    ${CPU_SRC_DIR}/nodes/executors/selective_ssm_config.hpp
    ${CPU_SRC_DIR}/nodes/executors/selective_ssm_implementations.cpp
    ${CPU_SRC_DIR}/nodes/executors/subgraph.cpp
    ${CPU_SRC_DIR}/nodes/executors/subgraph.hpp
    ${CPU_SRC_DIR}/nodes/executors/transpose.cpp
    ${CPU_SRC_DIR}/nodes/executors/transpose.hpp
    ${CPU_SRC_DIR}/nodes/executors/transpose_list.cpp
    ${CPU_SRC_DIR}/nodes/executors/transpose_list.hpp
    ${CPU_SRC_DIR}/nodes/executors/type_mask.hpp
    ${CPU_SRC_DIR}/nodes/executors/variable_executor.hpp
    ${CPU_SRC_DIR}/nodes/experimental_detectron_detection_output.cpp
    ${CPU_SRC_DIR}/nodes/experimental_detectron_detection_output.h
    ${CPU_SRC_DIR}/nodes/experimental_detectron_generate_proposals_single_image.cpp
    ${CPU_SRC_DIR}/nodes/experimental_detectron_generate_proposals_single_image.h
    ${CPU_SRC_DIR}/nodes/experimental_detectron_priorgridgenerator.cpp
    ${CPU_SRC_DIR}/nodes/experimental_detectron_priorgridgenerator.h
    ${CPU_SRC_DIR}/nodes/experimental_detectron_roifeatureextractor.cpp
    ${CPU_SRC_DIR}/nodes/experimental_detectron_roifeatureextractor.h
    ${CPU_SRC_DIR}/nodes/experimental_detectron_topkrois.cpp
    ${CPU_SRC_DIR}/nodes/experimental_detectron_topkrois.h
    ${CPU_SRC_DIR}/nodes/extract_image_patches.cpp
    ${CPU_SRC_DIR}/nodes/extract_image_patches.h
    ${CPU_SRC_DIR}/nodes/eye.cpp
    ${CPU_SRC_DIR}/nodes/eye.h
    ${CPU_SRC_DIR}/nodes/fake_quantize.cpp
    ${CPU_SRC_DIR}/nodes/fake_quantize.h
    ${CPU_SRC_DIR}/nodes/fullyconnected.cpp
    ${CPU_SRC_DIR}/nodes/fullyconnected.h
    ${CPU_SRC_DIR}/nodes/gated_delta_net.cpp
    ${CPU_SRC_DIR}/nodes/gated_delta_net.h
    ${CPU_SRC_DIR}/nodes/gather.cpp
    ${CPU_SRC_DIR}/nodes/gather.h
    ${CPU_SRC_DIR}/nodes/gather_elements.cpp
    ${CPU_SRC_DIR}/nodes/gather_elements.h
    ${CPU_SRC_DIR}/nodes/gather_nd.cpp
    ${CPU_SRC_DIR}/nodes/gather_nd.h
    ${CPU_SRC_DIR}/nodes/gather_tree.cpp
    ${CPU_SRC_DIR}/nodes/gather_tree.h
    ${CPU_SRC_DIR}/nodes/gathermatmul.cpp
    ${CPU_SRC_DIR}/nodes/gathermatmul.h
    ${CPU_SRC_DIR}/nodes/generate_proposals.cpp
    ${CPU_SRC_DIR}/nodes/generate_proposals.h
    ${CPU_SRC_DIR}/nodes/grid_sample.cpp
    ${CPU_SRC_DIR}/nodes/grid_sample.hpp
    ${CPU_SRC_DIR}/nodes/grn.cpp
    ${CPU_SRC_DIR}/nodes/grn.h
    ${CPU_SRC_DIR}/nodes/identity.cpp
    ${CPU_SRC_DIR}/nodes/identity.hpp
    ${CPU_SRC_DIR}/nodes/if.cpp
    ${CPU_SRC_DIR}/nodes/if.h
    ${CPU_SRC_DIR}/nodes/input.cpp
    ${CPU_SRC_DIR}/nodes/input.h
    ${CPU_SRC_DIR}/nodes/interaction.cpp
    ${CPU_SRC_DIR}/nodes/interaction.h
    ${CPU_SRC_DIR}/nodes/interpolate.cpp
    ${CPU_SRC_DIR}/nodes/interpolate.h
    ${CPU_SRC_DIR}/nodes/inverse.cpp
    ${CPU_SRC_DIR}/nodes/inverse.hpp
    ${CPU_SRC_DIR}/nodes/istft.cpp
    ${CPU_SRC_DIR}/nodes/istft.h
    ${CPU_SRC_DIR}/nodes/kernels/jit_eltwise_common.cpp
    ${CPU_SRC_DIR}/nodes/kernels/jit_eltwise_common.hpp
    ${CPU_SRC_DIR}/nodes/kernels/kai/kleidi_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/linear_attn/recurrent_linear_attn.cpp
    ${CPU_SRC_DIR}/nodes/kernels/linear_attn/recurrent_linear_attn.hpp
    ${CPU_SRC_DIR}/nodes/kernels/paged_causal_conv1d.cpp
    ${CPU_SRC_DIR}/nodes/kernels/paged_causal_conv1d.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/attn_memcpy.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/attn_memcpy.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/attn_quant.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/attn_quant.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/attn_quant_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/cache_reorder.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/cache_reorder.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/cache_rotation.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/cache_spec.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/codec_kernels.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/codecs.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/common_quantize.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/turboq_codec.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/turboq_quantize.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/turboq_quantize.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/turboq_rotation.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/turboq_rotation.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/codecs/turboq_tables.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/common.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/executor_pa.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/executor_pa.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/executor_pa_common.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/executor_pa_common.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/mha_kv_cache_codec.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/mha_kv_cache_codec.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/mha_kv_cache_reduce.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/mha_single_token.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/mha_single_token.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/paged_attn_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/sage_attn.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/softmax.cpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/softmax.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/softmax_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/transpose.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/transpose_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/scaled_attn/xattention.hpp
    ${CPU_SRC_DIR}/nodes/kernels/selective_ssm.cpp
    ${CPU_SRC_DIR}/nodes/kernels/selective_ssm.hpp
    ${CPU_SRC_DIR}/nodes/kernels/simd/simd.hpp
    ${CPU_SRC_DIR}/nodes/kernels/simd/simd_avx2.hpp
    ${CPU_SRC_DIR}/nodes/kernels/simd/simd_avx512.hpp
    ${CPU_SRC_DIR}/nodes/kernels/simd/simd_common.hpp
    ${CPU_SRC_DIR}/nodes/kernels/simd/simd_loop.hpp
    ${CPU_SRC_DIR}/nodes/kernels/simd/simd_scalar.hpp
    ${CPU_SRC_DIR}/nodes/llm_mlp.cpp
    ${CPU_SRC_DIR}/nodes/llm_mlp.h
    ${CPU_SRC_DIR}/nodes/log_softmax.cpp
    ${CPU_SRC_DIR}/nodes/log_softmax.h
    ${CPU_SRC_DIR}/nodes/lora.cpp
    ${CPU_SRC_DIR}/nodes/lora.h
    ${CPU_SRC_DIR}/nodes/lrn.cpp
    ${CPU_SRC_DIR}/nodes/lrn.h
    ${CPU_SRC_DIR}/nodes/mathematics.cpp
    ${CPU_SRC_DIR}/nodes/mathematics.h
    ${CPU_SRC_DIR}/nodes/matmul.cpp
    ${CPU_SRC_DIR}/nodes/matmul.h
    ${CPU_SRC_DIR}/nodes/matrix_nms.cpp
    ${CPU_SRC_DIR}/nodes/matrix_nms.h
    ${CPU_SRC_DIR}/nodes/memory.cpp
    ${CPU_SRC_DIR}/nodes/memory.hpp
    ${CPU_SRC_DIR}/nodes/memory_state_base.cpp
    ${CPU_SRC_DIR}/nodes/memory_state_base.h
    ${CPU_SRC_DIR}/nodes/multiclass_nms.cpp
    ${CPU_SRC_DIR}/nodes/multiclass_nms.hpp
    ${CPU_SRC_DIR}/nodes/multinomial.cpp
    ${CPU_SRC_DIR}/nodes/multinomial.hpp
    ${CPU_SRC_DIR}/nodes/mvn.cpp
    ${CPU_SRC_DIR}/nodes/mvn.h
    ${CPU_SRC_DIR}/nodes/ngram.cpp
    ${CPU_SRC_DIR}/nodes/ngram.h
    ${CPU_SRC_DIR}/nodes/node_config.h
    ${CPU_SRC_DIR}/nodes/non_max_suppression.cpp
    ${CPU_SRC_DIR}/nodes/non_max_suppression.h
    ${CPU_SRC_DIR}/nodes/non_zero.cpp
    ${CPU_SRC_DIR}/nodes/non_zero.h
    ${CPU_SRC_DIR}/nodes/normalize.cpp
    ${CPU_SRC_DIR}/nodes/normalize.h
    ${CPU_SRC_DIR}/nodes/one_hot.cpp
    ${CPU_SRC_DIR}/nodes/one_hot.h
    ${CPU_SRC_DIR}/nodes/pa_kv_reorder.cpp
    ${CPU_SRC_DIR}/nodes/pa_kv_reorder.hpp
    ${CPU_SRC_DIR}/nodes/pad.cpp
    ${CPU_SRC_DIR}/nodes/pad.h
    ${CPU_SRC_DIR}/nodes/paged_attn.cpp
    ${CPU_SRC_DIR}/nodes/paged_attn.h
    ${CPU_SRC_DIR}/nodes/paged_causal_conv1d.cpp
    ${CPU_SRC_DIR}/nodes/paged_causal_conv1d.h
    ${CPU_SRC_DIR}/nodes/paged_gated_delta_net.cpp
    ${CPU_SRC_DIR}/nodes/paged_gated_delta_net.h
    ${CPU_SRC_DIR}/nodes/paged_selective_ssm.cpp
    ${CPU_SRC_DIR}/nodes/paged_selective_ssm.h
    ${CPU_SRC_DIR}/nodes/pooling.cpp
    ${CPU_SRC_DIR}/nodes/pooling.h
    ${CPU_SRC_DIR}/nodes/priorbox.cpp
    ${CPU_SRC_DIR}/nodes/priorbox.h
    ${CPU_SRC_DIR}/nodes/priorbox_clustered.cpp
    ${CPU_SRC_DIR}/nodes/priorbox_clustered.h
    ${CPU_SRC_DIR}/nodes/proposal.cpp
    ${CPU_SRC_DIR}/nodes/proposal.h
    ${CPU_SRC_DIR}/nodes/proposal_imp.cpp
    ${CPU_SRC_DIR}/nodes/proposal_imp.hpp
    ${CPU_SRC_DIR}/nodes/psroi_pooling.cpp
    ${CPU_SRC_DIR}/nodes/psroi_pooling.h
    ${CPU_SRC_DIR}/nodes/qkv_proj.cpp
    ${CPU_SRC_DIR}/nodes/qkv_proj.h
    ${CPU_SRC_DIR}/nodes/random_uniform.cpp
    ${CPU_SRC_DIR}/nodes/random_uniform.hpp
    ${CPU_SRC_DIR}/nodes/range.cpp
    ${CPU_SRC_DIR}/nodes/range.h
    ${CPU_SRC_DIR}/nodes/rdft.cpp
    ${CPU_SRC_DIR}/nodes/rdft.h
    ${CPU_SRC_DIR}/nodes/reduce.cpp
    ${CPU_SRC_DIR}/nodes/reduce.h
    ${CPU_SRC_DIR}/nodes/reference.cpp
    ${CPU_SRC_DIR}/nodes/reference.h
    ${CPU_SRC_DIR}/nodes/region_yolo.cpp
    ${CPU_SRC_DIR}/nodes/region_yolo.h
    ${CPU_SRC_DIR}/nodes/reorder.cpp
    ${CPU_SRC_DIR}/nodes/reorder.h
    ${CPU_SRC_DIR}/nodes/reorg_yolo.cpp
    ${CPU_SRC_DIR}/nodes/reorg_yolo.h
    ${CPU_SRC_DIR}/nodes/reshape.cpp
    ${CPU_SRC_DIR}/nodes/reshape.h
    ${CPU_SRC_DIR}/nodes/reverse_sequence.cpp
    ${CPU_SRC_DIR}/nodes/reverse_sequence.h
    ${CPU_SRC_DIR}/nodes/rms_norm.cpp
    ${CPU_SRC_DIR}/nodes/rms_norm.h
    ${CPU_SRC_DIR}/nodes/rnn.cpp
    ${CPU_SRC_DIR}/nodes/rnn.h
    ${CPU_SRC_DIR}/nodes/roi_align.cpp
    ${CPU_SRC_DIR}/nodes/roi_align.h
    ${CPU_SRC_DIR}/nodes/roi_align_rotated.cpp
    ${CPU_SRC_DIR}/nodes/roi_align_rotated.h
    ${CPU_SRC_DIR}/nodes/roi_pooling.cpp
    ${CPU_SRC_DIR}/nodes/roi_pooling.h
    ${CPU_SRC_DIR}/nodes/roll.cpp
    ${CPU_SRC_DIR}/nodes/roll.h
    ${CPU_SRC_DIR}/nodes/rope.cpp
    ${CPU_SRC_DIR}/nodes/rope.h
    ${CPU_SRC_DIR}/nodes/scaled_attn.cpp
    ${CPU_SRC_DIR}/nodes/scaled_attn.h
    ${CPU_SRC_DIR}/nodes/scatter_update.cpp
    ${CPU_SRC_DIR}/nodes/scatter_update.h
    ${CPU_SRC_DIR}/nodes/search_sorted.cpp
    ${CPU_SRC_DIR}/nodes/search_sorted.h
    ${CPU_SRC_DIR}/nodes/segment_max.cpp
    ${CPU_SRC_DIR}/nodes/segment_max.h
    ${CPU_SRC_DIR}/nodes/selective_ssm.cpp
    ${CPU_SRC_DIR}/nodes/selective_ssm.h
    ${CPU_SRC_DIR}/nodes/shapeof.cpp
    ${CPU_SRC_DIR}/nodes/shapeof.h
    ${CPU_SRC_DIR}/nodes/shuffle_channels.cpp
    ${CPU_SRC_DIR}/nodes/shuffle_channels.h
    ${CPU_SRC_DIR}/nodes/softmax.cpp
    ${CPU_SRC_DIR}/nodes/softmax.h
    ${CPU_SRC_DIR}/nodes/space_to_batch.cpp
    ${CPU_SRC_DIR}/nodes/space_to_batch.h
    ${CPU_SRC_DIR}/nodes/space_to_depth.cpp
    ${CPU_SRC_DIR}/nodes/space_to_depth.h
    ${CPU_SRC_DIR}/nodes/sparse_fill_empty_rows.cpp
    ${CPU_SRC_DIR}/nodes/sparse_fill_empty_rows.h
    ${CPU_SRC_DIR}/nodes/split.cpp
    ${CPU_SRC_DIR}/nodes/split.h
    ${CPU_SRC_DIR}/nodes/stft.cpp
    ${CPU_SRC_DIR}/nodes/stft.h
    ${CPU_SRC_DIR}/nodes/strided_slice.cpp
    ${CPU_SRC_DIR}/nodes/strided_slice.h
    ${CPU_SRC_DIR}/nodes/string_tensor_pack.cpp
    ${CPU_SRC_DIR}/nodes/string_tensor_pack.h
    ${CPU_SRC_DIR}/nodes/string_tensor_unpack.cpp
    ${CPU_SRC_DIR}/nodes/string_tensor_unpack.h
    ${CPU_SRC_DIR}/nodes/subgraph.cpp
    ${CPU_SRC_DIR}/nodes/subgraph.h
    ${CPU_SRC_DIR}/nodes/tensoriterator.cpp
    ${CPU_SRC_DIR}/nodes/tensoriterator.h
    ${CPU_SRC_DIR}/nodes/tile.cpp
    ${CPU_SRC_DIR}/nodes/tile.h
    ${CPU_SRC_DIR}/nodes/topk.cpp
    ${CPU_SRC_DIR}/nodes/topk.h
    ${CPU_SRC_DIR}/nodes/transpose.cpp
    ${CPU_SRC_DIR}/nodes/transpose.h
    ${CPU_SRC_DIR}/nodes/unique.cpp
    ${CPU_SRC_DIR}/nodes/unique.hpp
    ${CPU_SRC_DIR}/nodes_factory.cpp
    ${CPU_SRC_DIR}/onednn/dnnl.cpp
    ${CPU_SRC_DIR}/onednn/dnnl.h
    ${CPU_SRC_DIR}/onednn/iml_type_mapper.cpp
    ${CPU_SRC_DIR}/onednn/iml_type_mapper.h
    ${CPU_SRC_DIR}/partitioned_mem_blk.cpp
    ${CPU_SRC_DIR}/partitioned_mem_blk.h
    ${CPU_SRC_DIR}/perf_count.h
    ${CPU_SRC_DIR}/plugin.cpp
    ${CPU_SRC_DIR}/plugin.h
    ${CPU_SRC_DIR}/post_ops.cpp
    ${CPU_SRC_DIR}/post_ops.hpp
    ${CPU_SRC_DIR}/proxy_mem_blk.cpp
    ${CPU_SRC_DIR}/proxy_mem_blk.h
    ${CPU_SRC_DIR}/selective_build.h
    ${CPU_SRC_DIR}/shape_inference/custom/adaptive_pooling.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/adaptive_pooling.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/color_convert.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/color_convert.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/convolution.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/convolution.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/eltwise.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/eltwise.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/fullyconnected.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/fullyconnected.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/gather.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/gather.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/gathermatmul.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/gathermatmul.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/matmul.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/matmul.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/ngram.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/ngram.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/one_hot.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/one_hot.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/priorbox.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/priorbox.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/priorbox_clustered.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/priorbox_clustered.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/reshape.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/reshape.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/rms_norm.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/rms_norm.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/scaled_attn.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/scaled_attn.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/shapeof.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/strided_slice.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/strided_slice.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/subgraph.hpp
    ${CPU_SRC_DIR}/shape_inference/custom/transpose.cpp
    ${CPU_SRC_DIR}/shape_inference/custom/transpose.hpp
    ${CPU_SRC_DIR}/shape_inference/memory_accessor.hpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference.cpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference.hpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference_cpu.cpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference_cpu.hpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference_internal_dyn.hpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference_pass_through.hpp
    ${CPU_SRC_DIR}/shape_inference/shape_inference_status.hpp
    ${CPU_SRC_DIR}/shape_inference/static_dimension.cpp
    ${CPU_SRC_DIR}/shape_inference/static_dimension.hpp
    ${CPU_SRC_DIR}/shape_inference/static_shape.cpp
    ${CPU_SRC_DIR}/shape_inference/static_shape.hpp
    ${CPU_SRC_DIR}/sigstack_manager.cpp
    ${CPU_SRC_DIR}/sigstack_manager.h
    ${CPU_SRC_DIR}/sub_memory_manager.hpp
    ${CPU_SRC_DIR}/thread_pool_imp.cpp
    ${CPU_SRC_DIR}/thread_pool_imp.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/causal_mask_preprocess.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/causal_mask_preprocess.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/leaky_relu.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/leaky_relu.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/ngram.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/ngram.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/power_static.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/power_static.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/read_value_with_subgraph.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/read_value_with_subgraph.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/sdpa.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/sdpa.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/submodel.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/submodel.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/swish_cpu.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/op/swish_cpu.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/align_matmul_input_ranks.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/align_matmul_input_ranks.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/causal_mask_preprocess_fusion.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_broadcast_to_tiles.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_broadcast_to_tiles.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_fq_rnn_to_quantized_rnn.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_fq_rnn_to_quantized_rnn.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_matmul_to_fc.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_matmul_to_fc.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_tile_to_seq_tiles.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_tile_to_seq_tiles.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_to_leaky_relu.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_to_leaky_relu.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_to_power_static.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_to_power_static.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_to_swish_cpu.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/convert_to_swish_cpu.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/decompose_integer_divide.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/decompose_integer_divide.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/decompose_rms_norm.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/decompose_rms_norm.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/disable_bf16_comp_cumsum_sin_gen.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/disable_bf16_comp_cumsum_sin_gen.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/fc_bias_fusion.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/fc_bias_fusion.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/insert_convert_after_extension.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/insert_convert_after_extension.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/move_readvalue_inputs_to_subgraph.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/move_readvalue_inputs_to_subgraph.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/ngram_fusion.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/ngram_fusion.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/permute_slice_n_interpolation.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/permute_slice_n_interpolation.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/rnn_sequences_optimization.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/rnn_sequences_optimization.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/stateful_sdpa_fusion.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/stateful_sdpa_fusion.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/swap_convert_transpose.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/common/pass/swap_convert_transpose.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/convert_to_cpu_specific_opset.hpp
    ${CPU_SRC_DIR}/transformations/defs.hpp
    ${CPU_SRC_DIR}/transformations/itt.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/op/fused_mul_add.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/op/fused_mul_add.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/op/load_convert.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/op/load_convert.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/op/store_convert.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/op/store_convert.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/eliminate_copy_b.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/eliminate_copy_b.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/enforce_precision.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/enforce_precision.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/lowered/adjust_copy_b_loop_ports.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/lowered/adjust_copy_b_loop_ports.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/lowered/external_repacking_adjuster.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/lowered/external_repacking_adjuster.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/lowered/fuse_load_store_and_convert.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/lowered/fuse_load_store_and_convert.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/mul_add_to_fma.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/mul_add_to_fma.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/repack_matmul_weights.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/pass/repack_matmul_weights.hpp
    ${CPU_SRC_DIR}/transformations/snippets/common/shape_inference.cpp
    ${CPU_SRC_DIR}/transformations/snippets/common/shape_inference.hpp
    ${CPU_SRC_DIR}/transformations/transformation_pipeline.cpp
    ${CPU_SRC_DIR}/transformations/transformation_pipeline.h
    ${CPU_SRC_DIR}/transformations/utils.cpp
    ${CPU_SRC_DIR}/transformations/utils.hpp
    ${CPU_SRC_DIR}/utils/arch_macros.h
    ${CPU_SRC_DIR}/utils/arm_isa_support.cpp
    ${CPU_SRC_DIR}/utils/arm_isa_support.h
    ${CPU_SRC_DIR}/utils/bfloat16.hpp
    ${CPU_SRC_DIR}/utils/bit_util.hpp
    ${CPU_SRC_DIR}/utils/blob_dump.cpp
    ${CPU_SRC_DIR}/utils/blob_dump.h
    ${CPU_SRC_DIR}/utils/caseless.hpp
    ${CPU_SRC_DIR}/utils/codec_xor.cpp
    ${CPU_SRC_DIR}/utils/codec_xor.hpp
    ${CPU_SRC_DIR}/utils/cpp/bit_cast.hpp
    ${CPU_SRC_DIR}/utils/cpp/to_underlying.hpp
    ${CPU_SRC_DIR}/utils/cpu_utils.hpp
    ${CPU_SRC_DIR}/utils/debug_capabilities.h
    ${CPU_SRC_DIR}/utils/debug_caps_config.h
    ${CPU_SRC_DIR}/utils/denormals.hpp
    ${CPU_SRC_DIR}/utils/general_utils.h
    ${CPU_SRC_DIR}/utils/graph_serializer/deserializer.cpp
    ${CPU_SRC_DIR}/utils/graph_serializer/deserializer.hpp
    ${CPU_SRC_DIR}/utils/graph_serializer/serializer.cpp
    ${CPU_SRC_DIR}/utils/graph_serializer/serializer.hpp
    ${CPU_SRC_DIR}/utils/memory_stats_dump.hpp
    ${CPU_SRC_DIR}/utils/multidim_map.hpp
    ${CPU_SRC_DIR}/utils/ngraph_transformation.hpp
    ${CPU_SRC_DIR}/utils/ngraph_utils.hpp
    ${CPU_SRC_DIR}/utils/node_dumper.h
    ${CPU_SRC_DIR}/utils/plain_tensor.hpp
    ${CPU_SRC_DIR}/utils/platform.h
    ${CPU_SRC_DIR}/utils/precision_support.cpp
    ${CPU_SRC_DIR}/utils/precision_support.h
    ${CPU_SRC_DIR}/utils/rt_info/memory_formats_attribute.cpp
    ${CPU_SRC_DIR}/utils/rt_info/memory_formats_attribute.hpp
    ${CPU_SRC_DIR}/utils/verbose.h
    ${CPU_SRC_DIR}/weights_cache.cpp
    ${CPU_SRC_DIR}/weights_cache.hpp
)

set(CPU_PLUGIN_ACL_SRCS
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_common_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_common_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_conv.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_conv.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_convert.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_convert.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_deconv.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_deconv.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_eltwise.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_eltwise.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_fullyconnected.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_fullyconnected.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_fullyconnected_utils.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_fullyconnected_utils.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_ie_scheduler.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_ie_scheduler.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_interpolate.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_interpolate.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_lowp_fullyconnected.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_lowp_fullyconnected.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_mvn.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_mvn.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_pooling.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_pooling.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_reduce.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_reduce.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_transpose.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_transpose.hpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_utils.cpp
    ${CPU_SRC_DIR}/nodes/executors/acl/acl_utils.hpp
    ${CPU_SRC_DIR}/nodes/kernels/acl/gemm_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/acl/gemm_kernel.hpp
)

set(CPU_PLUGIN_X64_SRCS
    ${CPU_SRC_DIR}/emitters/plugin/x64/debug_capabilities.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/debug_capabilities.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_bf16_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_conversion_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_conversion_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_dnnl_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_dnnl_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_dnnl_ext_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_eltwise_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_eltwise_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_emitter.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_emitter.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_load_store_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/jit_load_store_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/utils.cpp
    ${CPU_SRC_DIR}/emitters/plugin/x64/utils.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/cpu_generator.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/cpu_generator.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_binary_call_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_binary_call_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_brgemm_copy_b_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_brgemm_copy_b_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_brgemm_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_brgemm_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_debug_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_fill_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_fill_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_horizon_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_horizon_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_kernel_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_kernel_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_loop_base_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_loop_base_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_loop_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_loop_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_memory_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_memory_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_parallel_loop_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_parallel_loop_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_perf_count_chrono_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_perf_count_chrono_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_perf_count_rdtsc_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_perf_count_rdtsc_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_reg_spill_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_reg_spill_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_segfault_detector_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_segfault_detector_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_snippets_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/jit_snippets_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm_amx.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm_amx.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm_base.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm_base.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm_copy_b.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/brgemm_copy_b.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/parallel_loop.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/kernel_executors/parallel_loop.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/utils.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/utils.hpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/verbose.cpp
    ${CPU_SRC_DIR}/emitters/snippets/x64/verbose.hpp
    ${CPU_SRC_DIR}/nodes/executors/x64/gdn_jit_executor.cpp
    ${CPU_SRC_DIR}/nodes/executors/x64/gdn_jit_executor.hpp
    ${CPU_SRC_DIR}/nodes/executors/x64/jit_transpose.cpp
    ${CPU_SRC_DIR}/nodes/executors/x64/jit_transpose.hpp
    ${CPU_SRC_DIR}/nodes/executors/x64/matmul_small.cpp
    ${CPU_SRC_DIR}/nodes/executors/x64/matmul_small.hpp
    ${CPU_SRC_DIR}/nodes/executors/x64/subgraph.cpp
    ${CPU_SRC_DIR}/nodes/executors/x64/subgraph.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/brgemm_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/brgemm_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/dft_uni_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/dft_uni_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/gather_uni_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/gather_uni_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/gdn_jit_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/gdn_jit_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/grid_sample.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/grid_sample.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_kernel_base.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_kernel_base.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_matmul_small.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_matmul_small.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_uni_eltwise_generic.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/jit_uni_eltwise_generic.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/mlp_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/mlp_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/mlp_utils.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/mlp_utils.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/non_max_suppression.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/non_max_suppression.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/random_uniform.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/random_uniform.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/rdft_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/rdft_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/registers_pool.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/rms_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/rms_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/rope_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/x64/rope_kernel.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/op/interaction.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/op/interaction.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/op/llm_mlp.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/op/llm_mlp.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/op/qkv_proj.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/op/qkv_proj.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/convert_to_interaction.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/convert_to_interaction.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/mlp_fusion.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/mlp_fusion.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/qkv_proj_fusion.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/qkv_proj_fusion.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/sdpa_fuse_transpose_reshape.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/sdpa_fuse_transpose_reshape.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/x64/pass/simplify_fakequantize.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/brgemm_copy_b.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/brgemm_copy_b.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/brgemm_cpu.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/brgemm_cpu.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/brgemm_utils.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/brgemm_utils.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/perf_count_rdtsc.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/op/perf_count_rdtsc.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/brgemm_to_brgemm_cpu.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/brgemm_to_brgemm_cpu.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/eliminate_brgemm_copy_b.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/eliminate_brgemm_copy_b.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/fuse_brgemm_cpu_postops.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/fuse_brgemm_cpu_postops.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/adjust_brgemm_copy_b_loop_ports.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/adjust_brgemm_copy_b_loop_ports.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/brgemm_copy_b_loop_ports_adjuster.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/brgemm_copy_b_loop_ports_adjuster.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/brgemm_cpu_blocking.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/expressions/brgemm_copy_b_buffer_expressions.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/expressions/brgemm_copy_b_buffer_expressions.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/external_repacking_adjuster.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/insert_brgemm_copy_buffers.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/insert_brgemm_copy_buffers.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/parallelize_gated_mlp_n_loops.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/lowered/parallelize_gated_mlp_n_loops.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/remove_converts.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/remove_converts.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/repack_matmul_weights.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/repack_matmul_weights.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/snippets_mark_skipped.cpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/pass/snippets_mark_skipped.hpp
    ${CPU_SRC_DIR}/transformations/snippets/x64/shape_inference.cpp
)

set(CPU_PLUGIN_TPP_X64_SRCS
    ${CPU_SRC_DIR}/emitters/tpp/x64/jit_brgemm_emitter.cpp
    ${CPU_SRC_DIR}/emitters/tpp/x64/jit_brgemm_emitter.hpp
    ${CPU_SRC_DIR}/emitters/tpp/x64/jit_debug_emitter.hpp
    ${CPU_SRC_DIR}/emitters/tpp/x64/jit_tpp_emitter.cpp
    ${CPU_SRC_DIR}/emitters/tpp/x64/jit_tpp_emitter.hpp
)

set(CPU_PLUGIN_ARM_SRCS
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/debug_capabilities.cpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/debug_capabilities.hpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_conversion_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_conversion_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_conversion_helpers.hpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_eltwise_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_emitter.cpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_emitter.hpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_load_store_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/aarch64/jit_load_store_emitters.hpp
    ${CPU_SRC_DIR}/nodes/kernels/aarch64/brgemm_kernel.cpp
    ${CPU_SRC_DIR}/nodes/kernels/aarch64/brgemm_kernel.hpp
    ${CPU_SRC_DIR}/nodes/kernels/aarch64/jit_uni_eltwise_generic.cpp
    ${CPU_SRC_DIR}/nodes/kernels/aarch64/jit_uni_eltwise_generic.hpp
    ${CPU_SRC_DIR}/nodes/kernels/aarch64/sve_utils.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/align_unsupported_lp_conv_fq_precision.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/align_unsupported_lp_conv_fq_precision.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/conv_mul_add_fq_block.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/conv_mul_add_fq_block.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_conv_bias.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_fc_bias.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_gemm_bias.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_group_conv.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_group_conv.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_group_conv1d.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_group_conv1d.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_reduce_multi_axis.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_reduce_multi_axis.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_reduce_no_keep_dims.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/convert_reduce_no_keep_dims.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/deconv_1d_decomposition.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/deconv_1d_decomposition.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/fallback_unsupported_lp_conv_to_fp16.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/fallback_unsupported_lp_conv_to_fp16.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/fc_mul_add_fq_block.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/fc_mul_add_fq_block.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/grid_sample_decomposition.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/grid_sample_decomposition.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/mish_decomposition.cpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/mish_decomposition.hpp
    ${CPU_SRC_DIR}/transformations/cpu_opset/arm/pass/mul_add_fq_tail.hpp
)

set(CPU_PLUGIN_TPP_AARCH64_SRCS
    ${CPU_SRC_DIR}/emitters/tpp/aarch64/jit_brgemm_emitter.cpp
    ${CPU_SRC_DIR}/emitters/tpp/aarch64/jit_brgemm_emitter.hpp
)

set(CPU_PLUGIN_AARCH64_SRCS
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/cpu_generator.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/cpu_generator.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_binary_call_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_binary_call_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_debug_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_fill_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_fill_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_gemm_copy_b_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_gemm_copy_b_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_gemm_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_gemm_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_horizon_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_horizon_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_kernel_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_kernel_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_loop_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_loop_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_memory_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_memory_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_perf_count_chrono_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_perf_count_chrono_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_reg_spill_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_reg_spill_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_segfault_detector_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_segfault_detector_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_snippets_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/jit_snippets_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/kernel_executors/gemm.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/kernel_executors/gemm.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/kernel_executors/gemm_copy_b.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/kernel_executors/gemm_copy_b.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/utils.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/utils.hpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/verbose.cpp
    ${CPU_SRC_DIR}/emitters/snippets/aarch64/verbose.hpp
    ${CPU_SRC_DIR}/nodes/executors/aarch64/subgraph.cpp
    ${CPU_SRC_DIR}/nodes/executors/aarch64/subgraph.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/op/gemm_copy_b.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/op/gemm_copy_b.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/op/gemm_cpu.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/op/gemm_cpu.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/op/gemm_utils.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/op/gemm_utils.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/brgemm_to_gemm_cpu.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/brgemm_to_gemm_cpu.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/eliminate_gemm_copy_b.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/eliminate_gemm_copy_b.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/adjust_gemm_copy_b_loop_ports.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/adjust_gemm_copy_b_loop_ports.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/expressions/gemm_copy_b_buffer_expressions.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/expressions/gemm_copy_b_buffer_expressions.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/external_repacking_adjuster.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/external_repacking_adjuster.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/gemm_copy_b_loop_ports_adjuster.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/gemm_copy_b_loop_ports_adjuster.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/gemm_cpu_blocking.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/gemm_cpu_blocking.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/insert_gemm_copy_buffers.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/lowered/insert_gemm_copy_buffers.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/repack_matmul_weights.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/repack_matmul_weights.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/snippets_mark_skipped.cpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/pass/snippets_mark_skipped.hpp
    ${CPU_SRC_DIR}/transformations/snippets/aarch64/shape_inference.cpp
)

set(CPU_PLUGIN_KLEIDIAI_SRCS
    ${CPU_SRC_DIR}/nodes/executors/kleidiai/kleidiai_common.hpp
    ${CPU_SRC_DIR}/nodes/executors/kleidiai/kleidiai_gathermatmul.cpp
    ${CPU_SRC_DIR}/nodes/executors/kleidiai/kleidiai_gathermatmul.hpp
    ${CPU_SRC_DIR}/nodes/executors/kleidiai/kleidiai_mm.cpp
    ${CPU_SRC_DIR}/nodes/executors/kleidiai/kleidiai_mm.hpp
)

set(CPU_PLUGIN_RISCV64_SRCS
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/debug_capabilities.cpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/debug_capabilities.hpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_context_helpers.cpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_context_helpers.hpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_conversion_helpers.cpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_conversion_helpers.hpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_eltwise_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_eltwise_emitters.hpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_emitter.cpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_emitter.hpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_load_store_emitters.cpp
    ${CPU_SRC_DIR}/emitters/plugin/riscv64/jit_load_store_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/cpu_generator.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/cpu_generator.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_binary_call_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_binary_call_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_brgemm_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_brgemm_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_debug_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_fill_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_fill_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_horizon_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_horizon_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_kernel_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_kernel_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_loop_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_loop_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_memory_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_memory_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_perf_count_chrono_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_perf_count_chrono_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_reg_spill_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_reg_spill_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_segfault_detector_emitter.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_segfault_detector_emitter.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_snippets_emitters.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/jit_snippets_emitters.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/kernel_executors/brgemm.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/kernel_executors/brgemm.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/utils.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/utils.hpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/verbose.cpp
    ${CPU_SRC_DIR}/emitters/snippets/riscv64/verbose.hpp
    ${CPU_SRC_DIR}/nodes/executors/riscv64/subgraph.cpp
    ${CPU_SRC_DIR}/nodes/executors/riscv64/subgraph.hpp
    ${CPU_SRC_DIR}/nodes/kernels/riscv64/cpu_isa_traits.cpp
    ${CPU_SRC_DIR}/nodes/kernels/riscv64/cpu_isa_traits.hpp
    ${CPU_SRC_DIR}/nodes/kernels/riscv64/jit_generator.cpp
    ${CPU_SRC_DIR}/nodes/kernels/riscv64/jit_generator.hpp
    ${CPU_SRC_DIR}/nodes/kernels/riscv64/jit_uni_eltwise_generic.cpp
    ${CPU_SRC_DIR}/nodes/kernels/riscv64/jit_uni_eltwise_generic.hpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/op/brgemm_cpu.cpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/op/brgemm_cpu.hpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/op/brgemm_utils.hpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/pass/brgemm_to_brgemm_cpu.cpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/pass/brgemm_to_brgemm_cpu.hpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/pass/lowered/brgemm_cpu_blocking.cpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/pass/lowered/brgemm_cpu_blocking.hpp
    ${CPU_SRC_DIR}/transformations/snippets/riscv64/shape_inference.cpp
)

set(CPU_PLUGIN_MLAS_SRCS
    ${CPU_SRC_DIR}/mlas/sgemm.cpp
    ${CPU_SRC_DIR}/mlas/sgemm.hpp
    ${CPU_SRC_DIR}/mlas/thread_pool.cpp
    ${CPU_SRC_DIR}/mlas/thread_pool.hpp
    ${CPU_SRC_DIR}/nodes/executors/mlas/mlas_gemm.cpp
    ${CPU_SRC_DIR}/nodes/executors/mlas/mlas_gemm.hpp
    ${CPU_SRC_DIR}/nodes/executors/mlas/mlas_transpose.cpp
    ${CPU_SRC_DIR}/nodes/executors/mlas/mlas_transpose.hpp
)

set(CPU_PLUGIN_TPP_SRCS
    ${CPU_SRC_DIR}/emitters/tpp/common/kernel_executors/brgemm.cpp
    ${CPU_SRC_DIR}/emitters/tpp/common/kernel_executors/brgemm.hpp
    ${CPU_SRC_DIR}/emitters/tpp/common/utils.hpp
    ${CPU_SRC_DIR}/transformations/tpp/common/op/brgemm.cpp
    ${CPU_SRC_DIR}/transformations/tpp/common/op/brgemm.hpp
    ${CPU_SRC_DIR}/transformations/tpp/common/op/modifiers.hpp
    ${CPU_SRC_DIR}/transformations/tpp/common/pass/brgemm_to_brgemm_tpp.cpp
    ${CPU_SRC_DIR}/transformations/tpp/common/pass/brgemm_to_brgemm_tpp.hpp
    ${CPU_SRC_DIR}/transformations/tpp/common/pass/lowered/brgemm_tpp_blocking.cpp
    ${CPU_SRC_DIR}/transformations/tpp/common/pass/lowered/brgemm_tpp_blocking.hpp
    ${CPU_SRC_DIR}/transformations/tpp/common/pass/lowered/set_tpp_leading_dim.cpp
    ${CPU_SRC_DIR}/transformations/tpp/common/pass/lowered/set_tpp_leading_dim.hpp
)

# used when no architecture-specific snippets shape inference is available
set(CPU_PLUGIN_GENERIC_ARCH_SRCS
    ${CPU_SRC_DIR}/transformations/snippets/common/shape_inference_fallback.cpp
)

set(CPU_PLUGIN_DEBUG_CAPS_SRCS
    ${CPU_SRC_DIR}/utils/debug_capabilities.cpp
    ${CPU_SRC_DIR}/utils/debug_caps_config.cpp
    ${CPU_SRC_DIR}/utils/memory_stats_dump.cpp
    ${CPU_SRC_DIR}/utils/node_dumper.cpp
    ${CPU_SRC_DIR}/utils/verbose.cpp
)

if(OV_CPU_WITH_ACL)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_ACL_SRCS})
endif()

if(X86_64)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_X64_SRCS})
    if(ENABLE_SNIPPETS_LIBXSMM_TPP)
        list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_TPP_X64_SRCS})
    endif()
endif()

if(ARM OR AARCH64)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_ARM_SRCS})
    if(ENABLE_SNIPPETS_LIBXSMM_TPP)
        list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_TPP_AARCH64_SRCS})
    endif()
endif()

if(AARCH64)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_AARCH64_SRCS} ${CPU_PLUGIN_KLEIDIAI_SRCS})
endif()

if(RISCV64)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_RISCV64_SRCS})
endif()

if(NOT (X86_64 OR AARCH64 OR RISCV64))
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_GENERIC_ARCH_SRCS})
endif()

if(ENABLE_MLAS_FOR_CPU)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_MLAS_SRCS})
endif()

if(ENABLE_SNIPPETS_LIBXSMM_TPP)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_TPP_SRCS})
endif()

if(ENABLE_CPU_DEBUG_CAPS)
    list(APPEND CPU_PLUGIN_SRCS ${CPU_PLUGIN_DEBUG_CAPS_SRCS})
endif()
