fail-on-severity: 'low'
allow-licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'Apache-2.0'
fail-on-scopes:
  - 'runtime'
  - 'development'
  - 'unknown'
license-check: true
vulnerability-check: true
