# See help here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  #
  # Python product dependencies
  #

  #
  # Root Python dependencies (pyproject.toml)
  #
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 20
    assignees:
      - "p-wysocki"
      - "akuporos"
      - "rkazants"
      - "mryzhov"
    versioning-strategy: increase-if-necessary
    groups:
      pip-root:
        patterns:
          - "*"

  # Python API, Frontends
  - package-ecosystem: pip
    directory: "/src/bindings/python/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 10
    assignees:
      - "p-wysocki"
      - "akuporos"
      - "rkazants"
      - "ceciliapeng2011"
      - "almilosz"
    versioning-strategy: increase-if-necessary
    groups:
      pip-python-api:
        patterns:
          - "*"

  # Tests
  - package-ecosystem: pip
    directory: "/tests"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 10
    assignees:
      - "p-wysocki"
      - "akuporos"
      - "rkazants"
    versioning-strategy: increase-if-necessary
    groups:
      pip-tests:
        patterns:
          - "*"

  # ovc and Benchmark tools
  - package-ecosystem: pip
    directory: "/tools"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 10
    assignees:
      - "rkazants"
      - "andrei-kochin"
      - "p-wysocki"
      - "akuporos"
      - "Wovchena"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    versioning-strategy: increase-if-necessary
    groups:
      pip-tools:
        patterns:
          - "*"

  #
  # Python Samples
  #

  - package-ecosystem: pip
    directories:
      - "/samples/python/hello_reshape_ssd/"
      - "/samples/python/classification_sample_async/"
      - "/samples/python/benchmark/bert_benchmark/"
      - "/samples/python/hello_classification/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    open-pull-requests-limit: 10
    assignees:
      - "Wovchena"
      - "p-wysocki"
      - "akuporos"
      - "rkazants"
    versioning-strategy: increase-if-necessary
    groups:
      pip-samples:
        patterns:
          - "*"

  # JavaScript API (Node.js bindings)
  - package-ecosystem: npm
    directory: "/src/bindings/js/node/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
      - "mlukasze"
      - "Retribution98"
      - "almilosz"
    versioning-strategy: lockfile-only
    groups:
      npm-packages:
        patterns:
          - "*"

  # JavaScript samples (Node.js)
  - package-ecosystem: npm
    directory: "/samples/js/node/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Poland"
    open-pull-requests-limit: 3
    assignees:
      - "mlukasze"
      - "Retribution98"
      - "almilosz"
    versioning-strategy: lockfile-only
    groups:
      npm-packages:
        patterns:
          - "*"

  #
  # Github actions - CI
  #

  # Custom Github actions (Node.js)
  - package-ecosystem: npm
    directories:
      - "/.github/actions/**/*"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    assignees:
      - "akashchi"
      - "mryzhov"
      - "akladiev"
    open-pull-requests-limit: 10
    groups:
      npm-actions:
        patterns:
          - "*"

  # Github action workflows
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    assignees:
      - "akashchi"
      - "mryzhov"
      - "akladiev"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker images
  - package-ecosystem: docker
    directories:
      - "/.github/dockerfiles/**/*"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Dubai"
    allow:
      - dependency-type: "direct"
    assignees:
      - "akashchi"
      - "mryzhov"
      - "akladiev"
    open-pull-requests-limit: 10
    groups:
      docker-images:
        patterns:
          - "*"
