#version 450

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) readonly buffer Intermediate {
    float values[];
} intermediate_data;

layout(set = 0, binding = 1) writeonly buffer Output {
    float values[];
} output_data;

void main() {
    const uint global_index = gl_GlobalInvocationID.x;
    output_data.values[global_index] = intermediate_data.values[global_index] * 2.0;
}
