#version 450

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;
layout(constant_id = 1) const uint local_memory_words = 64;

layout(set = 0, binding = 0) readonly buffer Input {
    float values[];
} input_data;

layout(set = 0, binding = 1) writeonly buffer Intermediate {
    float values[];
} intermediate_data;

shared float local_values[local_memory_words];

void main() {
    const uint global_index = gl_GlobalInvocationID.x;
    const uint local_index = gl_LocalInvocationID.x;
    local_values[local_index] = input_data.values[global_index];
    barrier();
    const uint adjacent_index = (local_index + 1) % local_memory_words;
    intermediate_data.values[global_index] = local_values[adjacent_index] + 1.0;
}
