# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(OV_CORE_TESTS_VISITORS_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/dimension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/partial_shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/user_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/value_map.cpp
    ${CMAKE_CURRENT_LIST_DIR}/visitors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/abs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/acos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/acosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adaptive_avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adaptive_max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/asin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/asinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/atan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/atanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/binary_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_left_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_rigth_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ceiling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/clamp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert_color_i420.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert_color_nv12.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert_promote_types.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convolution_backprop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_greedy_decoder_seq_len.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/deformable_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/deformable_psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/divide.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/elu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embedding_segments_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_offsets.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_offsetssum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_packed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_packedsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/erf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/erfinv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/exp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_topkrois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/extractimagepatches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fake_convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fake_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/floor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/floor_mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/framework_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/glu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/greater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/greater_equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/group_conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/grouped_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gru_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gru_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hard_sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hsigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hswish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/idft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/inverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/irdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/is_finite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/is_inf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/is_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/less.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/less_equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lstm_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/maximum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/minimum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multiply.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/negative.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/non_zero.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/normalize_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/not_equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/paged_causal_conv1d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/parameter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/power.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/prelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/prior_box_clustered.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/read_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_l1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_logical_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_logical_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_mean.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_min.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_prod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/result.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rms_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rnn_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rnn_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/round.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scaled_dot_product_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_elements_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/selu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/shape_of.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softplus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softsign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sorted_search.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sqrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/squared_difference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/squeeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/string_tensor_pack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/string_tensor_unpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/subtract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/swish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/topk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unsqueeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/variadic_split.cpp
)
