# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS openvino::pugixml openvino::gflags_nothreads_static openvino::nlohmann_json openvino::itt openvino::conditional_compilation openvino::util openvino::snippets openvino::offline_transformations openvino::reference openvino::shape_inference openvino::core::dev openvino::openvino_runtime_s openvino::runtime::dev openvino::format_reader openvino::ie_samples_utils openvino::interpreter_backend)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target openvino::pugixml
add_library(openvino::pugixml STATIC IMPORTED)

set_target_properties(openvino::pugixml PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<BOOL:OFF>:PUGIXML_WCHAR_MODE>;\$<\$<BOOL:OFF>:PUGIXML_COMPACT>;\$<\$<BOOL:OFF>:PUGIXML_NO_XPATH>;\$<\$<BOOL:OFF>:PUGIXML_NO_STL>;\$<\$<BOOL:OFF>:PUGIXML_NO_EXCEPTIONS>"
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/thirdparty/pugixml/src"
)

# Create imported target openvino::gflags_nothreads_static
add_library(openvino::gflags_nothreads_static STATIC IMPORTED)

set_target_properties(openvino::gflags_nothreads_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GFLAGS_IS_A_DLL=0"
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/thirdparty/gflags/gflags/include"
  INTERFACE_LINK_LIBRARIES "shlwapi.lib"
)

# Create imported target openvino::nlohmann_json
add_library(openvino::nlohmann_json INTERFACE IMPORTED)

set_target_properties(openvino::nlohmann_json PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<BOOL:ON>>:JSON_USE_GLOBAL_UDLS=0>;\$<\$<NOT:\$<BOOL:ON>>:JSON_USE_IMPLICIT_CONVERSIONS=0>;\$<\$<BOOL:OFF>:JSON_DISABLE_ENUM_SERIALIZATION=1>;\$<\$<BOOL:OFF>:JSON_DIAGNOSTICS=1>;\$<\$<BOOL:OFF>:JSON_USE_LEGACY_DISCARDED_VALUE_COMPARISON=1>"
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/thirdparty/json/nlohmann_json/include/"
  INTERFACE_SOURCES "D:/OPENVINO/openvino/thirdparty/json/nlohmann_json/nlohmann_json.natvis"
)

# Create imported target openvino::itt
add_library(openvino::itt STATIC IMPORTED)

set_target_properties(openvino::itt PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/common/itt/include"
  INTERFACE_LINK_LIBRARIES "openvino::util"
)

# Create imported target openvino::conditional_compilation
add_library(openvino::conditional_compilation INTERFACE IMPORTED)

set_target_properties(openvino::conditional_compilation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/common/conditional_compilation/include"
  INTERFACE_LINK_LIBRARIES "openvino::itt"
)

# Create imported target openvino::util
add_library(openvino::util STATIC IMPORTED)

set_target_properties(openvino::util PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/common/util/include/"
  INTERFACE_LINK_LIBRARIES "openvino::pugixml;\$<LINK_ONLY:Shlwapi>"
)

# Create imported target openvino::snippets
add_library(openvino::snippets STATIC IMPORTED)

set_target_properties(openvino::snippets PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/common/snippets/include"
  INTERFACE_LINK_LIBRARIES "openvino::runtime;\$<LINK_ONLY:openvino::reference>;\$<LINK_ONLY:openvino::runtime::dev>;\$<LINK_ONLY:openvino::conditional_compilation>"
)

# Create imported target openvino::offline_transformations
add_library(openvino::offline_transformations STATIC IMPORTED)

set_target_properties(openvino::offline_transformations PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/common/offline_transformations/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openvino::core::dev>;\$<LINK_ONLY:openvino::reference>;\$<LINK_ONLY:openvino::runtime>"
)

# Create imported target openvino::reference
add_library(openvino::reference STATIC IMPORTED)

set_target_properties(openvino::reference PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TBB_PREVIEW_WAITING_FOR_WORKERS=1;IE_THREAD=IE_THREAD_TBB;OV_THREAD=OV_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/core/reference/include;D:/OPENVINO/openvino/src/core/dev_api;D:/OPENVINO/openvino/src/core/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:TBB::tbb>;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:openvino::core::dev>"
)

# Create imported target openvino::shape_inference
add_library(openvino::shape_inference STATIC IMPORTED)

set_target_properties(openvino::shape_inference PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/core/shape_inference/include;D:/OPENVINO/openvino/src/core/include;\$<TARGET_PROPERTY:openvino::core::dev,INTERFACE_INCLUDE_DIRECTORIES>"
)

# Create imported target openvino::core::dev
add_library(openvino::core::dev INTERFACE IMPORTED)

set_target_properties(openvino::core::dev PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/core/include;D:/OPENVINO/openvino/src/core/dev_api;D:/OPENVINO/openvino/src/frontends/common/include;D:/OPENVINO/openvino/src/common/transformations/include;D:/OPENVINO/openvino/src/common/low_precision_transformations/include"
  INTERFACE_LINK_LIBRARIES "openvino::itt;openvino::util"
)

# Create imported target openvino::openvino_runtime_s
add_library(openvino::openvino_runtime_s STATIC IMPORTED)

set_target_properties(openvino::openvino_runtime_s PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TBB_PREVIEW_WAITING_FOR_WORKERS=1;IE_THREAD=IE_THREAD_TBB;OV_THREAD=OV_THREAD_TBB;USE_STATIC_IE"
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/inference/src"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:TBB::tbb>;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:openvino::itt>;\$<LINK_ONLY:openvino::runtime::dev>;\$<LINK_ONLY:openvino::pugixml>"
)

# Create imported target openvino::runtime::dev
add_library(openvino::runtime::dev INTERFACE IMPORTED)

set_target_properties(openvino::runtime::dev PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "TBB_PREVIEW_WAITING_FOR_WORKERS=1;IE_THREAD=IE_THREAD_TBB;OV_THREAD=OV_THREAD_TBB"
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/inference/dev_api;D:/OPENVINO/openvino/temp/tbb/include"
  INTERFACE_LINK_LIBRARIES "openvino::runtime;openvino::core::dev;TBB::tbb;Threads::Threads"
)

# Create imported target openvino::format_reader
add_library(openvino::format_reader STATIC IMPORTED)

set_target_properties(openvino::format_reader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/samples/cpp/common/format_reader/include"
)

# Create imported target openvino::ie_samples_utils
add_library(openvino::ie_samples_utils STATIC IMPORTED)

set_target_properties(openvino::ie_samples_utils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/samples/cpp/common/utils/include"
  INTERFACE_LINK_LIBRARIES "openvino::runtime;\$<LINK_ONLY:openvino::gflags_nothreads_static>"
)

# Create imported target openvino::interpreter_backend
add_library(openvino::interpreter_backend STATIC IMPORTED)

set_target_properties(openvino::interpreter_backend PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OPENVINO/openvino/src/plugins/template/backend;D:/OPENVINO/openvino/src/plugins/template/backend/ops/"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openvino::reference>;\$<LINK_ONLY:openvino::util>;\$<LINK_ONLY:openvino::runtime::dev>;\$<LINK_ONLY:openvino::shape_inference>"
)

# Import target "openvino::pugixml" for configuration "Debug"
set_property(TARGET openvino::pugixml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::pugixml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/pugixmld.lib"
  )

# Import target "openvino::gflags_nothreads_static" for configuration "Debug"
set_property(TARGET openvino::gflags_nothreads_static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::gflags_nothreads_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/gflags_nothreads_static_debug.lib"
  )

# Import target "openvino::itt" for configuration "Debug"
set_property(TARGET openvino::itt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::itt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_ittd.lib"
  )

# Import target "openvino::util" for configuration "Debug"
set_property(TARGET openvino::util APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::util PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_utild.lib"
  )

# Import target "openvino::snippets" for configuration "Debug"
set_property(TARGET openvino::snippets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::snippets PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_snippetsd.lib"
  )

# Import target "openvino::offline_transformations" for configuration "Debug"
set_property(TARGET openvino::offline_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::offline_transformations PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_offline_transformationsd.lib"
  )

# Import target "openvino::reference" for configuration "Debug"
set_property(TARGET openvino::reference APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::reference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_referenced.lib"
  )

# Import target "openvino::shape_inference" for configuration "Debug"
set_property(TARGET openvino::shape_inference APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::shape_inference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_shape_inferenced.lib"
  )

# Import target "openvino::openvino_runtime_s" for configuration "Debug"
set_property(TARGET openvino::openvino_runtime_s APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::openvino_runtime_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_runtime_sd.lib"
  )

# Import target "openvino::format_reader" for configuration "Debug"
set_property(TARGET openvino::format_reader APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::format_reader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/format_readerd.lib"
  )

# Import target "openvino::ie_samples_utils" for configuration "Debug"
set_property(TARGET openvino::ie_samples_utils APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::ie_samples_utils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/ie_samples_utilsd.lib"
  )

# Import target "openvino::interpreter_backend" for configuration "Debug"
set_property(TARGET openvino::interpreter_backend APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(openvino::interpreter_backend PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/OPENVINO/openvino/bin/intel64/Debug/openvino_interpreter_backendd.lib"
  )

# Import target "openvino::pugixml" for configuration "Release"
set_property(TARGET openvino::pugixml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::pugixml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/pugixml.lib"
  )

# Import target "openvino::gflags_nothreads_static" for configuration "Release"
set_property(TARGET openvino::gflags_nothreads_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::gflags_nothreads_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/gflags_nothreads_static.lib"
  )

# Import target "openvino::itt" for configuration "Release"
set_property(TARGET openvino::itt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::itt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_itt.lib"
  )

# Import target "openvino::util" for configuration "Release"
set_property(TARGET openvino::util APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::util PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_util.lib"
  )

# Import target "openvino::snippets" for configuration "Release"
set_property(TARGET openvino::snippets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::snippets PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_snippets.lib"
  )

# Import target "openvino::offline_transformations" for configuration "Release"
set_property(TARGET openvino::offline_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::offline_transformations PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_offline_transformations.lib"
  )

# Import target "openvino::reference" for configuration "Release"
set_property(TARGET openvino::reference APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::reference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_reference.lib"
  )

# Import target "openvino::shape_inference" for configuration "Release"
set_property(TARGET openvino::shape_inference APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::shape_inference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_shape_inference.lib"
  )

# Import target "openvino::openvino_runtime_s" for configuration "Release"
set_property(TARGET openvino::openvino_runtime_s APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::openvino_runtime_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_runtime_s.lib"
  )

# Import target "openvino::format_reader" for configuration "Release"
set_property(TARGET openvino::format_reader APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::format_reader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/format_reader.lib"
  )

# Import target "openvino::ie_samples_utils" for configuration "Release"
set_property(TARGET openvino::ie_samples_utils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::ie_samples_utils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/ie_samples_utils.lib"
  )

# Import target "openvino::interpreter_backend" for configuration "Release"
set_property(TARGET openvino::interpreter_backend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(openvino::interpreter_backend PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/OPENVINO/openvino/bin/intel64/Release/openvino_interpreter_backend.lib"
  )

# Import target "openvino::pugixml" for configuration "MinSizeRel"
set_property(TARGET openvino::pugixml APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::pugixml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/pugixml.lib"
  )

# Import target "openvino::gflags_nothreads_static" for configuration "MinSizeRel"
set_property(TARGET openvino::gflags_nothreads_static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::gflags_nothreads_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/gflags_nothreads_static.lib"
  )

# Import target "openvino::itt" for configuration "MinSizeRel"
set_property(TARGET openvino::itt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::itt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_itt.lib"
  )

# Import target "openvino::util" for configuration "MinSizeRel"
set_property(TARGET openvino::util APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::util PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_util.lib"
  )

# Import target "openvino::snippets" for configuration "MinSizeRel"
set_property(TARGET openvino::snippets APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::snippets PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_snippets.lib"
  )

# Import target "openvino::offline_transformations" for configuration "MinSizeRel"
set_property(TARGET openvino::offline_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::offline_transformations PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_offline_transformations.lib"
  )

# Import target "openvino::reference" for configuration "MinSizeRel"
set_property(TARGET openvino::reference APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::reference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_reference.lib"
  )

# Import target "openvino::shape_inference" for configuration "MinSizeRel"
set_property(TARGET openvino::shape_inference APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::shape_inference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_shape_inference.lib"
  )

# Import target "openvino::openvino_runtime_s" for configuration "MinSizeRel"
set_property(TARGET openvino::openvino_runtime_s APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::openvino_runtime_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_runtime_s.lib"
  )

# Import target "openvino::format_reader" for configuration "MinSizeRel"
set_property(TARGET openvino::format_reader APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::format_reader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/format_reader.lib"
  )

# Import target "openvino::ie_samples_utils" for configuration "MinSizeRel"
set_property(TARGET openvino::ie_samples_utils APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::ie_samples_utils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/ie_samples_utils.lib"
  )

# Import target "openvino::interpreter_backend" for configuration "MinSizeRel"
set_property(TARGET openvino::interpreter_backend APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(openvino::interpreter_backend PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/OPENVINO/openvino/bin/intel64/MinSizeRel/openvino_interpreter_backend.lib"
  )

# Import target "openvino::pugixml" for configuration "RelWithDebInfo"
set_property(TARGET openvino::pugixml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::pugixml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/pugixml.lib"
  )

# Import target "openvino::gflags_nothreads_static" for configuration "RelWithDebInfo"
set_property(TARGET openvino::gflags_nothreads_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::gflags_nothreads_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/gflags_nothreads_static.lib"
  )

# Import target "openvino::itt" for configuration "RelWithDebInfo"
set_property(TARGET openvino::itt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::itt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_itt.lib"
  )

# Import target "openvino::util" for configuration "RelWithDebInfo"
set_property(TARGET openvino::util APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::util PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_util.lib"
  )

# Import target "openvino::snippets" for configuration "RelWithDebInfo"
set_property(TARGET openvino::snippets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::snippets PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_snippets.lib"
  )

# Import target "openvino::offline_transformations" for configuration "RelWithDebInfo"
set_property(TARGET openvino::offline_transformations APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::offline_transformations PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_offline_transformations.lib"
  )

# Import target "openvino::reference" for configuration "RelWithDebInfo"
set_property(TARGET openvino::reference APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::reference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_reference.lib"
  )

# Import target "openvino::shape_inference" for configuration "RelWithDebInfo"
set_property(TARGET openvino::shape_inference APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::shape_inference PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_shape_inference.lib"
  )

# Import target "openvino::openvino_runtime_s" for configuration "RelWithDebInfo"
set_property(TARGET openvino::openvino_runtime_s APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::openvino_runtime_s PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_runtime_s.lib"
  )

# Import target "openvino::format_reader" for configuration "RelWithDebInfo"
set_property(TARGET openvino::format_reader APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::format_reader PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/format_reader.lib"
  )

# Import target "openvino::ie_samples_utils" for configuration "RelWithDebInfo"
set_property(TARGET openvino::ie_samples_utils APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::ie_samples_utils PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/ie_samples_utils.lib"
  )

# Import target "openvino::interpreter_backend" for configuration "RelWithDebInfo"
set_property(TARGET openvino::interpreter_backend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(openvino::interpreter_backend PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/OPENVINO/openvino/bin/intel64/RelWithDebInfo/openvino_interpreter_backend.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
