# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# Main GPU unit test sources, always compiled regardless of GPU_RT_TYPE/ENABLE_ONEDNN_FOR_GPU.
set(GPU_UNIT_TESTS_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/bounded_shape_mem_alloc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/deconv_quantize_kernel_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/is_valid_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/memory_realloc_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/optimized_out_execution_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/priorbox_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/skip_gather_at_runtime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/skip_permutes_at_runtime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/skip_redundant_reorder_at_runtime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/skip_scatter_update_at_runtime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/stateful_model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/update_shape_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_execution/zero_copy_output_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fake_alignment/fc_fake_alignment_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/activation_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/batch_to_space_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/broadcast_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/concatenate_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/convolution_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/deconvolution_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/depth_to_space_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/eltwise_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/fully_connected_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/fusion_test_common.hpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/fusion_validity_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/gather_elements_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/gather_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/gather_matmul_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/gather_nd_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/gemm_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/loop_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/lora_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/lrn_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/mvn_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/normalize_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/permute_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/pooling_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/reduce_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/resample_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/rms_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/scatter_elements_update_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/scatter_nd_update_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/scatter_update_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/select_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/softmax_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/space_to_batch_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/space_to_depth_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fusions/strided_slice_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gtest_main_gpu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/canonicalize_fused_shapes_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/convert_and_copy_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/dispatch_data_func_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/execution_config_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/force_implementations_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/format_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/graph_manipulation_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/impls_registry_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/impls_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/jitter_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/kernel_impl_params_relevance_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/layout_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/mem_reset_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/primitive_comparison_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/shape_predictor_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/sycl/sycl_test_context.hpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/test_uqr_distribution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/weights_reorder_factory_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_test_context.hpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/add_onednn_optimization_attributes_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/add_required_reorders_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/basic_memory_dependencies_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/clamp_fp16_output_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/fuse_primitives_with_layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/handle_reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/kernels_cache_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/mark_shape_of_subgraphs_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/mark_state_init_subgraphs_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/post_optimize_weights.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/prepare_buffer_fusing_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/prepare_padding_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/prepare_primitive_fusing_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/prepare_primitive_fusing_through_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/prepare_quantization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/propagate_constants_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/remove_redundant_reorders_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/reorder_inputs_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/reorder_transfer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/select_preferred_formats_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/test_module_fusing_reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/passes/trim_to_outputs_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/activation_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/arg_max_min_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/assign_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/broadcast_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/bucketize_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/concatenation_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/convolution_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/crop_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/ctc_greedy_decoder_seq_len_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/deconvolution_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/depth_to_space_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/detection_output_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/dft_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/eltwise_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/gather_elements_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/gather_nd_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/gather_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/gather_tree_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/grid_sample_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/grn_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/interpolate_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/kv_cache_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/lrn_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/matmul_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/mvn_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/non_max_suppression_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/normalize_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/one_hot_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/pad_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/pooling_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/proposal_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/quantize_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/random_uniform_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/range_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/read_value_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/reduce_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/region_yolo_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/reorg_yolo_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/resample_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/reshape_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/reverse_sequence_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/reverse_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/roi_align_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/roi_pooling_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/roll_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/scatter_nd_update_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/scatter_update_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/select_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/shape_of_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/softmax_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/space_to_depth_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/strided_slice_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/tile_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_infer/transpose_si_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/activation_simple_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/adaptive_avg_pooling_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/adaptive_max_pooling_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/add_reorders_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/arg_max_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/barriers_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/batch_to_space_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/bf16_onednn_ops_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/border_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/broadcast_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/bucketize_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/cache_serialization_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/canonicalization_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/command_queue_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/concatenation_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/condition_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/convolution_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/crop_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/ctc_loss_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/cum_sum_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/custom_gpu_primitive_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/data_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/debug_config_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/deconvolution_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/depth_concatenate_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/depth_to_space_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/detection_output_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/dft_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/dynamic_quantize_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/eltwise_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/embedding_bag_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/empty_tensor_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/experimental_detectron_detection_output_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/experimental_detectron_generate_proposals_single_image_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/experimental_detectron_prior_grid_generator_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/experimental_detectron_roi_feature_extractor_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/experimental_detectron_topk_rois_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/extract_image_patches_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/fully_connected_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gated_mlp_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gather_elements_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gather_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gather_nd_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gather_tree_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/gemm_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/generate_proposals_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/grid_sample_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/group_normalization_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/hash_key_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/istft_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/loop_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/lrn_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/lru_caches_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/matrix_nms_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/memory_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_3gemm_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_3gemm_test_data.h
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_gather_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_gemm_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_mask_gen_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_offload_constant_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_offload_lru_cache_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_offload_primitive_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_offload_property_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_offload_weight_provider_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_router_fused_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/moe_scatter_reduction_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/multiclass_nms_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/multiple_streams_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/mvn_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/non_max_suppression_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/non_zero_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/normalizel2_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/one_hot_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/pa_kv_reorder_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/paged_attention_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/paged_attention_gpu_test.h
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/paged_attention_token_type_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/paged_causal_conv1d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/paged_selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/permute_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/pooling_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/prior_box_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/propagate_constants_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/proposal_cpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/proposal_test_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/quantize_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/random_uniform_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/range_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/reduce_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/region_yolo_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/removing_output_node_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/reorder_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/reorg_yolo_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/resample_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/reshape_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/reverse_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/reverse_sequence_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/rms_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/roi_align_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/roi_align_rotated_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/roi_pooling_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/roll_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/rope_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/scatter_elements_update_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/scatter_nd_update_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/scatter_update_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/sdpa_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/search_sorted_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/segment_max_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/select_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/set_output_memory_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/shape_of_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/shuffle_channels_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/slice_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/slice_scatter_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/softmax_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/space_to_batch_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/space_to_depth_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/sparse_fill_empty_rows_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/spatial_concatenate_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/stft_gpu_benchamrk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/stft_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/streams_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/strided_slice_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/swiglu_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/tensor_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/test_device_mem_usage_estimation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/tile_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/unique_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/variable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/vlsdpa_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/conv_test_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/network_test.h
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/opencl_helper_instance.hpp
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/parallel_mem_streambuf_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/primitive_inst_test_helper.h
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/program_wrapper.h
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/random_gen.h
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/test_data/paged_attention_token_type_test_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/test_data/paged_attention_token_type_test_data.h
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/test_utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/test_utils.h
    ${CMAKE_CURRENT_LIST_DIR}/test_utils/uniform_quantized_real_distribution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/bcast_and_pad_zp_buffers_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/clamp_fp16_output_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_binary_conv_to_conv_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_convolution_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_fc_to_compressed_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_matmul_to_fc_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_pooling_to_reduce_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_stridedslices_to_variadicsplit_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/decompose_one_hot_non_const_values_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/decompose_reduce_for_false_keepdims_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/decompose_reduce_scalar_output_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/disable_fp16_compression_cumsum_sin_gen_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/disable_fp16_compression_rms_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/disable_fp16_compression_sin_gen_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/disable_fp16_compression_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/dynamic_quantize_sharing_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/expand_broadcast_reshape_sdpa_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fc_convert_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fc_per_layer_scaling_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fold_activation_transpose_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fuse_atan2_decomposed_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fuse_moe_router_scale_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fuse_moe_router_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/fuse_moe_shared_expert_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/horizontal_fc_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/increase_precision_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/indirect_kv_cache_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/keep_gqa_kv_scale_precision_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/keep_xattention_threshold_precision_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/kv_cache_compression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/kv_cache_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/lora_horizontal_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/move_fc_reshape_to_weights.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/optimize_subsequent_reshapes_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/preserve_single_selective_ssm_output_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/reduce_fc_dimensions_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/sdpa_opt_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/sdpa_transpose_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/sink_reshape_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/swish_with_clamp_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/transpose_matmul_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/transpose_sdpa_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/transpose_split_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/transpose_vlsdpa_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/unsqueeze_broadcast_reshape_matmul_fusion_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/xattention_kv_cache_transform_test.cpp
)

set(GPU_UNIT_TESTS_TRANSFORMATIONS_SRCS
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/bcast_and_pad_zp_buffers.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/bcast_and_pad_zp_buffers.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/binary_conv_to_conv.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/binary_conv_to_conv.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/clamp_fp16_output.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/clamp_fp16_output.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/compressed_weights_pattern.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_convolution.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_convolution.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_fc_to_compressed.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_matmul_to_fc.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_pooling_to_reduce.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_pooling_to_reduce.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_shapeof.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_shapeof.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_stridedslices_to_variadicsplit.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/convert_stridedslices_to_variadicsplit.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/decompose_one_hot_non_const_values.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/decompose_one_hot_non_const_values.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_for_false_keepdims.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_for_false_keepdims.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_scalar_output.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/decompose_reduce_scalar_output.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_cumsum_sin_gen.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_cumsum_sin_gen.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_direct_multiply_sin_cos.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_direct_multiply_sin_cos.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_gated_residual.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_gated_residual.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_rms.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_rms.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_sin_gen.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/disable_fp16_comp_sin_gen.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/dynamic_quantize_fully_connected.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/dynamic_quantize_fully_connected.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/einsum_decomposition.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/einsum_decomposition.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/expand_broadcast_reshape_sdpa_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/expand_broadcast_reshape_sdpa_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fc_convert_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fc_convert_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fc_horizontal_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fc_per_layer_scaling.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fc_per_layer_scaling.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fold_activation_transpose.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fold_activation_transpose.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_atan2_decomposed.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_atan2_decomposed.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_gated_mlp.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_gated_mlp.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_moe_router.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_moe_router.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_moe_router_scale.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_moe_router_scale.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_moe_shared_expert.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/fuse_moe_shared_expert.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/increase_position_ids_precision.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/increase_rms_input_precision.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/increase_rms_input_precision.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/indirect_kv_cache.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/keep_gqa_kv_scale_precision.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/keep_gqa_kv_scale_precision.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/keep_moe_3gemm_const_precision.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/keep_moe_3gemm_const_precision.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/keep_xattention_threshold_precision.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/keep_xattention_threshold_precision.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/kv_cache_compression.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/kv_cache_compression.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/kv_cache_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/kv_cache_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/lora_horizontal_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/lora_horizontal_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/lora_subgraph_horizontal_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/lora_subgraph_horizontal_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/normalize_l2_decomposition.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/normalize_l2_decomposition.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/optimize_subsequent_reshapes.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/optimize_subsequent_reshapes.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/preserve_single_selective_ssm_output.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/preserve_single_selective_ssm_output.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/print_model_statistics.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/print_model_statistics.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/reduce_fc_dimensions.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/reduce_fc_dimensions.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/sdpa_transpose_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/sdpa_transpose_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/sink_reshape.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/sink_reshape.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/swiglu_fusion_with_clamp.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/swiglu_fusion_with_clamp.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/transpose_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_matmul_fusion.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/unsqueeze_broadcast_reshape_matmul_fusion.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/utils.hpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/atan2.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/convolution.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/fully_connected.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/fully_connected_compressed.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/gated_mlp.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/gemm.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/indirect_gemm.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/indirect_sdpa.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/kv_cache.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/lora_subgraph_fused.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/moe_router_fused.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/placeholder.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/read_value.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/sdpa.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/transformations/op/swiglu_with_clamp.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/variable_state.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/multi_tensor_variable_state.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/remote_context.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/remote_tensor.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/usm_host_tensor.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/common_utils.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/simple_math.cpp
    ${CMAKE_HOME_DIRECTORY}/src/plugins/intel_gpu/src/plugin/ops/moe_offload_constant.cpp
)
list(APPEND GPU_UNIT_TESTS_SRCS ${GPU_UNIT_TESTS_TRANSFORMATIONS_SRCS})

# oneDNN-specific tests - only compiled when oneDNN is enabled for the GPU plugin.
set(GPU_UNIT_TESTS_ONEDNN_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/onednn/profiling_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/onednn/utils_test.cpp
)
if(ENABLE_ONEDNN_FOR_GPU)
    list(APPEND GPU_UNIT_TESTS_SRCS ${GPU_UNIT_TESTS_ONEDNN_SRCS})
endif()

# Tests with a dependency on the OpenCL runtime - excluded from the build with a different runtime.
set(GPU_UNIT_TESTS_OCL_RT_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/device_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/engine_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/events_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/network_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/usm_memory_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/convert_color_gpu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/cl_mem_input_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/test_cases/mem_perf_test.cpp
)
if(GPU_RT_TYPE STREQUAL "OCL")
    list(APPEND GPU_UNIT_TESTS_SRCS ${GPU_UNIT_TESTS_OCL_RT_SRCS})
endif()

# Tests with a dependency on the Level Zero runtime.
set(GPU_UNIT_TESTS_ZE_RT_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_device_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_engine_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_events_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_image_memory_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_resource_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/ze/ze_usm_memory_test.cpp
)
if(GPU_RT_TYPE STREQUAL "ZE")
    list(APPEND GPU_UNIT_TESTS_SRCS ${GPU_UNIT_TESTS_ZE_RT_SRCS})
endif()

# Tests with a dependency on the SYCL runtime.
set(GPU_UNIT_TESTS_SYCL_RT_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/sycl/sycl_device_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/sycl/sycl_engine_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/sycl/sycl_events_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/sycl/sycl_kernel_builder_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/module_tests/sycl/sycl_usm_memory_test.cpp
)
if(GPU_RT_TYPE STREQUAL "SYCL")
    list(APPEND GPU_UNIT_TESTS_SRCS ${GPU_UNIT_TESTS_SYCL_RT_SRCS})
endif()
