[tool.black]
line-length = 160
include = '\.pyi?$'

[tool.pyright]
exclude = [
    "src/openvino/utils/data_helpers/data_dispatcher.py",
    "src/openvino/utils/types.py",
    "src/openvino/**/ops.py",
    "src/openvino/utils/decorators.py",
    "src/openvino/frontend/frontend.py",
    "src/openvino/_ov_api.py",
    "src/openvino/_op_base.py",
    "src/openvino/utils/node_factory.py",
    "src/openvino/frontend/tensorflow",
    "src/openvino/frontend/pytorch",
    "src/openvino/frontend/jax",
]
reportInvalidTypeForm = false
reportMissingModuleSource = false
reportFunctionMemberAccess = false
reportAttributeAccessIssue = false
reportMissingImports = false
reportIncompatibleMethodOverride = false
