[project]
name = "openvino"
dynamic = ["version", "entry-points", "scripts"]
description = "OpenVINO(TM) Runtime"
readme = {file = "README.md", content-type="text/markdown"}
license = {text = "OSI Approved :: Apache Software License"}
authors = [
    { name = "OpenVINO Developers", email = "openvino@intel.com" },
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.9"

dependencies = [
    "numpy>=1.16.6,<2.2.0",
    "openvino-telemetry>=2023.2.1",
    "packaging"
]

[build-system]
requires = ["setuptools>=70,<=75", "wheel<=0.45.1", "cmake<=3.31.6"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
license-files = [
    "readme.txt", 
    "../../../LICENSE",
    "../../../licensing/runtime-third-party-programs.txt",
    "../../../licensing/onetbb_third-party-programs.txt",
    "../../../licensing/onednn_third-party-programs.txt",
]

[tool.black]
line-length = 160
include = '\.pyi?$'

[tool.pyright]
exclude = [
    "src/openvino/utils/data_helpers/data_dispatcher.py",
    "src/openvino/utils/types.py",
    "src/openvino/**/ops.py",
    "src/openvino/utils/decorators.py",
    "src/openvino/frontend/frontend.py",
    "src/openvino/_ov_api.py",
    "src/openvino/_op_base.py",
    "src/openvino/utils/node_factory.py",
    "src/openvino/frontend/tensorflow",
    "src/openvino/frontend/pytorch",
    "src/openvino/frontend/jax",
]
reportInvalidTypeForm = false
reportMissingModuleSource = false
reportFunctionMemberAccess = false
reportAttributeAccessIssue = false
reportMissingImports = false
reportIncompatibleMethodOverride = false
