# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# NOTE: .pyi stub files are intentionally not tracked here - they are auto-generated
# by a scheduled CI workflow and are not required to gate these dependency lists.
set(OPENVINO_PYTHON_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/_offline_transformations/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/_op_base.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/_ov_api.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/exceptions.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/experimental/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/frontend.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/jax/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/jax/jaxpr_decoder.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/jax/passes.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/jax/utils.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/onnx/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/paddle/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/compressed_tensors.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/fx_decoder.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/gptq.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/inlined_extension.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/module_extension.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/ov_custom_ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/patch_functions.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/patch_model.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/quantized.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/backend.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/backend_utils.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/compile.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/decompositions.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/execute.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/export_decompositions.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/op_support.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/torchdynamo/partition.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/ts_decoder.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/pytorch/utils.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/tensorflow/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/tensorflow/graph_iterator.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/tensorflow/node_decoder.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/frontend/tensorflow/utils.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/helpers/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/helpers/packing.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/op/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/op/util/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset1/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset1/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset10/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset10/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset11/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset11/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset12/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset12/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset13/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset13/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset14/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset14/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset15/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset15/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset16/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset16/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset17/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset17/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset2/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset2/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset3/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset3/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset4/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset4/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset5/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset5/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset6/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset6/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset7/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset7/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset8/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset8/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset9/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/opset9/ops.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/package_utils.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/passes/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/passes/graph_rewrite.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/passes/manager.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/preprocess/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/preprocess/torchvision/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/preprocess/torchvision/preprocess_converter.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/preprocess/torchvision/torchvision_preprocessing.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/_properties.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/device/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/hint/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/intel_auto/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/intel_cpu/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/intel_gpu/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/intel_gpu/hint/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/intel_npu/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/log/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/properties/streams/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/test_utils/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/test_utils/test_api.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/torch/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/broadcasting.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/data_helpers/__init__.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/data_helpers/data_dispatcher.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/data_helpers/wrappers.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/decorators.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/input_validation.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/node_factory.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/postponed_constant.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/reduction.py
    ${CMAKE_CURRENT_LIST_DIR}/src/openvino/utils/types.py
)

set(OpenVINO_Telemetry_SOURCE_DIR "${OpenVINO_SOURCE_DIR}/thirdparty/telemetry")
set(telemetry_files
    ${OpenVINO_Telemetry_SOURCE_DIR}/LICENSE
    ${OpenVINO_Telemetry_SOURCE_DIR}/README.md
    ${OpenVINO_Telemetry_SOURCE_DIR}/requirements.txt
    ${OpenVINO_Telemetry_SOURCE_DIR}/setup.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/__init__.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/backend/__init__.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/backend/backend.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/backend/backend_ga.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/backend/backend_ga4.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/backend/backend_ga4_test.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/backend/backend_ga_test.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/main.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/main_test.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/opt_in_out.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/__init__.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/cid.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/colored_print.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/input_with_timeout.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/input_with_timeout_test.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/message.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/opt_in_checker.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/opt_in_checker_test.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/params.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/sender.py
    ${OpenVINO_Telemetry_SOURCE_DIR}/src/utils/sender_test.py
)
