import { Shape, Tensor, IShape, ITensor } from 'openvinojs-common';
import { OpenvinoModule } from './types.js';
import type { OriginalShape, OriginalTensor, OriginalShapeWrapper, OriginalTensorWrapper } from './ov-module.js';
export declare function isNodeEnv(): boolean;
export declare function getFileDataAsArray(path: string): Promise<Uint8Array>;
export declare function uploadFile(ov: OpenvinoModule, filename: string, data: Uint8Array): void;
export declare function parseOriginalShape(ov: OpenvinoModule, originalShape: OriginalShape): Shape;
export declare function convertShape(ov: OpenvinoModule, shape: IShape): OriginalShapeWrapper;
export declare function parseOriginalTensor(ov: OpenvinoModule, originalTensor: OriginalTensor): Tensor;
export declare function convertTensor(ov: OpenvinoModule, tensor: ITensor): OriginalTensorWrapper;
