# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(LIBRARY_SRC
    ${CMAKE_CURRENT_LIST_DIR}/any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/atomic_guard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/attribute_adapter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/attribute_visitor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/axis_set.cpp
    ${CMAKE_CURRENT_LIST_DIR}/axis_vector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bound_evaluate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bound_evaluate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/constant_fold_utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/coordinate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/coordinate_diff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dimension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/evaluator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/except.cpp
    ${CMAKE_CURRENT_LIST_DIR}/extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/interval.cpp
    ${CMAKE_CURRENT_LIST_DIR}/itt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/layout_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/log_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/memory_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/node_input.cpp
    ${CMAKE_CURRENT_LIST_DIR}/node_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/node_vector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/partial_shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/precomp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/rt_info.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime_attribute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_node_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/so_extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/strides.cpp
    ${CMAKE_CURRENT_LIST_DIR}/symbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tensor_name_util.hpp
    ${CMAKE_CURRENT_LIST_DIR}/tensor_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/validation_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/version.cpp
    ${CMAKE_CURRENT_LIST_DIR}/weight_sharing_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/descriptor/input.cpp
    ${CMAKE_CURRENT_LIST_DIR}/descriptor/output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/descriptor/shared_tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/descriptor/tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/abs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/acos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/acosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adaptive_avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adaptive_max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/asin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/asinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/atan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/atanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/binary_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_left_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_right_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bitwise_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ceiling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/clamp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convert_promote_types.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_greedy_decoder_seq_len.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/deformable_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/deformable_psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/divide.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/elu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embedding_segments_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_offsets.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_offsets_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_packed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/embeddingbag_packedsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/erf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/erfinv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/exp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_roi_feature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/experimental_detectron_topkrois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/extractimagepatches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fake_convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fake_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/floor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/floor_mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/greater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/greater_eq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/group_conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/group_query_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/grouped_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gru_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gru_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hard_sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hsigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hswish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/i420_to_bgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/i420_to_rgb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/idft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/inverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/irdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/is_finite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/is_inf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/is_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/less.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/less_eq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/logical_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lstm_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/maximum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/minimum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/moe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multiply.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/negative.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/non_zero.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/normalize_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/not_equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/nv12_to_bgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/nv12_to_rgb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/pa_kv_reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/paged_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/paged_causal_conv1d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/parameter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/power.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/prelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/prior_box_clustered.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/read_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_l1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_logical_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_logical_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_mean.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_min.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_prod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/result.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rms_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rnn_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rnn_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roi_align_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/round.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scaled_dot_product_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_elements_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/search_sorted.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/selu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/shape_of.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softplus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softsign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sqrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/squared_difference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/squeeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/string_tensor_pack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/string_tensor_unpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/subtract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/swish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/topk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/type_relaxed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unsqueeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/variadic_split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/activation_functions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/arithmetic_reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/arithmetic_reductions_keep_dims.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/assign_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/attr_types.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/avg_pool_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/binary_elementwise_arithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/binary_elementwise_bitwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/binary_elementwise_comparison.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/binary_elementwise_logical.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/broadcast_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/convert_color_i420_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/convert_color_nv12_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/deformable_convolution_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/detection_output_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/elementwise_args.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/embeddingbag_offsets_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/embeddingbag_packed_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/fft_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/framework_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/gather_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/gather_nd_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/index_reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/interpolate_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/logical_reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/logical_reduction_keep_dims.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/max_pool_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/model_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/multi_subgraph_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/multiclass_nms_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/node_util.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/one_hot_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/op_types.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/pad_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/precision_sensitive_attribute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/read_value_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/recurrent_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/reduction_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/rnn_cell_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/roi_align_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/scatter_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/scatter_elements_update_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/scatter_nd_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/slice_plan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/squeeze_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/sub_graph_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/symbolic_info.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/topk_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/unary_elementwise_arithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/variable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/variable_extension.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/variable_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/util/weightless_caching_attributes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/opsets/opset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/constant_folding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/convert_fp32_to_fp16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/graph_rewrite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/low_latency.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/make_stateful.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/node_registry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/pa_kv_reorder_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/pass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/pass_config.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/perf_counters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/perf_counters.hpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/sdpa_to_paged_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/sdpa_to_vlsdpa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/serialize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/stateful_to_stateless.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/validate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pass/visualize_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/matcher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/multi_matcher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/any_of.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/any_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/block.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/label.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/optional.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/pattern.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/predicate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/true.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pattern/op/wrap_type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/color_utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/color_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/function_guard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/pre_post_process.cpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/preprocess_impls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/preprocess_impls.hpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/preprocess_steps_impl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/preprocess/preprocess_steps_impl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/aligned_buffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/allocator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/compute_hash.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/itensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/lazy_buffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/shared_buffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/string_aligned_buffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/runtime/tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/bfloat16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/element_type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/float16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/float4_e2m1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/float8_e4m3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/float8_e5m2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/float8_e8m0.cpp
    ${CMAKE_CURRENT_LIST_DIR}/type/nf4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xml_util/constant_writer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xml_util/xml_serialize_util.cpp
)
