# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(GPU_FUNCTIONAL_TEST_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/behavior/compatibility_string.cpp
    ${CMAKE_CURRENT_LIST_DIR}/behavior/infer_request.cpp
    ${CMAKE_CURRENT_LIST_DIR}/behavior/inference_precision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/behavior/memory_dyn_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/behavior/model_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/behavior/properties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/concurrency/gpu_concurrency_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/concurrency/gpu_reservation_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/custom_op/custom_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/custom_op/custom_op_dynamic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_tests/gpu_dyn_batch_shape_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_tests/gpu_dyn_huge_input_range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_tests/gpu_dyn_output_aliasing_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_tests/gpu_dyn_output_deep_chain_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_tests/gpu_dyn_output_multiop_chain_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/dx11_nthandle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/dx11_remote_ctx_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/dx12_nthandle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/dx12_remote_run.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/helpers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/ocl_remote_tensor_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/va_remote_tensor_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/remote_tensor_tests/ze_remote_tensor_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_executable_network/exec_graph_info.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_executable_network/exec_net_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_executable_network/get_metric.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_executable_network/properties_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/callback.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/cancellation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/infer_consistency.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/infer_request_dynamic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/io_tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/iteration_chaining.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/multithreading.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/perf_counters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_infer_request/wait.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/caching_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/core_integration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/core_threading_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/life_time.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/properties_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/remote.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/behavior/ov_plugin/version.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/core_config.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/execution_graph_info/nms_transformation_for_last_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/execution_graph_info/normalize_l2_decomposition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/execution_graph_info/remove_parameter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/add_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/assign_and_read_value_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/batch_to_space_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/clamp_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/concat_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/concat_with_child_and_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/concat_with_different_precision_on_children.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/concat_with_intermediate_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/concat_with_neighbors_graph_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/concat_with_split_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/convolution_backprop_data_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/convolution_qdq_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/convolution_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/depth_to_space_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/elementwise_branch_selection_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/eliminate_fake_quantize_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fq_and_avg_pool_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fq_and_max_pool_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fq_and_two_output_branches_with_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fq_precision_selection_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fq_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fq_with_dq_not_optimal_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fully_connected_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fuse_convert_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fuse_dequantize_to_fq_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fuse_fq_and_scale_shift_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fuse_multiply_to_fq_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/fuse_subtract_to_fq_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/gather_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/group_convolution_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/groupconvolution_qdq_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/interpolate_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/mat_mul_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/mat_mul_with_constant_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/mat_mul_with_optimized_constant_fq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/move_fake_quantize_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/multiply_to_group_convolution_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/multiply_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/multiply_with_one_parent_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/mvn_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/normalize_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/output_layers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/pad_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/prelu_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/pull_reshape_through_dequantization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/recurrent_cell_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/reduce_max_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/reduce_mean_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/reduce_min_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/reduce_sum_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/relu_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/reshape_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/shuffle_channels_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/slice_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/space_to_batch_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/split_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/squeeze_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/strided_slice_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/subtract_multiply_to_multiply_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/transpose_after_matmul_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/transpose_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/unsqueeze_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/low_precision_transformations/variadic_split_transformation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/preprocess/yuv_to_grey_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/set_device_name.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/activation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/adaptive_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/comparison.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/conversion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/conversion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/convert_color_i420.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/convert_color_nv12.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/ctc_greedy_decoder_seq_len.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/deformable_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/deformable_psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/embedding_bag_offsets_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/embedding_bag_packed_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/embedding_segments_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/experimental_detectron_generate_proposals_single_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/experimental_detectron_roifeatureextractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/experimental_detectron_topk_rois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/extract_image_patches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/fake_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/group_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/group_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/grouped_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/gru_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/gru_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/is_inf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/logical.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/lstm_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/mat_mul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/memory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/minimum_maximum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/normalize_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/paged_attention_token_type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/power.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/prior_box_clustered.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/rdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/reduce_ops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/rnn_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/rnn_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/roi_align_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/scatter_elements_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/search_sorted.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/shape_of.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/squeeze_unsqueeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/topk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/single_layer_tests/variadic_split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/skip_tests_config.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/broadcast_eltwise_eliminated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/constant_result.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/conv1x1_weight_compressed_to_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/gather_weights_decompression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/get_output_before_activation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/group_normalization_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/lora_pattern.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/matmul_conversion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/matmul_squeeze_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/matmul_transpose_to_reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/multiply_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/perm_conv_perm_concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/preprocess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/quantized_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/quantized_group_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/reduce_eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/reshape_permute_conv_permute_reshape_act.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/reshape_squeeze_reshape_relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/rotary_pos_emb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/scale_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/shared_constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/shared_matmul_gather_weights_decompression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/shared_matmul_weights_decompression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/split_conv_concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/stateful_model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/stridedslice_eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shared_tests_instances/subgraph_tests/transpose_matmul_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/adaptive_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/ctc_greedy_decoder_seq_len.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/group_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/groupconvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/lstmcell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/normalize_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/reduce.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/scaled_dot_product_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/sdpa_transpose_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/shapeof.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/top_k.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/dynamic/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/fake_convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/gather_elements_padding_input.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/gather_indices_input.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/group_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/prelu_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/reduce.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/single_layer_tests/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/condition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/activations_scaling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/broadcast_eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/concat_in_place_dynamic_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/convert_bf16_fp32_fp16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_fc_horizontal_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_model_static_split_layer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_conv_reshape_fully_connected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_gen_impl_key.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_reduce_deconvolution_concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_shape_of_activation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_shape_of_reduce_reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_with_empty_tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_smoke_test_with_static_conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/dynamic_unfusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/eltwise_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/eltwise_merge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/hybrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/kv_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/kv_cache_sdpa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/matmul_weights_decompression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/moe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/qdq_stripping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/read_value_assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/rms_norm_decomposition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/split_reshape_eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/swiglu_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/dynamic/transpose_matmul_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/matmul_sum_fusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/mvn_layernorm_byxf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/prevent_f32_dequantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/sdpa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/serialize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/shared_constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/transpose_split_vlsdpa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subgraph_tests/vlsdpa.cpp
)

# Only compiled when ENABLE_MLIR_FOR_GPU is ON.
set(GPU_FUNCTIONAL_TEST_MLIR_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/binary_eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/matmul_rms_norm_concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/mlir_test_env.hpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/reduction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/rms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/sdpa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mlir_op/unary_eltwise.cpp
)
