# Copyright (C) 2018-2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

nodes_to_compare = ("ScaledDotProductAttention", "PagedAttentionExtension", "Parameter", "ReadValue", "Assign")

ref_diff_map = {
	"hf-internal-testing/tiny-random-LlamaForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-CohereForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-GPTJForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-GPTNeoForCausalLM" : {
		"PagedAttentionExtension" : 4,
		"ScaledDotProductAttention" : -4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"Assign" : -8,
	},
	"hf-internal-testing/tiny-random-GPTNeoXForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-MistralForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-CodeGenForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"hf-internal-testing/Mixtral-tiny" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-GPTBigCodeForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 13,
		"ReadValue" : -5,
		"Assign" : -5,
	},
	"hf-internal-testing/tiny-random-Starcoder2ForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-BloomForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 14,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-gpt2" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-BlenderbotForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 8,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-PegasusForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 8,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-PhiForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-MptForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 14,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-StableLmForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-PersimmonForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-FalconForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"hf-tiny-model-private/tiny-random-OPTForCausalLM" : {
		"PagedAttentionExtension" : 5,
		"ScaledDotProductAttention" : -5,
		"Parameter" : 14,
		"ReadValue" : -10,
		"Assign" : -10,
	},
	"katuni4ka/tiny-random-xverse" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-baichuan2-13b" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-qwen" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-aquilachat" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-aquila2" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-qwen1.5-moe" : {
		"PagedAttentionExtension" : 4,
		"ScaledDotProductAttention" : -4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"Assign" : -8,
	},
	"katuni4ka/tiny-random-codegen2" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-olmo-hf" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-baichuan2" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-jais" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-internlm" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-internlm2" : {
		"PagedAttentionExtension" : 4,
		"ScaledDotProductAttention" : -4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"Assign" : -8,
	},
    "katuni4ka/tiny-random-minicpm" : {
        "ReadValue" : -8,
        "ScaledDotProductAttention" : -4,
        "Assign" : -8,
        "PagedAttentionExtension" : 4,
        "Parameter" : 11,
    },
	"katuni4ka/tiny-random-falcon-40b" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-dbrx" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"fxmarty/tiny-random-GemmaForCausalLM" : {
		"PagedAttentionExtension" : 1,
		"ScaledDotProductAttention" : -1,
		"Parameter" : 5,
		"ReadValue" : -2,
		"Assign" : -2,
	},
	"fxmarty/tiny-dummy-qwen2" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"fxmarty/really-tiny-falcon-testing" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"Xenova/tiny-random-Phi3ForCausalLM" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"facebook/opt-125m" : {
		"PagedAttentionExtension" : 12,
		"ScaledDotProductAttention" : -12,
		"Parameter" : 28,
		"ReadValue" : -24,
		"Assign" : -24,
	},
	"facebook/opt-350m" : {
		"PagedAttentionExtension" : 24,
		"ScaledDotProductAttention" : -24,
		"Parameter" : 52,
		"ReadValue" : -48,
		"Assign" : -48,
	},
	"katuni4ka/tiny-random-chatglm2" : {
		"PagedAttentionExtension" : 2,
		"ScaledDotProductAttention" : -2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-glm4" : {
		"PagedAttentionExtension" : 6,
		"ScaledDotProductAttention" : -6,
		"Parameter" : 15,
		"ReadValue" : -12,
		"Assign" : -12,
	},
}

ref_diff_map_cache_eviction = {
	"hf-internal-testing/tiny-random-LlamaForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-CohereForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-GPTJForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 17,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-GPTNeoForCausalLM" : {
		"ScaledDotProductAttention" : -4,
		"ReadValue" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 14,
		"Assign" : -8,
	},
	"hf-internal-testing/tiny-random-GPTNeoXForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 17,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-MistralForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-CodeGenForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 17,
		"Assign" : -10,
	},
	"hf-internal-testing/Mixtral-tiny" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-GPTBigCodeForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -5,
		"PagedAttentionExtension" : 5,
		"Parameter" : 17,
		"Assign" : -5,
	},
	"hf-internal-testing/tiny-random-Starcoder2ForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-BloomForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 18,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-gpt2" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 17,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-BlenderbotForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 9,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-PegasusForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 9,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-PhiForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-MptForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 18,
		"Assign" : -10,
	},
	"hf-internal-testing/tiny-random-StableLmForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-PersimmonForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-internal-testing/tiny-random-FalconForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"hf-tiny-model-private/tiny-random-OPTForCausalLM" : {
		"ScaledDotProductAttention" : -5,
		"ReadValue" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 18,
		"Assign" : -10,
	},
	"katuni4ka/tiny-random-xverse" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-baichuan2-13b" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-qwen" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-aquilachat" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-aquila2" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-qwen1.5-moe" : {
		"ScaledDotProductAttention" : -4,
		"ReadValue" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 14,
		"Assign" : -8,
	},
	"katuni4ka/tiny-random-codegen2" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-olmo-hf" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-baichuan2" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-jais" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-internlm" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-internlm2" : {
		"ScaledDotProductAttention" : -4,
		"ReadValue" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 14,
		"Assign" : -8,
	},
    "katuni4ka/tiny-random-minicpm" : {
        "ScaledDotProductAttention" : -4,
        "Parameter" : 14,
        "PagedAttentionExtension" : 4,
        "ReadValue" : -8,
        "Assign" : -8,
    },
	"katuni4ka/tiny-random-falcon-40b" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-dbrx" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"fxmarty/tiny-random-GemmaForCausalLM" : {
		"ScaledDotProductAttention" : -1,
		"ReadValue" : -2,
		"PagedAttentionExtension" : 1,
		"Parameter" : 5,
		"Assign" : -2,
	},
	"fxmarty/tiny-dummy-qwen2" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"fxmarty/really-tiny-falcon-testing" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"Xenova/tiny-random-Phi3ForCausalLM" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"facebook/opt-125m" : {
		"ScaledDotProductAttention" : -12,
		"ReadValue" : -24,
		"PagedAttentionExtension" : 12,
		"Parameter" : 39,
		"Assign" : -24,
	},
	"facebook/opt-350m" : {
		"ScaledDotProductAttention" : -24,
		"ReadValue" : -48,
		"PagedAttentionExtension" : 24,
		"Parameter" : 75,
		"Assign" : -48,
	},
	"katuni4ka/tiny-random-chatglm2" : {
		"ScaledDotProductAttention" : -2,
		"ReadValue" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"Assign" : -4,
	},
	"katuni4ka/tiny-random-glm4" : {
		"ScaledDotProductAttention" : -6,
		"ReadValue" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 20,
		"Assign" : -12,
	},
}
