# Copyright (C) 2018-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

nodes_to_compare = ("ScaledDotProductAttention", "PagedAttentionExtension", "Parameter", "ReadValue", "Assign")

ref_diff_map = {
	"optimum-intel-internal-testing/opt-125m" : {
		"Assign" : -24,
		"PagedAttentionExtension" : 12,
		"Parameter" : 27,
		"ReadValue" : -24,
		"ScaledDotProductAttention" : -12,
	},
	"optimum-intel-internal-testing/really-tiny-falcon-testing" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-dummy-qwen2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-mixtral" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-BlenderbotModel" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-BloomModel" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 14,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-CodeGenForCausalLM" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-CohereForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},

	"optimum-intel-internal-testing/tiny-random-GPTJModel" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-GPTNeoModel" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-GPTNeoXForCausalLM" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-GemmaForCausalLM" : {
		"Assign" : -2,
		"PagedAttentionExtension" : 1,
		"Parameter" : 5,
		"ReadValue" : -2,
		"ScaledDotProductAttention" : -1,
	},
	"optimum-intel-internal-testing/tiny-random-LlamaForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-MptForCausalLM" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 14,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-OPTModel" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-PersimmonForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-Phi3ForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-PhiForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-StableLmForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-Starcoder2ForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-aquila2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-aquilachat" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-baichuan2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-chatglm" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-chatglm4" : {
		"Assign" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 15,
		"ReadValue" : -12,
		"ScaledDotProductAttention" : -6,
	},
	"optimum-intel-internal-testing/tiny-random-codegen2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-dbrx" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-decilm" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-exaone" : {
		"Assign" : -16,
		"PagedAttentionExtension" : 8,
		"Parameter" : 19,
		"ReadValue" : -16,
		"ScaledDotProductAttention" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-falcon-40b" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-gemma2" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-glm-edge" : {
		"Assign" : -56,
		"PagedAttentionExtension" : 28,
		"Parameter" : 59,
		"ReadValue" : -56,
		"ScaledDotProductAttention" : -28,
	},
	"optimum-intel-internal-testing/tiny-random-gpt2" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 13,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-granite" : {
		"Assign" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 15,
		"ReadValue" : -12,
		"ScaledDotProductAttention" : -6,
	},
	"optimum-intel-internal-testing/tiny-random-granite-moe" : {
		"Assign" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 15,
		"ReadValue" : -12,
		"ScaledDotProductAttention" : -6,
	},
	"optimum-intel-internal-testing/tiny-random-internlm" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-jais" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava-next" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava-next-mistral" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava-next-video" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-maira2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-minicpmv-2_6" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-mistral" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-mistral-nemo" : {
		"Assign" : -16,
		"PagedAttentionExtension" : 8,
		"Parameter" : 19,
		"ReadValue" : -16,
		"ScaledDotProductAttention" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-olmo-hf" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-pegasus" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-qwen1.5-moe" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-qwen2vl" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-xverse" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/opt-125m-gptq-4bit" : {
		"ScaledDotProductAttention" : -12,
		"PagedAttentionExtension" : 12,
		"Parameter" : 27,
		"ReadValue" : -24,
		"Assign" : -24,
	},
	"optimum-intel-internal-testing/tiny-marian-en-de" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 8,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-mixtral-AWQ-4bit" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-GPTBigCodeModel" : {
		"ScaledDotProductAttention" : -5,
		"PagedAttentionExtension" : 5,
		"Parameter" : 13,
		"ReadValue" : -5,
		"Assign" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-baichuan2-13b" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-deepseek-v3" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-internlm2" : {
		"ScaledDotProductAttention" : -4,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"Assign" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-internvl2" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-minicpm" : {
		"ScaledDotProductAttention" : -4,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"Assign" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-minicpm3" : {
		"ScaledDotProductAttention" : -6,
		"PagedAttentionExtension" : 6,
		"Parameter" : 15,
		"ReadValue" : -12,
		"Assign" : -12,
	},
	"optimum-intel-internal-testing/tiny-random-nanollava" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-phi-4-multimodal" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-phi3-vision" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-qwen" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 7,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-snowflake" : {
		"ScaledDotProductAttention" : -4,
		"PagedAttentionExtension" : 4,
		"Parameter" : 11,
		"ReadValue" : -8,
		"Assign" : -8,
	},

}

ref_diff_map_optimizations = {
	"optimum-intel-internal-testing/opt-125m" : {
		"Assign" : -24,
		"PagedAttentionExtension" : 12,
		"Parameter" : 78,
		"ReadValue" : -24,
		"ScaledDotProductAttention" : -12,
	},
	"optimum-intel-internal-testing/really-tiny-falcon-testing" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-dummy-qwen2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-mixtral" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-BlenderbotModel" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 19,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-BloomModel" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 37,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-CodeGenForCausalLM" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 36,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-CohereForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},

	"optimum-intel-internal-testing/tiny-random-GPTJModel" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 36,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-GPTNeoModel" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-GPTNeoXForCausalLM" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 36,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-GemmaForCausalLM" : {
		"Assign" : -2,
		"PagedAttentionExtension" : 1,
		"Parameter" : 12,
		"ReadValue" : -2,
		"ScaledDotProductAttention" : -1,
	},
	"optimum-intel-internal-testing/tiny-random-LlamaForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-MptForCausalLM" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 37,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-OPTModel" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 36,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-PersimmonForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-Phi3ForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-PhiForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-StableLmForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-Starcoder2ForCausalLM" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-aquila2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-aquilachat" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-baichuan2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-chatglm" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-chatglm4" : {
		"Assign" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 42,
		"ReadValue" : -12,
		"ScaledDotProductAttention" : -6,
	},
	"optimum-intel-internal-testing/tiny-random-codegen2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-dbrx" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-decilm" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-exaone" : {
		"Assign" : -16,
		"PagedAttentionExtension" : 8,
		"Parameter" : 54,
		"ReadValue" : -16,
		"ScaledDotProductAttention" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-falcon-40b" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-gemma2" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-glm-edge" : {
		"Assign" : -56,
		"PagedAttentionExtension" : 28,
		"Parameter" : 174,
		"ReadValue" : -56,
		"ScaledDotProductAttention" : -28,
	},
	"optimum-intel-internal-testing/tiny-random-gpt2" : {
		"Assign" : -10,
		"PagedAttentionExtension" : 5,
		"Parameter" : 36,
		"ReadValue" : -10,
		"ScaledDotProductAttention" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-granite" : {
		"Assign" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 42,
		"ReadValue" : -12,
		"ScaledDotProductAttention" : -6,
	},
	"optimum-intel-internal-testing/tiny-random-granite-moe" : {
		"Assign" : -12,
		"PagedAttentionExtension" : 6,
		"Parameter" : 42,
		"ReadValue" : -12,
		"ScaledDotProductAttention" : -6,
	},
	"optimum-intel-internal-testing/tiny-random-internlm" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-jais" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava-next" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava-next-mistral" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-llava-next-video" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-maira2" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-minicpmv-2_6" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-mistral" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-mistral-nemo" : {
		"Assign" : -16,
		"PagedAttentionExtension" : 8,
		"Parameter" : 54,
		"ReadValue" : -16,
		"ScaledDotProductAttention" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-olmo-hf" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-pegasus" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 19,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-qwen1.5-moe" : {
		"Assign" : -8,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"ScaledDotProductAttention" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-qwen2vl" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/tiny-random-xverse" : {
		"Assign" : -4,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"ScaledDotProductAttention" : -2,
	},
	"optimum-intel-internal-testing/opt-125m-gptq-4bit" : {
		"ScaledDotProductAttention" : -12,
		"PagedAttentionExtension" : 12,
		"Parameter" : 78,
		"ReadValue" : -24,
		"Assign" : -24,
	},
	"optimum-intel-internal-testing/tiny-marian-en-de" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 19,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-mixtral-AWQ-4bit" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-GPTBigCodeModel" : {
		"ScaledDotProductAttention" : -5,
		"PagedAttentionExtension" : 5,
		"Parameter" : 36,
		"ReadValue" : -5,
		"Assign" : -5,
	},
	"optimum-intel-internal-testing/tiny-random-baichuan2-13b" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-deepseek-v3" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-internlm2" : {
		"ScaledDotProductAttention" : -4,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"Assign" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-internvl2" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-minicpm" : {
		"ScaledDotProductAttention" : -4,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"Assign" : -8,
	},
	"optimum-intel-internal-testing/tiny-random-minicpm3" : {
		"ScaledDotProductAttention" : -6,
		"PagedAttentionExtension" : 6,
		"Parameter" : 42,
		"ReadValue" : -12,
		"Assign" : -12,
	},
	"optimum-intel-internal-testing/tiny-random-nanollava" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-phi-4-multimodal" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-phi3-vision" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-qwen" : {
		"ScaledDotProductAttention" : -2,
		"PagedAttentionExtension" : 2,
		"Parameter" : 18,
		"ReadValue" : -4,
		"Assign" : -4,
	},
	"optimum-intel-internal-testing/tiny-random-snowflake" : {
		"ScaledDotProductAttention" : -4,
		"PagedAttentionExtension" : 4,
		"Parameter" : 30,
		"ReadValue" : -8,
		"Assign" : -8,
	},

}
