# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(PUBLIC_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/any.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/attribute_adapter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/attribute_visitor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/axis_set.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/axis_vector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/coordinate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/coordinate_diff.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/core.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/core_visibility.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/deprecated.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/dimension.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/enum_mask.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/enum_names.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/except.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/extension.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/graph_util.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/interval.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/layout.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/log.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/model.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/node_input.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/node_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/node_vector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/op_extension.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/parallel.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/partial_shape.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/rank.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/rt_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/rtti.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/runtime_attribute.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/shape.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/strides.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/symbol.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/version.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/visibility.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/descriptor/input.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/descriptor/output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/descriptor/tensor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/color_format.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/input_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/input_model_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/input_tensor_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/output_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/output_model_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/output_tensor_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/padding_mode.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/postprocess_steps.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/pre_post_process.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/preprocess_steps.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/preprocess/resize_algorithm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/bfloat16.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/element_type.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/element_type_traits.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/float16.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/float4_e2m1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/float8_e4m3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/float8_e5m2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/core/type/float8_e8m0.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/abs.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/acos.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/acosh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/adaptive_avg_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/adaptive_max_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/add.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/asin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/asinh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/assign.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/atan.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/atanh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/avg_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/batch_norm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/batch_to_space.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/binary_convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bitwise_and.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bitwise_left_shift.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bitwise_not.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bitwise_or.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bitwise_right_shift.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bitwise_xor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/broadcast.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/bucketize.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/ceiling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/clamp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/col2im.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/concat.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/constant.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/convert.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/convert_like.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/convert_promote_types.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/cos.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/cosh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/ctc_greedy_decoder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/ctc_greedy_decoder_seq_len.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/ctc_loss.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/cum_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/deformable_convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/deformable_psroi_pooling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/depth_to_space.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/detection_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/dft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/divide.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/einsum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/elu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/embedding_segments_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/embeddingbag_offsets.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/embeddingbag_offsets_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/embeddingbag_packed.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/embeddingbag_packedsum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/equal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/erf.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/erfinv.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/exp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/experimental_detectron_detection_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/experimental_detectron_generate_proposals.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/experimental_detectron_prior_grid_generator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/experimental_detectron_roi_feature.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/experimental_detectron_topkrois.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/extractimagepatches.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/eye.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/fake_convert.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/fake_quantize.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/floor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/floor_mod.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gather.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gather_elements.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gather_nd.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gather_tree.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gelu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/generate_proposals.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/greater.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/greater_eq.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/grid_sample.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/grn.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/group_conv.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/group_normalization.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/grouped_matmul.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gru_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/gru_sequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/hard_sigmoid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/hsigmoid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/hswish.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/i420_to_bgr.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/i420_to_rgb.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/identity.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/idft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/if.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/interpolate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/inverse.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/irdft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/is_finite.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/is_inf.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/is_nan.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/istft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/less.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/less_eq.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/log.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/log_softmax.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/logical_and.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/logical_not.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/logical_or.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/logical_xor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/loop.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/lrn.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/lstm_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/lstm_sequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/matmul.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/matrix_nms.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/max_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/maximum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/minimum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/mish.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/mod.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/multiclass_nms.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/multinomial.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/multiply.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/mvn.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/negative.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/nms_rotated.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/non_max_suppression.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/non_zero.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/normalize_l2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/not_equal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/nv12_to_bgr.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/nv12_to_rgb.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/one_hot.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/op.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/ops.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/pad.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/parameter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/power.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/prelu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/prior_box.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/prior_box_clustered.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/proposal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/psroi_pooling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/random_uniform.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/range.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/rdft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/read_value.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_l1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_l2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_logical_and.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_logical_or.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_max.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_mean.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_min.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_prod.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reduce_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/region_yolo.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/relu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reorg_yolo.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reshape.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/result.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reverse.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/reverse_sequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/rnn_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/rnn_sequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/roi_align.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/roi_align_rotated.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/roi_pooling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/roll.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/round.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/scaled_dot_product_attention.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/scatter_elements_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/scatter_nd_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/scatter_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/search_sorted.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/segment_max.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/select.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/selu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/shape_of.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/shuffle_channels.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sigmoid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sign.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sinh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sink.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/slice.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/slice_scatter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/softmax.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/softplus.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/softsign.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/space_to_batch.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/space_to_depth.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sparse_fill_empty_rows.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/split.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/sqrt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/squared_difference.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/squeeze.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/stft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/strided_slice.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/string_tensor_pack.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/string_tensor_unpack.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/subtract.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/swish.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/tan.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/tanh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/tensor_iterator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/tile.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/topk.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/transpose.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/unique.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/unsqueeze.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/variadic_split.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/xor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/activation_functions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/arithmetic_reduction.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/arithmetic_reductions_keep_dims.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/assign_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/attr_types.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/avg_pool_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/binary_elementwise_arithmetic.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/binary_elementwise_bitwise.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/binary_elementwise_comparison.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/binary_elementwise_logical.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/broadcast_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/convert_color_i420_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/convert_color_nv12_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/convolution_backprop_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/convolution_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/deformable_convolution_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/detection_output_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/elementwise_args.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/embeddingbag_offsets_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/embeddingbag_packed_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/fft_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/framework_node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/gather_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/gather_nd_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/index_reduction.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/interpolate_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/logical_reduction.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/logical_reduction_keep_dims.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/max_pool_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/multi_subgraph_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/multiclass_nms_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/one_hot_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/op_types.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/pad_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/precision_sensitive_attribute.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/read_value_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/recurrent_sequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/reduction_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/rnn_cell_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/roi_align_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/scatter_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/scatter_elements_update_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/scatter_nd_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/shape_of_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/squeeze_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/sub_graph_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/symbolic_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/topk_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/unary_elementwise_arithmetic.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/variable.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/variable_context.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/variable_extension.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/op/util/variable_value.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset10.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset10_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset11.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset11_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset12.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset12_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset13.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset13_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset14.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset14_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset15.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset15_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset16.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset16_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset17.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset17_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset1_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset2_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset3.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset3_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset4.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset4_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset5.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset5_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset6.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset6_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset7.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset7_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset8.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset8_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset9.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/opsets/opset9_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/backward_graph_rewrite.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/constant_folding.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/convert_fp32_to_fp16.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/graph_rewrite.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/low_latency.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/make_stateful.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/manager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/matcher_pass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/node_registry.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pa_kv_reorder_fusion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pass.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pass_config.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/sdpa_to_paged_attention.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/sdpa_to_vlsdpa.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/serialize.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/stateful_to_stateless.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/validate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/visualize_tree.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/matcher.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/multi_matcher.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/any.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/any_of.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/any_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/block.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/block_util.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/label.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/op.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/optional.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/or.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/pattern.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/predicate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/true.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/pass/pattern/op/wrap_type.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/runtime/allocator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/runtime/file_handle.hpp
    ${CMAKE_CURRENT_LIST_DIR}/openvino/runtime/tensor.hpp
)
