// Copyright (C) 2018-2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

// Auto-generated by tools/polar_codebook_gen.py — do not edit manually.
// PolarQuant per-level angle codebooks, decision boundaries, and cos/sin LUTs.

#include <cmath>
#include <cstddef>

// Level 1, 5-bit: 32 centroids
static constexpr float POLARQ_CENTROIDS_L1_5BIT[32] = {
    0.09692368f, 0.29540771f, 0.49214223f, 0.69379300f, 0.89311677f, 1.09548533f, 1.29976487f, 1.50390363f,
    1.70558012f, 1.90376043f, 2.10461903f, 2.30458593f, 2.50533843f, 2.70387816f, 2.90072775f, 3.09507298f,
    3.29240012f, 3.48596692f, 3.67869592f, 3.86954904f, 4.06075239f, 4.25528383f, 4.45010328f, 4.64623070f,
    4.84208059f, 5.03918457f, 5.22838163f, 5.41547108f, 5.60417843f, 5.79968405f, 5.99312496f, 6.18592501f};
static constexpr float POLARQ_BOUNDARIES_L1_5BIT[31] = {
    0.19616570f, 0.39377499f, 0.59296763f, 0.79345489f, 0.99430102f, 1.19762504f, 1.40183425f, 1.60474181f,
    1.80467021f, 2.00418973f, 2.20460248f, 2.40496206f, 2.60460830f, 2.80230308f, 2.99790049f, 3.19373655f,
    3.38918352f, 3.58233142f, 3.77412248f, 3.96515059f, 4.15801811f, 4.35269356f, 4.54816675f, 4.74415541f,
    4.94063282f, 5.13378334f, 5.32192612f, 5.50982475f, 5.70193148f, 5.89640474f, 6.08952522f};
static constexpr float POLARQ_COS_L1_5BIT[32] = {
    0.99530655f,  0.95668352f,  0.88132262f,  0.76882607f,  0.62698698f,  0.45761502f,  0.26772541f,  0.06684282f,
    -0.13437606f, -0.32684577f, -0.50882792f, -0.66968876f, -0.80432707f, -0.90572280f, -0.97113204f, -0.99891818f,
    -0.98865008f, -0.94128686f, -0.85919440f, -0.74653572f, -0.60648847f, -0.44135231f, -0.25928876f, -0.06611003f,
    0.12932836f,  0.32100984f,  0.49339849f,  0.64657193f,  0.77819681f,  0.88537270f,  0.95822662f,  0.99527395f};
static constexpr float POLARQ_SIN_L1_5BIT[32] = {
    0.09677200f,  0.29112992f,  0.47251496f,  0.63945794f,  0.77902973f,  0.88915044f,  0.96349525f,  0.99776351f,
    0.99093038f,  0.94507772f,  0.86086828f,  0.74264187f,  0.59418684f,  0.42387053f,  0.23854265f,  0.04650289f,
    -0.15023649f, -0.33760774f, -0.51164925f, -0.66534537f, -0.79509228f, -0.89733392f, -0.96579987f, -0.99781233f,
    -0.99160182f, -0.94707584f, -0.86980337f, -0.76285303f, -0.62802047f, -0.46488193f, -0.28601006f, -0.09710704f};

// Level 1, 3-bit: 8 centroids
// MSE=0.051401, samples=256000000
static constexpr float POLARQ_CENTROIDS_L1_3BIT[8] =
    {0.39270288f, 1.17811370f, 1.96353114f, 2.74890828f, 3.53449726f, 4.31986904f, 5.10516453f, 5.89056206f};

static constexpr float POLARQ_BOUNDARIES_L1_3BIT[7] =
    {0.78540826f, 1.57082236f, 2.35621953f, 3.14170265f, 3.92718315f, 4.71251678f, 5.49786329f};

static constexpr float POLARQ_COS_L1_3BIT[8] =
    {0.92387807f, 0.38266826f, -0.38271642f, -0.92388511f, -0.92380083f, -0.38251781f, 0.38275415f, 0.92390847f};

static constexpr float POLARQ_SIN_L1_3BIT[8] =
    {0.38268694f, 0.92388582f, 0.92386585f, 0.38266996f, -0.38287336f, -0.92394811f, -0.92385024f, -0.38261348f};

// Level 1, 4-bit: 16 centroids
// MSE=0.012852, samples=256000000
static constexpr float POLARQ_CENTROIDS_L1_4BIT[16] = {0.19632146f,
                                                       0.58895415f,
                                                       0.98162860f,
                                                       1.37416577f,
                                                       1.76703978f,
                                                       2.15987062f,
                                                       2.55270171f,
                                                       2.94543338f,
                                                       3.33825159f,
                                                       3.73094463f,
                                                       4.12353086f,
                                                       4.51618719f,
                                                       4.90877724f,
                                                       5.30145693f,
                                                       5.69414854f,
                                                       6.08682966f};

static constexpr float POLARQ_BOUNDARIES_L1_4BIT[15] = {0.39263782f,
                                                        0.78529137f,
                                                        1.17789721f,
                                                        1.57060277f,
                                                        1.96345508f,
                                                        2.35628605f,
                                                        2.74906754f,
                                                        3.14184237f,
                                                        3.53459811f,
                                                        3.92723775f,
                                                        4.31985903f,
                                                        4.71248245f,
                                                        5.10511732f,
                                                        5.49780273f,
                                                        5.89048910f};

static constexpr float POLARQ_COS_L1_4BIT[16] = {0.98079073f,
                                                 0.83152211f,
                                                 0.55566931f,
                                                 0.19536594f,
                                                 -0.19498622f,
                                                 -0.55559152f,
                                                 -0.83155721f,
                                                 -0.98082238f,
                                                 -0.98072487f,
                                                 -0.83130103f,
                                                 -0.55541193f,
                                                 -0.19494537f,
                                                 0.19512849f,
                                                 0.55558646f,
                                                 0.83147609f,
                                                 0.98078412f};

static constexpr float POLARQ_SIN_L1_4BIT[16] = {0.19506279f,
                                                 0.55549169f,
                                                 0.83140343f,
                                                 0.98073041f,
                                                 0.98080599f,
                                                 0.83145541f,
                                                 0.55543911f,
                                                 0.19490376f,
                                                 -0.19539382f,
                                                 -0.55582249f,
                                                 -0.83157533f,
                                                 -0.98081410f,
                                                 -0.98077768f,
                                                 -0.83145875f,
                                                 -0.55556053f,
                                                 -0.19509612f};

// Level 2, 2-bit: 4 centroids
static constexpr float POLARQ_CENTROIDS_L2_2BIT[4] = {0.31085393f, 0.63622820f, 0.93819648f, 1.26180220f};
static constexpr float POLARQ_BOUNDARIES_L2_2BIT[3] = {0.47354108f, 0.78721237f, 1.09999931f};
static constexpr float POLARQ_COS_L2_2BIT[4] = {0.95207274f, 0.80434257f, 0.59124351f, 0.30410057f};
static constexpr float POLARQ_SIN_L2_2BIT[4] = {0.30587175f, 0.59416586f, 0.80649310f, 0.95263994f};

// Level 2, 3-bit: 8 centroids
// MSE=0.002636, samples=128000000
static constexpr float POLARQ_CENTROIDS_L2_3BIT[8] =
    {0.18831834f, 0.37976331f, 0.54799783f, 0.70702809f, 0.86339289f, 1.02238250f, 1.19068098f, 1.38228941f};

static constexpr float POLARQ_BOUNDARIES_L2_3BIT[7] =
    {0.28404084f, 0.46388060f, 0.62751299f, 0.78521049f, 0.94288766f, 1.10653174f, 1.28648520f};

static constexpr float POLARQ_COS_L2_3BIT[8] =
    {0.98232043f, 0.92875242f, 0.85356933f, 0.76029569f, 0.64986247f, 0.52133435f, 0.37102753f, 0.18739249f};

static constexpr float POLARQ_SIN_L2_3BIT[8] =
    {0.18720724f, 0.37070066f, 0.52097929f, 0.64957714f, 0.76005185f, 0.85335249f, 0.92862189f, 0.98228514f};

// Level 2, 5-bit: 32 centroids
// MSE=0.000174, samples=128000000
static constexpr float POLARQ_CENTROIDS_L2_5BIT[32] = {
    0.07052115f, 0.14108075f, 0.20143414f, 0.25627670f, 0.30740961f, 0.35583127f, 0.40209138f, 0.44656500f,
    0.48959243f, 0.53137827f, 0.57213676f, 0.61201787f, 0.65121669f, 0.68991148f, 0.72824180f, 0.76633406f,
    0.80436552f, 0.84244883f, 0.88075447f, 0.91943157f, 0.95865154f, 0.99856669f, 1.03935874f, 1.08114326f,
    1.12416029f, 1.16867125f, 1.21494937f, 1.26339817f, 1.31461406f, 1.36947548f, 1.42981446f, 1.50033903f};

static constexpr float POLARQ_BOUNDARIES_L2_5BIT[31] = {
    0.10580095f, 0.17125745f, 0.22885542f, 0.28184316f, 0.33162042f, 0.37896132f, 0.42432821f, 0.46807873f,
    0.51048535f, 0.55175751f, 0.59207731f, 0.63161731f, 0.67056406f, 0.70907664f, 0.74728793f, 0.78534979f,
    0.82340717f, 0.86160165f, 0.90009302f, 0.93904155f, 0.97860914f, 1.01896274f, 1.06025100f, 1.10265183f,
    1.14641583f, 1.19181037f, 1.23917377f, 1.28900611f, 1.34204471f, 1.39964497f, 1.46507680f};

static constexpr float POLARQ_COS_L2_5BIT[32] = {
    0.99751443f, 0.99006462f, 0.97978067f, 0.96734047f, 0.95312059f, 0.93735725f, 0.92024457f, 0.90193588f,
    0.88252461f, 0.86210948f, 0.84074599f, 0.81849039f, 0.79534692f, 0.77130234f, 0.74634576f, 0.72045779f,
    0.69356847f, 0.66563731f, 0.63656950f, 0.60627228f, 0.57462412f, 0.54150784f, 0.50677317f, 0.47031972f,
    0.43193403f, 0.39137477f, 0.34838441f, 0.30257982f, 0.25338927f, 0.19996372f, 0.14051530f, 0.07039897f};

static constexpr float POLARQ_SIN_L2_5BIT[32] = {
    0.07046270f, 0.14061321f, 0.20007467f, 0.25348061f, 0.30259070f, 0.34836966f, 0.39134380f, 0.43186995f,
    0.47026625f, 0.50672203f, 0.54142976f, 0.57452023f, 0.60615456f, 0.63646889f, 0.66555846f, 0.69349879f,
    0.72039074f, 0.74627542f, 0.77121937f, 0.79525715f, 0.81841743f, 0.84069568f, 0.86207944f, 0.88249612f,
    0.90190518f, 0.92023140f, 0.93735176f, 0.95312405f, 0.96736437f, 0.97980332f, 0.99007851f, 0.99751890f};

// Level 3, 2-bit: 4 centroids
static constexpr float POLARQ_CENTROIDS_L3_2BIT[4] = {0.42617366f, 0.67295450f, 0.89500540f, 1.14298379f};
static constexpr float POLARQ_BOUNDARIES_L3_2BIT[3] = {0.54956406f, 0.78397995f, 1.01899457f};
static constexpr float POLARQ_COS_L3_2BIT[4] = {0.91055417f, 0.78198355f, 0.62551457f, 0.41488150f};
static constexpr float POLARQ_SIN_L3_2BIT[4] = {0.41338974f, 0.62329906f, 0.78021246f, 0.90987545f};

// Level 3, 3-bit: 8 centroids
// MSE=0.001720, samples=64000000
static constexpr float POLARQ_CENTROIDS_L3_3BIT[8] =
    {0.30757028f, 0.47326383f, 0.60618919f, 0.72687811f, 0.84414071f, 0.96482241f, 1.09770608f, 1.26333070f};

static constexpr float POLARQ_BOUNDARIES_L3_3BIT[7] =
    {0.39041704f, 0.53972650f, 0.66653365f, 0.78550941f, 0.90448153f, 1.03126419f, 1.18051839f};

static constexpr float POLARQ_COS_L3_3BIT[8] =
    {0.95307195f, 0.89008540f, 0.82182515f, 0.74725264f, 0.66437376f, 0.56956285f, 0.45563933f, 0.30264407f};

static constexpr float POLARQ_SIN_L3_3BIT[8] =
    {0.30274382f, 0.45579380f, 0.56973982f, 0.66454005f, 0.74740052f, 0.82194775f, 0.89016449f, 0.95310366f};

// Level 3, 4-bit: 16 centroids
// MSE=0.000457, samples=64000000
static constexpr float POLARQ_CENTROIDS_L3_4BIT[16] = {0.22021720f,
                                                       0.33432585f,
                                                       0.42223349f,
                                                       0.49809739f,
                                                       0.56712967f,
                                                       0.63198042f,
                                                       0.69424802f,
                                                       0.75514114f,
                                                       0.81553096f,
                                                       0.87639028f,
                                                       0.93865258f,
                                                       1.00348222f,
                                                       1.07254815f,
                                                       1.14846575f,
                                                       1.23645902f,
                                                       1.35061789f};

static constexpr float POLARQ_BOUNDARIES_L3_4BIT[15] = {0.27727154f,
                                                        0.37827969f,
                                                        0.46016544f,
                                                        0.53261352f,
                                                        0.59955502f,
                                                        0.66311419f,
                                                        0.72469455f,
                                                        0.78533602f,
                                                        0.84596062f,
                                                        0.90752143f,
                                                        0.97106737f,
                                                        1.03801513f,
                                                        1.11050689f,
                                                        1.19246244f,
                                                        1.29353845f};

static constexpr float POLARQ_COS_L3_4BIT[16] = {0.97585005f,
                                                 0.94463176f,
                                                 0.91217595f,
                                                 0.87849313f,
                                                 0.84344643f,
                                                 0.80685920f,
                                                 0.76853502f,
                                                 0.72817481f,
                                                 0.68548191f,
                                                 0.63992918f,
                                                 0.59087563f,
                                                 0.53736889f,
                                                 0.47788745f,
                                                 0.40988740f,
                                                 0.32814321f,
                                                 0.21840379f};

static constexpr float POLARQ_SIN_L3_4BIT[16] = {0.21844159f,
                                                 0.32813242f,
                                                 0.40979883f,
                                                 0.47775498f,
                                                 0.53721333f,
                                                 0.59074384f,
                                                 0.63980770f,
                                                 0.68539143f,
                                                 0.72808963f,
                                                 0.76843393f,
                                                 0.80676264f,
                                                 0.84334731f,
                                                 0.87842107f,
                                                 0.91213614f,
                                                 0.94462800f,
                                                 0.97585851f};

// Level 4, 3-bit: 8 centroids
// MSE=0.000973, samples=32000000
static constexpr float POLARQ_CENTROIDS_L4_3BIT[8] =
    {0.42588434f, 0.55567163f, 0.65483624f, 0.74292272f, 0.82798368f, 0.91600144f, 1.01507926f, 1.14502001f};

static constexpr float POLARQ_BOUNDARIES_L4_3BIT[7] =
    {0.49077797f, 0.60525393f, 0.69887948f, 0.78545320f, 0.87199259f, 0.96554035f, 1.08004963f};

static constexpr float POLARQ_COS_L4_3BIT[8] =
    {0.91067374f, 0.84954631f, 0.79314768f, 0.73649466f, 0.67636228f, 0.60899657f, 0.52755260f, 0.41302794f};

static constexpr float POLARQ_SIN_L4_3BIT[8] =
    {0.41312629f, 0.52751398f, 0.60902935f, 0.67644334f, 0.73656911f, 0.79317290f, 0.84952235f, 0.91071838f};

// Level 5, 2-bit: 4 centroids
// MSE=0.001769, samples=16000000
static constexpr float POLARQ_CENTROIDS_L5_2BIT[4] = {0.59856242f, 0.72900337f, 0.84179825f, 0.97218698f};

static constexpr float POLARQ_BOUNDARIES_L5_2BIT[3] = {0.66378289f, 0.78540081f, 0.90699261f};

static constexpr float POLARQ_COS_L5_2BIT[4] = {0.82614648f, 0.74583864f, 0.66612273f, 0.56349415f};

static constexpr float POLARQ_SIN_L5_2BIT[4] = {0.56345540f, 0.66612667f, 0.74584216f, 0.82612008f};

// Level 6, 2-bit: 4 centroids
// MSE=0.000901, samples=8000000
static constexpr float POLARQ_CENTROIDS_L6_2BIT[4] = {0.65240341f, 0.74531835f, 0.82527328f, 0.91813117f};

static constexpr float POLARQ_BOUNDARIES_L6_2BIT[3] = {0.69886088f, 0.78529584f, 0.87170225f};

static constexpr float POLARQ_COS_L6_2BIT[4] = {0.79462701f, 0.73487204f, 0.67835617f, 0.60730594f};

static constexpr float POLARQ_SIN_L6_2BIT[4] = {0.60709798f, 0.67820579f, 0.73473322f, 0.79446805f};

// Level 5, 3-bit — needed for polar3 dim=256
static constexpr float POLARQ_CENTROIDS_L5_3BIT[8] =
    {0.52328789f, 0.61938542f, 0.69115025f, 0.75434774f, 0.81519520f, 0.87827575f, 0.94998318f, 1.04622591f};
static constexpr float POLARQ_BOUNDARIES_L5_3BIT[7] =
    {0.57133663f, 0.65526783f, 0.72274899f, 0.78477144f, 0.84673548f, 0.91412944f, 0.99810451f};
static constexpr float POLARQ_COS_L5_3BIT[8] =
    {0.86618084f, 0.81423539f, 0.77051330f, 0.72871834f, 0.68572628f, 0.63847911f, 0.58169675f, 0.50084120f};
static constexpr float POLARQ_SIN_L5_3BIT[8] =
    {0.49973074f, 0.58053488f, 0.63742387f, 0.68481350f, 0.72785950f, 0.76963913f, 0.81340575f, 0.86553919f};

// Level 6, 3-bit — needed for polar3 dim=256
static constexpr float POLARQ_CENTROIDS_L6_3BIT[8] =
    {0.59811950f, 0.66741502f, 0.71872991f, 0.76355577f, 0.80657953f, 0.85146618f, 0.90270966f, 0.97220147f};
static constexpr float POLARQ_BOUNDARIES_L6_3BIT[7] =
    {0.63276726f, 0.69307244f, 0.74114281f, 0.78506762f, 0.82902282f, 0.87708789f, 0.93745553f};
static constexpr float POLARQ_COS_L6_3BIT[8] =
    {0.82639599f, 0.78542429f, 0.75264257f, 0.72238177f, 0.69197178f, 0.65888089f, 0.61948514f, 0.56348217f};
static constexpr float POLARQ_SIN_L6_3BIT[8] =
    {0.56308943f, 0.61895776f, 0.65842927f, 0.69149441f, 0.72192454f, 0.75224727f, 0.78500843f, 0.82612818f};

// Level 6, 5-bit: 32 centroids — needed for optimal polar4
static constexpr float POLARQ_CENTROIDS_L6_5BIT[32] = {
    0.53798705f, 0.59076416f, 0.62029767f, 0.64516973f, 0.66534853f, 0.68169796f, 0.69450229f, 0.70789754f,
    0.72011614f, 0.73139447f, 0.74125266f, 0.74977887f, 0.75789201f, 0.76668018f, 0.77477026f, 0.78272140f,
    0.79006416f, 0.79851598f, 0.80709034f, 0.81647289f, 0.82597131f, 0.83535737f, 0.84564650f, 0.85568291f,
    0.86664265f, 0.88052571f, 0.89563268f, 0.91400462f, 0.93309599f, 0.95677823f, 0.98735154f, 1.03022647f};
static constexpr float POLARQ_BOUNDARIES_L6_5BIT[31] = {
    0.56437558f, 0.60553092f, 0.63273370f, 0.65525913f, 0.67352325f, 0.68810016f, 0.70119995f, 0.71400684f,
    0.72575533f, 0.73632360f, 0.74551576f, 0.75383544f, 0.76228613f, 0.77072525f, 0.77874583f, 0.78639275f,
    0.79429007f, 0.80280316f, 0.81178164f, 0.82122213f, 0.83066434f, 0.84050190f, 0.85066468f, 0.86116278f,
    0.87358415f, 0.88807923f, 0.90481865f, 0.92355031f, 0.94493711f, 0.97206491f, 1.00878906f};
static constexpr float POLARQ_COS_L6_5BIT[32] = {
    0.85874188f, 0.83051527f, 0.81370544f, 0.79899770f, 0.78670168f, 0.77650392f, 0.76837236f, 0.75973064f,
    0.75172913f, 0.74424374f, 0.73762333f, 0.73183960f, 0.72628665f, 0.72021776f, 0.71458179f, 0.70899701f,
    0.70379972f, 0.69777054f, 0.69160295f, 0.68479580f, 0.67784315f, 0.67091274f, 0.66324759f, 0.65570307f,
    0.64738899f, 0.63674587f, 0.62502503f, 0.61057913f, 0.59534931f, 0.57615626f, 0.55090213f, 0.51462466f};
static constexpr float POLARQ_SIN_L6_5BIT[32] = {
    0.51240844f, 0.55699581f, 0.58127743f, 0.60133404f, 0.61733335f, 0.63011241f, 0.64000309f, 0.65023792f,
    0.65947199f, 0.66790813f, 0.67521244f, 0.68147695f, 0.68739200f, 0.69374806f, 0.69955194f, 0.70521152f,
    0.71039844f, 0.71632141f, 0.72227794f, 0.72873503f, 0.73520654f, 0.74153632f, 0.74840009f, 0.75501889f,
    0.76215971f, 0.77107376f, 0.78060466f, 0.79195523f, 0.80346698f, 0.81733960f, 0.83456987f, 0.85741556f};

// Level 7, 2-bit — needed for polar3 dim=256
static constexpr float POLARQ_CENTROIDS_L7_2BIT[4] = {0.69146830f, 0.75732541f, 0.81385344f, 0.87985408f};
static constexpr float POLARQ_BOUNDARIES_L7_2BIT[3] = {0.72439682f, 0.78558940f, 0.84685373f};
static constexpr float POLARQ_COS_L7_2BIT[4] = {0.77031058f, 0.72667599f, 0.68670231f, 0.63726360f};
static constexpr float POLARQ_SIN_L7_2BIT[4] = {0.63766891f, 0.68698037f, 0.72693872f, 0.77064592f};

// -----------------------------------------------------------------------
// Bit allocation tables — dim-specific.
// -----------------------------------------------------------------------
static constexpr int POLARQ_MAX_LEVELS = 8;

// Optimal allocations from exhaustive search (DiagnosticAllocationSearch).
// polar4/128: [5,3,3,3,3,5,2] RMSE=0.098 vs TBQ4 RMSE=0.096 — parity.
static constexpr int POLARQ_BITS_POLAR4_128[POLARQ_MAX_LEVELS] = {5, 3, 3, 3, 3, 5, 2, 0};
// polar4/256: same pattern extended; L8 gets 0 (fixed).
// @todo claude: run exhaustive search for dim=256 to validate
static constexpr int POLARQ_BITS_POLAR4_256[POLARQ_MAX_LEVELS] = {5, 3, 3, 3, 3, 5, 2, 0};
// polar3/128: [4,2,2,3,2,0,0] RMSE=0.230 (best found, still behind TBQ3 0.183).
static constexpr int POLARQ_BITS_POLAR3_128[POLARQ_MAX_LEVELS] = {4, 2, 2, 3, 2, 0, 0, 0};
// polar3/256: extended for L=8.
// @todo claude: run exhaustive search for dim=256
static constexpr int POLARQ_BITS_POLAR3_256[POLARQ_MAX_LEVELS] = {4, 2, 2, 3, 2, 2, 2, 0};

static inline const int* polarq_get_bits_per_level(int bits, int head_dim) {
    if (bits == 4)
        return (head_dim <= 128) ? POLARQ_BITS_POLAR4_128 : POLARQ_BITS_POLAR4_256;
    return (head_dim <= 128) ? POLARQ_BITS_POLAR3_128 : POLARQ_BITS_POLAR3_256;
}

static constexpr float POLARQ_FIXED_ANGLE = 0.78539816339744830962f;
static constexpr float POLARQ_FIXED_COS = 0.70710678118654752440f;
static constexpr float POLARQ_FIXED_SIN = 0.70710678118654752440f;

// -----------------------------------------------------------------------
// LUT accessor.
// -----------------------------------------------------------------------

struct PolarqLevelLUT {
    const float* centroids;
    const float* boundaries;
    const float* cos_lut;
    const float* sin_lut;
    int n_centroids;
};

static inline PolarqLevelLUT polarq_get_lut(int level_1based, int bits) {
    if (bits == 0)
        return {nullptr, nullptr, nullptr, nullptr, 0};
    switch (level_1based * 16 + bits) {
    case 1 * 16 + 3:
        return {POLARQ_CENTROIDS_L1_3BIT, POLARQ_BOUNDARIES_L1_3BIT, POLARQ_COS_L1_3BIT, POLARQ_SIN_L1_3BIT, 8};
    case 1 * 16 + 4:
        return {POLARQ_CENTROIDS_L1_4BIT, POLARQ_BOUNDARIES_L1_4BIT, POLARQ_COS_L1_4BIT, POLARQ_SIN_L1_4BIT, 16};
    case 1 * 16 + 5:
        return {POLARQ_CENTROIDS_L1_5BIT, POLARQ_BOUNDARIES_L1_5BIT, POLARQ_COS_L1_5BIT, POLARQ_SIN_L1_5BIT, 32};
    case 2 * 16 + 2:
        return {POLARQ_CENTROIDS_L2_2BIT, POLARQ_BOUNDARIES_L2_2BIT, POLARQ_COS_L2_2BIT, POLARQ_SIN_L2_2BIT, 4};
    case 2 * 16 + 3:
        return {POLARQ_CENTROIDS_L2_3BIT, POLARQ_BOUNDARIES_L2_3BIT, POLARQ_COS_L2_3BIT, POLARQ_SIN_L2_3BIT, 8};
    case 2 * 16 + 5:
        return {POLARQ_CENTROIDS_L2_5BIT, POLARQ_BOUNDARIES_L2_5BIT, POLARQ_COS_L2_5BIT, POLARQ_SIN_L2_5BIT, 32};
    case 3 * 16 + 2:
        return {POLARQ_CENTROIDS_L3_2BIT, POLARQ_BOUNDARIES_L3_2BIT, POLARQ_COS_L3_2BIT, POLARQ_SIN_L3_2BIT, 4};
    case 3 * 16 + 3:
        return {POLARQ_CENTROIDS_L3_3BIT, POLARQ_BOUNDARIES_L3_3BIT, POLARQ_COS_L3_3BIT, POLARQ_SIN_L3_3BIT, 8};
    case 3 * 16 + 4:
        return {POLARQ_CENTROIDS_L3_4BIT, POLARQ_BOUNDARIES_L3_4BIT, POLARQ_COS_L3_4BIT, POLARQ_SIN_L3_4BIT, 16};
    case 4 * 16 + 3:
        return {POLARQ_CENTROIDS_L4_3BIT, POLARQ_BOUNDARIES_L4_3BIT, POLARQ_COS_L4_3BIT, POLARQ_SIN_L4_3BIT, 8};
    case 5 * 16 + 2:
        return {POLARQ_CENTROIDS_L5_2BIT, POLARQ_BOUNDARIES_L5_2BIT, POLARQ_COS_L5_2BIT, POLARQ_SIN_L5_2BIT, 4};
    case 5 * 16 + 3:
        return {POLARQ_CENTROIDS_L5_3BIT, POLARQ_BOUNDARIES_L5_3BIT, POLARQ_COS_L5_3BIT, POLARQ_SIN_L5_3BIT, 8};
    case 6 * 16 + 2:
        return {POLARQ_CENTROIDS_L6_2BIT, POLARQ_BOUNDARIES_L6_2BIT, POLARQ_COS_L6_2BIT, POLARQ_SIN_L6_2BIT, 4};
    case 6 * 16 + 3:
        return {POLARQ_CENTROIDS_L6_3BIT, POLARQ_BOUNDARIES_L6_3BIT, POLARQ_COS_L6_3BIT, POLARQ_SIN_L6_3BIT, 8};
    case 6 * 16 + 5:
        return {POLARQ_CENTROIDS_L6_5BIT, POLARQ_BOUNDARIES_L6_5BIT, POLARQ_COS_L6_5BIT, POLARQ_SIN_L6_5BIT, 32};
    case 7 * 16 + 2:
        return {POLARQ_CENTROIDS_L7_2BIT, POLARQ_BOUNDARIES_L7_2BIT, POLARQ_COS_L7_2BIT, POLARQ_SIN_L7_2BIT, 4};
    default:
        return {nullptr, nullptr, nullptr, nullptr, 0};
    }
}

// -----------------------------------------------------------------------
// Compute packed head record size in bytes.
// Each level is individually byte-rounded when packed.
// -----------------------------------------------------------------------
static inline size_t polarq_head_bytes_from_alloc(int head_dim, const int* bits_per_level) {
    size_t total_bytes = 0;
    int L = 0;
    for (int d = head_dim; d > 1; d >>= 1)
        L++;
    for (int k = 0; k < L; k++) {
        int n_bits = (head_dim >> (k + 1)) * bits_per_level[k];
        total_bytes += static_cast<size_t>((n_bits + 7) / 8);
    }
    return total_bytes + 4;  // + fp32 norm
}
