# Copyright (C) 2018-2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# set(CPACK_APP_VALUE_LEN "1")
# set(CPACK_BUILD_SOURCE_DIRS "/home/sandye51/Documents/Programming/git_repo/dldt;/home/sandye51/Documents/Programming/builds/dldt-release-gcc9")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "ngraph;ngraph_dev")
# set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
# set(CPACK_INSTALL_CMAKE_PROJECTS "/home/sandye51/Documents/Programming/builds/dldt-release-gcc9;OpenVINO;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/sandye51/Documents/Programming/builds/dldt-release-gcc9/install")
set(CPACK_MODULE_PATH "")
set(CPACK_OUTPUT_CONFIG_FILE "/home/sandye51/Documents/Programming/builds/dldt-release-gcc9/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
# set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.20/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenVINO toolkit")
set(CPACK_PACKAGE_DESCRIPTION "OpenVINO toolkit")
set(CPACK_PACKAGE_FILE_NAME "inference-engine_ngraph")
# set(CPACK_PACKAGE_INSTALL_DIRECTORY "inference-engine custom_cpack-dev-pkg_abe0336479cac9737a5563cbf25f81993928a135")
# set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "inference-engine custom_cpack-dev-pkg_abe0336479cac9737a5563cbf25f81993928a135")
set(CPACK_PACKAGE_NAME "inference-engine")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Intel Corporation")
set(CPACK_PACKAGE_VERSION "ngraphonly")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
# set(CPACK_SET_DESTDIR "OFF")
set(CPACK_STRIP_FILES "ON")
# set(CPACK_SYSTEM_NAME "Linux")
# set(CPACK_THREADS "8")
# set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_VERBATIM_VARIABLES "ON")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/sandye51/Documents/Programming/builds/dldt-release-gcc9;OpenVINO;ngraph_dev;/")

# if(NOT CPACK_PROPERTIES_FILE)
#   set(CPACK_PROPERTIES_FILE "/home/sandye51/Documents/Programming/builds/dldt-release-gcc9/CPackProperties.cmake")
# endif()

# if(EXISTS ${CPACK_PROPERTIES_FILE})
#   include(${CPACK_PROPERTIES_FILE})
# endif()
