name: Build Issue Report
description: This report is for the build/installation issue
title: "[Build]: "
labels: ["build", "support_request"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the necessary information to expedite the response.
  - type: input
    id: ov_version
    attributes:
      label: OpenVINO Version 
      description: OpenVINO version, branch, or tag in OpenVINO GitHub
      placeholder: 2021.4.0 LTS / Master Branch / tag 2022.3.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Ubuntu 18.04 (LTS)
        - Ubuntu 20.04 (LTS)
        - Windows System
        - Red Hat Enterprise Linux 8
        - Android System
        - Raspbian Stretch OS
        - macOS Systems for Intel CPU
        - macOS Systems for Apple Silicon
        - WebAssembly
        - Other (Please specify in description)
    validations:
      required: true
  - type: input
    id: target_platform
    attributes:
      label: Target Platform
      description: The platform that the OpenVINO source is built on
      placeholder: 11th Gen Intel Core i7-1185G7
    validations:
      required: false
  - type: textarea
    id: build_description
    attributes:
      label: Build issue description
      description: What issue are you facing during the build/installation?
      placeholder: Please provide a detailed description of what happened
    validations:
      required: true
  - type: textarea
    id: build_script
    attributes:
      label: Build scrip or step-by-step to reproduce
      description: How can we reproduce your issue?
      placeholder: Please provide detailed instructions on how to reproduce the issue
    validations:
      required: false
  - type: textarea
    id: build_logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Issue submission checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/intel/intel-one-mono/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I report the issue. It's not a question
          required: true
        - label: I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found the solution
          required: true
