name: Performance Issue Report
description: This report is for the performance-related issue
title: "[Performance]: "
labels: ["performance", "support_request"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the necessary information to expedite the response.
  - type: input
    id: ov_version
    attributes:
      label: OpenVINO Version 
      description: OpenVINO version, branch, or tag in OpenVINO GitHub
      placeholder: 2021.4.0 LTS / Master Branch / tag 2022.3.0
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using? 
      options:
        - Ubuntu 18.04 (LTS)
        - Ubuntu 20.04 (LTS)
        - Ubuntu 22.04 (LTS)
        - Windows System
        - Red Hat Enterprise Linux 8
        - OpenSUSE
        - Android System
        - Raspbian Stretch OS
        - macOS Systems for Intel CPU
        - macOS Systems for Apple Silicon
        - WebAssembly
        - WSL2 on Windows
        - Other (Please specify in description)
    validations:
      required: true
  - type: dropdown
    id: device_use
    attributes:
      label: Device used for inference
      description: What hardware are you using for inference?
      options:
        - CPU
        - iGPU
        - dGPU
        - NPU
    validations:
      required: false
  - type: dropdown
    id: openvino_installation
    attributes:
      label: OpenVINO installation 
      description: How do you install OpenVINO on your system?
      options:
        - PyPi
        - Docker
        - Build from source
        - Other virtual machines 
    validations:
      required: true
  - type: dropdown
    id: openvino_api
    attributes:
      label: Programming Language 
      description: What is the programming language you use in your performance test? 
      options:
        - Python
        - C++
        - Other
    validations:
      required: true
  - type: dropdown
    id: architecture
    attributes:
      label: Hardware Architecture 
      description: What is your hardware architecture used in this test?
      options:
        - x86 (64 bits)
        - x86 (32 bits)
        - ARM (64 bits)
        - ARM (32 bits)
        - RISC-V
        - Other (please specify in the description)
    validations:
      required: true
  - type: input
    id: model_name
    attributes:
      label: Model used
      description: Link to the model
      placeholder: ResNet50 / YOLOv4
    validations:
      required: true
  - type: dropdown
    id: model_quantized
    attributes:
      label: Model quantization
      description: Is your model quantized?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: target_platform
    attributes:
      label: Target Platform
      description: |
          You can also provide us full system log with the following command 
          Windows cmd     - "systeminfo" 
          Linux terminal  - "lscpu" and "lscpu -e"
      placeholder: Paste your full platform/system information here 
    validations:
      required: false
  - type: textarea
    id: performance_description
    attributes:
      label: Performance issue description
      description: What issue are you having, and what did you expect to happen instead?
      placeholder: |
          Please provide a detailed description of what happened.
          Can the issue be reproduced using benchmark_app?
    validations:
      required: true
  - type: textarea
    id: step_by_step
    attributes:
      label: Step-by-step reproduction 
      description: How can we reproduce your issue?
      placeholder: Please provide detailed instructions on how to reproduce the issue
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Issue submission checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/intel/intel-one-mono/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I'm reporting a performance issue. It's not a question.
          required: true
        - label: I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
          required: true
        - label: There is reproducer code and related data files such as images, videos, models, etc.
          required: true
