name: Pre-release Feedback
description: Feedback on Pre-release OpenVINO 
title: "[Pre-Release Feedback]:"
labels: ["Pre-release", "support_request"]
assignees:
  - octocat
body:
  - type: textarea
    id: feedback
    attributes:
      label: Pre-release feedback
      description: What is the issue or feedback on the pre-release?
      placeholder: Please describe the issue and/or feedback
      value: "Inference performance drop in OpenVINO 2022.4."
    validations:
      required: true
  - type: textarea
    id: thoughts
    attributes:
      label: Thought on new feature release
      description: What are your thoughts on the new features released in pre release?
      placeholder: any thoughts on the new feature are welcome
    validations:
      required: false
  - type: checkboxes
    id: checklist3
    attributes:
      label: Pre-release Feedback submission checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/intel/intel-one-mono/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: Have a new feature you would like to see in OpenVINO? File a feature request here <link to feature request issue>. You can also implement the feature yourself by following the CONTRIBUTING.MD <link this to contributing.md file>.
          required: true
