# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(op_list
    ${CMAKE_CURRENT_LIST_DIR}/src/op/abs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/acos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/acosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/adaptive_avg_pooling2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/affine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/affine_grid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/ai.onnx.ml/normalizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/argmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/argmin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/asin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/asinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/atan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/atanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/aten.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/average_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/bitshift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/bitwise_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/bitwise_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/bitwise_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/bitwise_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/blackmanwindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/cast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/cast_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/ceil.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/celu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/center_crop_pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/clip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/aliases.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/bias_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/bias_gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/bifurcation_detector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/dynamic_quantize_lstm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/dynamic_quantize_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/embed_layer_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/fast_gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/fused_conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/fusedgemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/fusedmatmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/gather_block_quantized.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/group_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/group_query_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/matmul_integer_to_float.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/matmulnbits.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/multi_head_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/qlinear_activation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/qlinear_concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/qlinear_ops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/qlinear_where.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/quick_gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/rotary_embedding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/simplified_layer_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/skip_layer_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/com.microsoft/skip_simplified_layer_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/compress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/concat_from_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/constant_fill.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/constant_of_shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/conv_integer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/conv_transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/cos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/cosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/crop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/dequantize_linear.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/div.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/dropout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/dynamic_quantize_linear.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/elu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/erf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/exp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/expand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/eye_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/flatten.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/floor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/global_average_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/global_max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/greater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/greater_or_equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gru.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/hammingwindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/hannwindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/hard_sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/hard_swish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/hardmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/image_scaler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/instance_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/is_finite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/is_inf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/is_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/layer_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/leaky_relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/less.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/less_or_equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/lp_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/lp_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/lstm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/matmul_integer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/max_roi_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/mean.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/mean_variance_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/min.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/mish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/mmdeploy_roi_align_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/mul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/neg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/neg_log_like_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/non_zero.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/onehot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/deformable_conv_2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/experimental_detectron/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/experimental_detectron/generate_proposals_single_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/experimental_detectron/prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/experimental_detectron/roi_feature_extractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/experimental_detectron/topk_rios.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/fake_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/group_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/normalize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/org.openvinotoolkit/swish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/pow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/prelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/qlinear_conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/qlinear_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/quantize_linear.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/random_normal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/random_normal_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/random_uniform_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reciprocal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reduce.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/resize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/rms_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/rnn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/rotary_embedding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/round.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/scan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/scatter_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/scatter_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/selu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sequence_at.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sequence_construct.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sequence_empty.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sequence_erase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sequence_insert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sequence_length.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/shrink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/size.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/softmax_cro_ent_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/softplus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/softsign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/split_to_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sqrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/squeeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sub.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/swish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/tan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/tanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/thresholded_relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/topk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/trilu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/unsqueeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/upsample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/where.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/xor.cpp
)

set(ONNX_FRONTEND_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/src/core/attribute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/decoder_proto.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph_iterator_proto.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/null_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/place.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/tensor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/transform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/detail/subgraph_extraction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/edge_mapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/editor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/exceptions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/frontend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/input_model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/node_context.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/onnx_framework_node.cpp
    ${op_list}
    ${CMAKE_CURRENT_LIST_DIR}/src/ops_bridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/place.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/translate_session.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/arg_min_max_factory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/conv_factory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/convpool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/onnx_internal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/pooling_factory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/recurrent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/tensor_external_data.cpp
)

set(ONNX_FRONTEND_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/src/core/attribute.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/decoder_proto.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph_cache.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/graph_iterator_proto.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/model.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/null_node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/operator_set.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/place.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/sparse_tensor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/tensor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/transform.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/core/value_info.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/detail/subgraph_extraction.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/edge_mapper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/editor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/editor_types.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/exceptions.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/input_model.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/onnx_framework_node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/ops_bridge.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/place.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/precomp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/translate_session.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/arg_min_max_factory.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/attention.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/common.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/conv_factory.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/convpool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/dft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/norm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/onnx_internal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/pooling_factory.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/recurrent.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/reshape.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/split.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/tensor_external_data.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/variadic.hpp
    ${CMAKE_CURRENT_LIST_DIR}/src/version_range.hpp
)

set(ONNX_FRONTEND_PUBLIC_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/decoder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/extension/conversion.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/extension/op.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/frontend.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/graph_iterator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/node_context.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/frontend/onnx/visibility.hpp
)
