# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(GPU_KERNEL_SELECTOR_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/auto_tuner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/auto_tuner.h
    ${CMAKE_CURRENT_LIST_DIR}/common_tools.h
    ${CMAKE_CURRENT_LIST_DIR}/common_types.h
    ${CMAKE_CURRENT_LIST_DIR}/jitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/jitter.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_base_cm.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_base_opencl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_base_opencl.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_common.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_params.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_params.h
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_utils.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/activation/activation_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/adaptive_pooling/adaptive_pooling_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/adaptive_pooling/adaptive_pooling_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/adaptive_pooling/adaptive_pooling_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/adaptive_pooling/adaptive_pooling_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_axis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_axis.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_gpu_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_gpu_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_topk_radix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/arg_max_min/arg_max_min_kernel_topk_radix.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/batch_to_space/batch_to_space_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/batch_to_space/batch_to_space_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/batch_to_space/batch_to_space_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/batch_to_space/batch_to_space_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/batch_to_space/batch_to_space_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/batch_to_space/batch_to_space_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/beam_table_update/beam_table_update_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/beam_table_update/beam_table_update_kernel_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/beam_table_update/beam_table_update_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/beam_table_update/beam_table_update_kernel_selector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/border/border_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/border/border_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/border/border_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/border/border_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/border/border_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/border/border_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/broadcast/broadcast_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/bucketize/bucketize_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/bucketize/bucketize_kernel_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/bucketize/bucketize_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/bucketize/bucketize_kernel_selector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_b_fs_yx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_b_fs_yx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_b_fs_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_b_fs_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_depth_bfyx_no_pitch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_depth_bfyx_no_pitch.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_fs_b_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_fs_b_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_simple_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/concatenation/concatenation_kernel_simple_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convert_color/convert_color_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convert_color/convert_color_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convert_color/convert_color_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convert_color/convert_color_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convert_color/convert_color_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convert_color/convert_color_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_1d_small_ic_gemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_1d_small_ic_gemm.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_1x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_1x1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_depthwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_depthwise.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_imad_1x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv16_imad_1x1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv4_int8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv4_int8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv_16_32_imad_dw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_yx_fsv_16_32_imad_dw.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_fp16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_fp32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_imad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_b_fs_zyx_fsv16_imad.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_1x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_1x1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_1x1_gemm_buf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_1x1_gemm_buf.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_1x1_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_1x1_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_depthwise_weights_lwg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_depthwise_weights_lwg.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_direct_10_12_16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_direct_10_12_16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_gemm_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_gemm_like.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_iyxo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_iyxo.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_os_iyx_osv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_to_b_fs_yx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_to_b_fs_yx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_to_bs_fs_yx_bsv16_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_to_bs_fs_yx_bsv16_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_to_fs_byx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_bfyx_to_fs_byx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_fs_byx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_fs_byx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_fs_byx_fsv32_1x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_fs_byx_fsv32_1x1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_fs_byx_fsv32_depthwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_fs_byx_fsv32_depthwise.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_b_fs_yx_fsv4_1x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_b_fs_yx_fsv4_1x1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_b_fs_yx_fsv4_dw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_b_fs_yx_fsv4_dw.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_bs_fs_yx_bsv16_fsv16_1x1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_bs_fs_yx_bsv16_fsv16_1x1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_bs_fs_yx_bsv16_fsv16_3x3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_imad_bs_fs_yx_bsv16_fsv16_3x3.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_b_fs_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_b_fs_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_b_fs_yx_fsv32_dw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_b_fs_yx_fsv32_dw.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_bfyx_to_b_fs_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_bfyx_to_b_fs_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_bfyx_to_b_fs_yx_fsv4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_mmad_bfyx_to_b_fs_yx_fsv4.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_winograd_2x3_s1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_winograd_2x3_s1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_winograd_2x3_s1_fused.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_winograd_2x3_s1_fused.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_winograd_6x3_s1_fused.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_winograd_6x3_s1_fused.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_yxio_b16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_yxio_b16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_yxio_b1_block_multiple_x.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_yxio_b1_block_multiple_x.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_yxio_b8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_kernel_yxfb_yxio_b8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_params.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/convolution_params.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/deformable_convolution_kernel_bfyx_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/deformable_convolution_kernel_bfyx_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/deformable_convolution_kernel_bfyx_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/convolution/deformable_convolution_kernel_bfyx_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ctc_greedy_decoder/ctc_greedy_decoder_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ctc_greedy_decoder/ctc_greedy_decoder_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ctc_greedy_decoder/ctc_greedy_decoder_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ctc_greedy_decoder/ctc_greedy_decoder_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ctc_greedy_decoder/ctc_greedy_decoder_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ctc_greedy_decoder/ctc_greedy_decoder_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_partial_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_partial_sum.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/cum_sum/cum_sum_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_b_fs_zyx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_b_fs_zyx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_b_fs_zyx_fsv16_dw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_b_fs_zyx_fsv16_dw.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_bfyx_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_bfyx_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_imad_along_f_tile_bfx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_imad_along_f_tile_bfx.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_imad_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_imad_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/deconvolution/deconvolution_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_block2_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_block2_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/depth_to_space/depth_to_space_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/detection_output/detection_output_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/detection_output/detection_output_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/detection_output/detection_output_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/detection_output/detection_output_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dft/dft_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dft/dft_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dft/dft_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dft/dft_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_kv_cache.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_opt_kv_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/dynamic_quantize/dynamic_quantize_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_do/detection_output_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_do/detection_output_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_do/detection_output_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_do/detection_output_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_gpsi/generate_proposals_single_image_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_gpsi/generate_proposals_single_image_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_gpsi/generate_proposals_single_image_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_gpsi/generate_proposals_single_image_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_pgg/prior_grid_generator_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_pgg/prior_grid_generator_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_pgg/prior_grid_generator_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_pgg/prior_grid_generator_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_rfe/roi_feature_extractor_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_rfe/roi_feature_extractor_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_rfe/roi_feature_extractor_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_rfe/roi_feature_extractor_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_topkroi/topk_rois_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_topkroi/topk_rois_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_topkroi/topk_rois_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/ed_topkroi/topk_rois_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_blocked_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_blocked_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_fs_b_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_fs_b_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_mixed_byxf_and_fs_b_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_mixed_byxf_and_fs_b_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_vload8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eltwise/eltwise_kernel_vload8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/embedding_bag/embedding_bag_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/embedding_bag/embedding_bag_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/embedding_bag/embedding_bag_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/embedding_bag/embedding_bag_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/extract_image_patches/extract_image_patches_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/extract_image_patches/extract_image_patches_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/extract_image_patches/extract_image_patches_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/extract_image_patches/extract_image_patches_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/extract_image_patches/extract_image_patches_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/extract_image_patches/extract_image_patches_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eye/eye_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eye/eye_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eye/eye_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/eye/eye_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_block_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_block_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_io_gemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_io_gemm.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_io_input_spatial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_io_input_spatial.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_io_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_io_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_tiled.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_tiled.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_tiled_dyn_b.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bf_tiled_dyn_b.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bfyx_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bfyx_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_af8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_af8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_b1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bs_f_bsv16_b1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bs_f_bsv8_af8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_bs_f_bsv8_af8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_io_b8_f8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_io_b8_f8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_io_block.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_io_block.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_io_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_io_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_oi_b8_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_oi_b8_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_oi_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fb_oi_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fs_byx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_fs_byx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_gemv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_gemv.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_imad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_imad.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_mmad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_mmad.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_yxfb_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_kernel_yxfb_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_params.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/fully_connected/fully_connected_params.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_elements_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_elements_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_elements_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_elements_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_nd_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_nd_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_nd_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather/gather_nd_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather_tree/gather_tree_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather_tree/gather_tree_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather_tree/gather_tree_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather_tree/gather_tree_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather_tree/gather_tree_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gather_tree/gather_tree_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_mmad_int8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_mmad_int8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_mmad_int8_slm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_mmad_int8_slm.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_tiled_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/gemm/gemm_kernel_tiled_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/generate_proposals/generate_proposals_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/generate_proposals/generate_proposals_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/generate_proposals/generate_proposals_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/generate_proposals/generate_proposals_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_opt_bilinear_zeros.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_opt_bilinear_zeros.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grid_sample/grid_sample_kernel_selector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grn/grn_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grn/grn_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grn/grn_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grn/grn_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grn/grn_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/grn/grn_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/istft/istft_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/istft/istft_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/istft/istft_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/istft/istft_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/istft/istft_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/istft/istft_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_multiple_features.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_multiple_features.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_multiple_features_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_multiple_features_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_opt_b8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_opt_b8.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_across_channel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_within_channel_byxf_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_within_channel_byxf_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_within_channel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_within_channel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_within_channel_ref_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lrn/lrn_kernel_within_channel_ref_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_cell_and_seq_kernel_bfyx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_cell_and_seq_kernel_bfyx.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_cell_and_seq_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_cell_and_seq_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_cell_and_seq_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_cell_and_seq_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/lstm/lstm_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/matrix_nms/matrix_nms_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/matrix_nms/matrix_nms_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/matrix_nms/matrix_nms_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/matrix_nms/matrix_nms_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multiclass_nms/multiclass_nms_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multiclass_nms/multiclass_nms_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multiclass_nms/multiclass_nms_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multiclass_nms/multiclass_nms_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multinomial/multinomial_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multinomial/multinomial_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multinomial/multinomial_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/multinomial/multinomial_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_b_fs_yx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_b_fs_yx_fsv16.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_bfyx_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_bfyx_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_bs_fs_yx_bsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_bs_fs_yx_bsv32.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/mvn/mvn_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_max_suppression/non_max_suppression_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_max_suppression/non_max_suppression_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_max_suppression/non_max_suppression_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_max_suppression/non_max_suppression_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/count_nonzero_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/count_nonzero_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/count_nonzero_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/count_nonzero_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_kernel_group.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_kernel_group.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/non_zero/gather_nonzero_params.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_across_spatial_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_across_spatial_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_within_spatial_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/normalize/normalize_kernel_within_spatial_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/one_hot/one_hot_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/one_hot/one_hot_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/one_hot/one_hot_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/one_hot/one_hot_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/one_hot/one_hot_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/one_hot/one_hot_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_bfzyx_to_bfyxz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_bfzyx_to_bfyxz.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_f_y_axes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_f_y_axes.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_tile_8x8_4x4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_tile_8x8_4x4.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_tile_8x8_4x4_fsv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_tile_8x8_4x4_fsv.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_xy_swap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_kernel_xy_swap.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/permute/permute_params.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_b_fs_yx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_b_fs_yx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_b_fs_yx_fsv4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_b_fs_yx_fsv4.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_b_fs_zyx_fsv16_imad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_b_fs_zyx_fsv16_imad.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_bfyx_block_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_bfyx_block_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_bs_fs_yx_bsv16_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_bs_fs_yx_bsv16_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_bsv16_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_bsv16_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_byxf_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_byxf_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_byxf_padding_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_byxf_padding_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_fs_b_yx_fsv32.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_fs_b_yx_fsv32.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_int8_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_int8_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_gpu_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/pooling/pooling_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/prior_box/prior_box_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/prior_box/prior_box_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/prior_box/prior_box_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/prior_box/prior_box_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_params.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_scale_shift_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_scale_shift_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_scale_shift_vload8_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_scale_shift_vload8_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/quantize_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/quantize/qunatize_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/random_uniform/random_uniform_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/random_uniform/random_uniform_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/random_uniform/random_uniform_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/random_uniform/random_uniform_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/range/range_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/range/range_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/range/range_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/range/range_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_b_fs_yx_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_b_fs_yx_fsv16.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_simple_to_scalar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reduce/reduce_kernel_simple_to_scalar.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/region_yolo/region_yolo_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/region_yolo/region_yolo_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/region_yolo/region_yolo_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/region_yolo/region_yolo_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_biplanar_nv12.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_biplanar_nv12.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_from_winograd_2x3_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_from_winograd_2x3_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_b_fs_yx_fsv16_fsv32_to_bfyx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_b_fs_yx_fsv16_fsv32_to_bfyx.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_bfyx_to_blocked_format.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_bfyx_to_blocked_format.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_fast_b1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_fast_b1.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_fs_b_yx_fsv32_to_bfyx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_fs_b_yx_fsv32_to_bfyx.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_fsv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_fsv.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_to_yxfb_batched.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_kernel_to_yxfb_batched.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_to_winograd_2x3_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_to_winograd_2x3_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_image_fyx_b_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_image_fyx_b_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_image_winograd_6x3_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_image_winograd_6x3_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_int4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_int4.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_winograd_2x3_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_winograd_2x3_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_winograd_6x3_kernel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorder/reorder_weights_winograd_6x3_kernel.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorg_yolo/reorg_yolo_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorg_yolo/reorg_yolo_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorg_yolo/reorg_yolo_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reorg_yolo/reorg_yolo_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_bfyx_cubic_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_bfyx_cubic_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_onnx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_onnx.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_pil_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_pil_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/resample_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/resample/utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reshape/reshape_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reshape/reshape_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reshape/reshape_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reshape/reshape_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse/reverse_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse/reverse_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse/reverse_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse/reverse_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse_sequence/reverse_sequence_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse_sequence/reverse_sequence_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse_sequence/reverse_sequence_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/reverse_sequence/reverse_sequence_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_bfyx_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_bfyx_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/rms/rms_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_align/roi_align_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_align/roi_align_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_align/roi_align_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_align/roi_align_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_ps_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_ps_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roi_pooling/roi_pooling_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roll/roll_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roll/roll_kernel_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roll/roll_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/roll/roll_kernel_selector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_elements_update_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_elements_update_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_elements_update_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_elements_update_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_update_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_update_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_update_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/scatter_update/scatter_update_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/search_sorted/search_sorted_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/search_sorted/search_sorted_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/search_sorted/search_sorted_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/search_sorted/search_sorted_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/search_sorted/search_sorted_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/search_sorted/search_sorted_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/select/select_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/select/select_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/select/select_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/select/select_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/select/select_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/select/select_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/shuffle_channels/shuffle_channels_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/shuffle_channels/shuffle_channels_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/shuffle_channels/shuffle_channels_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/shuffle_channels/shuffle_channels_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/slice/slice_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/slice/slice_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/slice/slice_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/slice/slice_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_items_class_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_items_class_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_bf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_bf.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_fb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_fb.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_items_class_optimized.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_items_class_optimized.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/softmax/softmax_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_batch/space_to_batch_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_batch/space_to_batch_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_batch/space_to_batch_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_batch/space_to_batch_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_batch/space_to_batch_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_batch/space_to_batch_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_depth/space_to_depth_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_depth/space_to_depth_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_depth/space_to_depth_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/space_to_depth/space_to_depth_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/sparse_fill_empty_rows/sparse_fill_empty_rows_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/sparse_fill_empty_rows/sparse_fill_empty_rows_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/sparse_fill_empty_rows/sparse_fill_empty_rows_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/sparse_fill_empty_rows/sparse_fill_empty_rows_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/stft/stft_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/strided_slice/strided_slice_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/strided_slice/strided_slice_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/strided_slice/strided_slice_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/strided_slice/strided_slice_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_opt.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/swiglu/swiglu_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/tile/tile_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/tile/tile_kernel_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/tile/tile_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/tile/tile_kernel_selector.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels/unique/unique_kernel_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/unique/unique_kernel_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/unique/unique_kernel_selector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels/unique/unique_kernel_selector.hpp
    ${CMAKE_CURRENT_LIST_DIR}/micro_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/primitive_db.cpp
    ${CMAKE_CURRENT_LIST_DIR}/primitive_db.h
    ${CMAKE_CURRENT_LIST_DIR}/tensor_type.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tensor_type.h
    ${CMAKE_CURRENT_LIST_DIR}/weight_bias_kernel_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/weight_bias_kernel_base.h
    ${CMAKE_CURRENT_LIST_DIR}/weight_bias_params.cpp
    ${CMAKE_CURRENT_LIST_DIR}/weight_bias_params.h
)

# .cl kernel files are not compiled directly; they are inputs to the
# primitive_db_gen.py codegen step (tracked via DEPENDS for incremental builds).
set(GPU_KERNEL_SELECTOR_CL_KERNELS
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/activation_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/activation_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/adaptive_pooling_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/arg_max_min_axis.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/arg_max_min_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/arg_max_min_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/arg_max_min_topk_radix.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/batch_to_space_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/beam_table_update_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/border_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/broadcast_gpu_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/broadcast_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/bucketize_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/concatenation_gpu_b_fs_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/concatenation_gpu_blocked.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/concatenation_gpu_depth_bfyx_no_pitch.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/concatenation_gpu_fs_b_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/concatenation_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/concatenation_gpu_simple_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convert_color_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_1d_small_ic_gemm.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_b_fs_yx_fsv16_imad_1x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_b_fs_yx_fsv4_1x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_b_fs_yx_fsv4_dw.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_b_fs_yx_fsv4_int8.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_b_fs_yx_fsv_16_32_imad_dw.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_b_fs_zyx_fsv16_imad.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_1x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_1x1_hgemm_buf_16x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_1x1_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_depthwise_weights_lwg.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_direct_10_12_16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_f16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_f16_1x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_f16_depthwise.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_gemm_like_fp16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_gemm_like_fp32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_iyxo.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_os_iyx_osv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_os_iyx_osv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_to_bfyx_f16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_to_bs_fs_yx_bsv16_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_bfyx_to_fs_byx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_fs_byx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_fs_byx_fsv32_1x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_fs_byx_fsv32_depthwise.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_imad.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_imad_bs_fs_yx_bsv16_fsv16_1x1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_imad_bs_fs_yx_bsv16_fsv16_3x3.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_mmad_b_fs_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_mmad_b_fs_yx_fsv32_dw.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_mmad_bfyx_to_b_fs_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_mmad_bfyx_to_b_fs_yx_fsv4.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_winograd_2x3_s1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_winograd_2x3_s1_fused.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_winograd_6x3_s1_fused.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_yxfb_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_yxfb_yxio_b16_fp16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_yxfb_yxio_b16_fp32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_yxfb_yxio_b1_block_multiple_x_fp32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/convolution_gpu_yxfb_yxio_b8_fp32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/count_nonzero_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/ctc_greedy_decoder_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/cum_sum_partial_sum.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/cum_sum_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deconvolution_gpu_b_fs_zyx_fsv16_dw.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deconvolution_gpu_bfyx_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deconvolution_gpu_imad_along_f_tile_bfx.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deconvolution_gpu_imad_common.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deconvolution_gpu_imad_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deconvolution_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deformable_convolution_gpu_bfyx_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/deformable_convolution_gpu_bfyx_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/depth_to_space_block2_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/depth_to_space_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/detection_output_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/dft_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/dynamic_quantize_gpu_kv_cache.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/dynamic_quantize_gpu_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/dynamic_quantize_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/eltwise_blocked_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/eltwise_fs_b_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/eltwise_mixed_byxf_and_fs_b_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/eltwise_simple_vload8.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/embedding_bag_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/experimental_detectron_detection_output_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/experimental_detectron_generate_proposals_single_image_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/experimental_detectron_prior_grid_generator_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/experimental_detectron_roi_feature_extractor_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/experimental_detectron_topk_rois_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/extract_image_patches_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/eye_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_MMAD.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bf_io_gemm.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bf_io_input_spatial.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bf_io_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bf_tiled.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bf_tiled_dyn_b.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bfyx_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bs_f_bsv16_af8_vload.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bs_f_bsv16_b1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_bs_f_bsv8_af8_vload.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_fb_io_b8_f8_vload.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_fb_io_block_fp16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_fb_io_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_fb_oi_b8_fp32_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_fb_oi_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_fs_byx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_gemv.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_imad.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/fully_connected_gpu_yxfb_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gather_elements_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gather_nd_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gather_nonzero_group.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gather_nonzero_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gather_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gather_tree_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gemm_mmad_int8.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gemm_mmad_int8_slm.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gemm_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gemm_tiled_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gen9_common_conv_bwd_data.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gen9_common_conv_fwd_data_f16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/gen9_common_conv_fwd_data_f32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/generate_proposals_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/generic_eltwise_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/grid_sample_opt_bilinear_zeros.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/grid_sample_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/grn_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/acc_type.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/algorithm.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/arg_max_min_common.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/bf16_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/common.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/fetch_data.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/fetch_weights.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/generic_vector_ops.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/imad.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/int2_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/int4_convert.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/int4_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/sdpa_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/sub_group_block_read.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/sub_group_block_write.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/sub_group_shuffle.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/tile_ops.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/batch_headers/vec_typedefs.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/detection_output_common.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/f4_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/f8_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/fetch_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/fully_connected_gpu_bf_tiled_common.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/fully_connected_gpu_bf_tiled_dyn_b_core.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/gemm_common.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/image_data.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/mmad.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/reshape_dims.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/sub_group.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/include/unit_type.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/istft_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_gpu_across_channel_multiple_features.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_gpu_across_channel_multiple_features_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_gpu_across_channel_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_gpu_across_channel_yxfb_b8_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_gpu_within_channel.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_gpu_within_channel_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lrn_within_channel_byxf_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lstm_cell_and_seq_bfyx.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/lstm_cell_and_seq_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/matrix_nms_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/multiclass_nms_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/multinomial_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_b_fs_yx_bsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_b_fs_yx_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_b_fs_yx_fsv16_accumulate.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_b_fs_yx_fsv16_reduce.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_bfyx_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_ref_across_channels.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/mvn_gpu_ref_within_channels.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/non_max_suppression_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/normalize_gpu_across_spatial_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/normalize_gpu_within_spatial_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/one_hot_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/permute_bfzyx_to_bfyxz.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/permute_f_y_axes.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/permute_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/permute_tile_8x8_4x4.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/permute_tile_8x8_4x4_fsv.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/permute_xy_swap.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_b_fs_yx_fsv4.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_b_fs_zyx_fsv16_imad.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_bfyx_block_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_blocked.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_bs_fs_yx_bsv16_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_bsv16_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_byxf_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_byxf_padding_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_fs_b_yx_fsv32.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_int8_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/pooling_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/prior_box_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/quantize_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/quantize_gpu_scale_shift_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/quantize_gpu_scale_shift_vload8_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/random_uniform_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/range_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reduce_gpu_b_fs_yx_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reduce_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reduce_simple_to_scalar.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/region_yolo_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_biplanar_nv12.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_data.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_data_b_fs_yx_fsv16_fsv32_to_bfyx.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_data_bfyx_to_blocked_format.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_data_fast_b1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_data_fsv.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_data_to_yxfb_batched.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_from_winograd_2x3_s1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_fs_b_yx_fsv32_to_bfyx.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_to_winograd_2x3_s1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights_image_2d_c4_fyx_b.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights_image_winograd_6x3_s1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights_int4.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights_winograd_2x3_s1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorder_weights_winograd_6x3_s1.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reorg_yolo_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/resample_bfyx_cubic_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/resample_onnx.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/resample_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/resample_pil_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/resample_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reshape_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reverse_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/reverse_sequence_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/rms_gpu_bfyx_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/rms_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/roi_align_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/roi_pooling_ps_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/roi_pooling_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/roll_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/scatter_elements_update_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/scatter_update_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/search_sorted_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/select_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/shuffle_channels_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/slice_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/softmax_gpu_bf.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/softmax_gpu_fb.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/softmax_gpu_items_class_optimized.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/softmax_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/space_to_batch_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/space_to_depth_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/sparse_fill_empty_rows_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/stft_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/stft_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/strided_slice_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/swiglu_gpu_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/swiglu_gpu_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/tile_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/unique_count_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/cl_kernels/unique_gather_ref.cl
)
