# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(REFERENCE_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/src/op/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/convert_x86_intrinsics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/experimental_detectron_proposal_single_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/experimental_detectron_roi_feature_extractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/fake_convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/fft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/function.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/generate_proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/group_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/group_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/inverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/irdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/rdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/utils/fft_common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/utils/nms_common.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/utils/paged_cache_manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/op/utils/rounding_guard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/coordinate_index.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/coordinate_range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/coordinate_transform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/jit_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/philox_converter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/philox_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/src/utils/registers_pool.cpp
)

set(REFERENCE_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/abs.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/acos.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/acosh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/adaptive_avg_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/adaptive_max_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/adaptive_rkv_diversity.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/add.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/and.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/asin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/asinh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/atan.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/atan2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/atanh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/autobroadcast_binop.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/avg_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/batch_norm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/binary_convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bitwise_and.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bitwise_left_shift.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bitwise_not.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bitwise_or.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bitwise_right_shift.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bitwise_xor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/broadcast.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/bucketize.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/ceiling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/clamp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/col2im.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/concat.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/constant.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/convert.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/convert_color_nv12.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/convolution_backprop_data.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/copy.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/cos.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/cosh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/ctc_greedy_decoder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/ctc_greedy_decoder_seq_len.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/ctc_loss.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/cum_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/deformable_convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/deformable_psroi_pooling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/depth_to_space.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/detection_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/divide.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/einsum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/elu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/embedding_bag_offsets.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/embedding_bag_packed.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/embedding_segments_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/equal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/erf.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/erfinv.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/exp.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/experimental_detectron_detection_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/experimental_detectron_prior_grid_generator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/experimental_detectron_proposal_single_image.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/experimental_detectron_roi_feature_extractor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/experimental_detectron_topk_rois.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/extract_image_patches.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/eye.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/fake_convert.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/fake_quantize.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/fft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/floor.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/floor_mod.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/function.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gated_delta_net.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gather.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gather_elements.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gather_nd.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gather_tree.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gelu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/generate_proposal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/greater.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/greater_eq.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/grid_sample.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/grn.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/group_convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/group_convolution_backprop_data.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/group_normalization.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/grouped_matmul.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/gru_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/hard_sigmoid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/hsigmoid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/hswish.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/identity.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/if.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/interpolate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/interpolate_pil.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/inverse.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/irdft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/is_finite.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/is_inf.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/is_nan.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/istft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/less.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/less_eq.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/log.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/log_softmax.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/logical_not.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/logical_reduction.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/loop.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/lrn.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/lstm_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/matmul.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/matrix_nms.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/max_pool.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/maximum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/minimum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/mish.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/mod.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/multiclass_nms.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/multinomial.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/multiply.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/mvn.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/negate.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/nms_rotated.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/nms_rotated_util.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/non_max_suppression.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/non_zero.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/normalize_l2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/not_equal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/one_hot.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/or.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/pad.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/paged_attention.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/power.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/prelu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/prior_box.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/prior_box_clustered.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/proposal.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/psroi_pooling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/random_uniform.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/range.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/rdft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_l1.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_l2.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_max.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_mean.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_min.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_prod.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reduce_sum.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/region_yolo.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/relu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reorg_yolo.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reshape.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/result.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reverse.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/reverse_sequence.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/rms_norm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/rnn_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/roi_align.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/roi_pooling.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/roll.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/round.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/rounding_guard.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/scaled_dot_product_attention.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/scatter_elements_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/scatter_nd_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/scatter_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/search_sorted.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/segment_max.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/select.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/selu.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sequences.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/shape_of.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/shuffle_channels.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sigmoid.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sign.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sin.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sinh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/slice.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/slice_scatter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/softmax.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/softplus.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/softsign.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/space_to_depth.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sparse_fill_empty_rows.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/split.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/sqrt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/squared_difference.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/stft.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/strided_slice.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/string_tensor_pack.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/string_tensor_unpack.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/subtract.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/swish.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/tan.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/tanh.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/tensor_iterator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/tile.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/topk.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/transpose.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/unique.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/convert_util.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/convert_x86_intrinsics.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/coordinate_index.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/coordinate_range.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/coordinate_transform.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/fft_common.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/jit_generator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/nms_common.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/paged_cache_manager.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/paged_cache_manager_helper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/philox_converter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/philox_generator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/include/openvino/reference/utils/registers_pool.hpp
)
