# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(OV_CORE_TESTS_TYPE_PROP_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/abs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/acos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/acosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/adaptive_avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/adaptive_max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/asin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/asinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/atan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/atanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/augru_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/augru_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/binary_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/binary_elementwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bitwise_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bitwise_left_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bitwise_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bitwise_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bitwise_right_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bitwise_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ceiling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/clamp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/constant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert_color_i420.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert_color_nv12.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert_promote_types.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cosh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_greedy_decoder_seq_len.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/deformable_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/deformable_convolution_opset8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/deformable_psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/divide.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dyn_reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/elu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embedding_segments_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embeddingbag_offsets.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embeddingbag_offsetssum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embeddingbag_packed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embeddingbag_packedsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/erf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/erfinv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/exp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_roi_feature_extractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_topkrois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/extractimagepatches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fake_convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fake_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fft_base_complex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/floor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/floor_mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/framework_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul_compressed_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grouped_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gru_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gru_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/hard_sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/hsigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/hswish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/inverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/irdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/is_finite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/is_inf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/is_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/logical_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/logical_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/logical_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/logical_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/loop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lstm_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/maximum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/minimum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multiply.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/negative.cpp
    ${CMAKE_CURRENT_LIST_DIR}/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/non_zero.cpp
    ${CMAKE_CURRENT_LIST_DIR}/normalize_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_causal_conv1d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/parameter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/power.cpp
    ${CMAKE_CURRENT_LIST_DIR}/prelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/prior_box_clustered.cpp
    ${CMAKE_CURRENT_LIST_DIR}/proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/read_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_l1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_logical_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_logical_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_mean.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_min.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_prod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/result.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rms_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rnn_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rnn_cell_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rnn_seq_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rnn_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/round.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scaled_dot_product_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_elements_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/search_sorted.cpp
    ${CMAKE_CURRENT_LIST_DIR}/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/selu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_of.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sinh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softplus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softsign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sqrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/squared_difference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/squeeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/string_tensor_pack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/string_tensor_unpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/subtract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/swish.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/top_k.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/unary_elementwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/unsqueeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/variadic_split.cpp
)
