# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(GPU_OCL_V2_IMPL_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/col2im.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_loss.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gated_delta_net_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gated_delta_net_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gather_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gather_matmul_gen_micro.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gather_matmul_gen_micro.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gather_matmul_impl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_batched_gemm_gen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_batched_gemm_gen.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_gather_gen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_gather_gen.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_scatter_gen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_scatter_gen.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_sort_gen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul/gathermatmul_sort_gen.hpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_bfyx_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_bfyx_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_fsv16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_fsv16.hpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/lora.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lora.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/expert_weight_provider.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/expert_weight_providers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/expert_weight_providers.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/lru_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/lru_cache.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_3gemm_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_3gemm_gen_micro.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_3gemm_gen_micro.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_3gemm_swiglu_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_3gemm_swiglu_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_gather.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_gemm_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_gemm_gen_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_mask_gen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_mask_gen.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_otd_runtime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_otd_runtime.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_router_fused_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_router_fused_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_scatter_reduction_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_scatter_reduction_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_scatter_reduction_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_scatter_reduction_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/moe/moe_scatter_reduction_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_reorder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_causal_conv1d_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_causal_conv1d_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_gated_delta_net.hpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/paged_selective_ssm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/primitive_ocl_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/rope_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rope_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/paged_attention_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/paged_attention_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_gen_micro.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_gen_micro.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_gen_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_gen_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_opt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_opt.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_ref.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_ref.hpp
    ${CMAKE_CURRENT_LIST_DIR}/sdpa/sdpa_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/segment_max.hpp
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_jit_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/slice_scatter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/fused_ops_jitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/fused_ops_jitter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/jitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/jitter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/kernel_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/kernel_generator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/kernels_db.cpp
    ${CMAKE_CURRENT_LIST_DIR}/utils/kernels_db.hpp
)

# .cl kernel files are not compiled directly; they are inputs to the ocl
# codegen step (tracked via DEPENDS for incremental builds).
set(GPU_OCL_V2_KERNEL_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/col2im.cl
    ${CMAKE_CURRENT_LIST_DIR}/ctc_loss.cl
    ${CMAKE_CURRENT_LIST_DIR}/expert_gemm_common.cl
    ${CMAKE_CURRENT_LIST_DIR}/expert_gemm_compute.cl
    ${CMAKE_CURRENT_LIST_DIR}/gated_delta_net_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul.cl
    ${CMAKE_CURRENT_LIST_DIR}/gather_matmul_batched.cl
    ${CMAKE_CURRENT_LIST_DIR}/gathermatmul_gather.cl
    ${CMAKE_CURRENT_LIST_DIR}/gathermatmul_scatter.cl
    ${CMAKE_CURRENT_LIST_DIR}/gathermatmul_sort.cl
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_bfyx_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_fsv16.cl
    ${CMAKE_CURRENT_LIST_DIR}/group_normalization_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/lora_horizontal_fused.cl
    ${CMAKE_CURRENT_LIST_DIR}/lora_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/lora_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_3gemm_swiglu_fuse.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_3gemm_swiglu_mlp.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_gather_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_gemm.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_mask_gen.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_router_fused.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_scatter_reduction_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_scatter_reduction_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/moe_scatter_reduction_row_lut.cl
    ${CMAKE_CURRENT_LIST_DIR}/pa_adaptive_rkv_diversity_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_cache_reorder_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_cache_rotate_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_cache_update_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_attention_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_causal_conv1d_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_gated_delta_net_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_gated_delta_net_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_selective_ssm_jit_precompute.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_selective_ssm_large_state.cl
    ${CMAKE_CURRENT_LIST_DIR}/paged_selective_ssm_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/rope_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update_copy.cl
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/scatter_nd_update_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/sdpa_micro.cl
    ${CMAKE_CURRENT_LIST_DIR}/sdpa_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/sdpa_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/segment_max_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/segment_max_ref.cl
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_jit.cl
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_large_state.cl
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_recurrence.cl
    ${CMAKE_CURRENT_LIST_DIR}/selective_ssm_type_utils.cl
    ${CMAKE_CURRENT_LIST_DIR}/slice_scatter_opt.cl
    ${CMAKE_CURRENT_LIST_DIR}/slice_scatter_ref.cl
)
