name: 'Find and install OpenVINO Python wheels'
description: 'Finds the OpenVINO Python wheels (core, dev and tokenizers) suitable for the "python3" executable and installs them'
inputs:
  wheels-dir-path:
    description: 'Path to the directory in which wheels are located'
    required: true
  wheels-to-install:
    description: 'List of wheel names to install in the form of "openvino openvino-dev openvino-tokenizers"'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install OpenVINO Python wheels (Windows)
      shell: pwsh
      if: runner.os == 'Windows'
      run: python3 -m pip install ${{ inputs.wheels-to-install }} --find-links ${{ inputs.wheels-dir-path }}

    - name: Install OpenVINO Python wheels (Linux and macOS)
      shell: bash
      if: runner.os != 'Windows'
      run: python3 -m pip install ${{ inputs.wheels-to-install }} --find-links ${{ inputs.wheels-dir-path }}
