set(SOURCES
    include/async_infer_request.hpp
    include/backends_registry.hpp
    include/compiled_model.hpp
    include/compiled_model_property_manager.hpp
    include/executor.hpp
    include/metadata.hpp
    include/metrics.hpp
    include/plugin.hpp
    include/plugin_property_manager.hpp
    include/property_registration.hpp
    include/remote_context.hpp
    include/transformations.hpp
    src/async_infer_request.cpp
    src/backends_registry.cpp
    src/compiled_model.cpp
    src/compiled_model_property_manager.cpp
    src/executor.cpp
    src/extension.cpp
    src/metadata.cpp
    src/metrics.cpp
    src/plugin.cpp
    src/plugin_property_manager.cpp
    src/remote_context.cpp
    src/transformations.cpp
)

set(NPUW_SOURCES
    npuw/accuracy/comparator.cpp
    npuw/accuracy/comparator.hpp
    npuw/attention.cpp
    npuw/attention.hpp
    npuw/attn/attn_subgraph.cpp
    npuw/attn/attn_subgraph.hpp
    npuw/base_sync_infer_request.cpp
    npuw/base_sync_infer_request.hpp
    npuw/common.hpp
    npuw/compiled_model.cpp
    npuw/compiled_model.hpp
    npuw/embedding/embedding_infer_request.cpp
    npuw/embedding/embedding_infer_request.hpp
    npuw/embedding/prepare_embedding_model.cpp
    npuw/embedding/prepare_embedding_model.hpp
    npuw/embedding/redirect_new_kv_to_output.cpp
    npuw/embedding/redirect_new_kv_to_output.hpp
    npuw/embedding/remove_empty_kv_inputs.cpp
    npuw/embedding/remove_empty_kv_inputs.hpp
    npuw/gqa_compiled_model.cpp
    npuw/gqa_compiled_model.hpp
    npuw/host_flash_attention.cpp
    npuw/host_flash_attention.hpp
    npuw/infer_request_utils.cpp
    npuw/infer_request_utils.hpp
    npuw/just_sync_infer_request.cpp
    npuw/just_sync_infer_request.hpp
    npuw/kv_cache_block_manager.cpp
    npuw/kv_cache_block_manager.hpp
    npuw/lazy_tensor.cpp
    npuw/lazy_tensor.hpp
    npuw/llm_block_kvcache_strategy.cpp
    npuw/llm_block_kvcache_strategy.hpp
    npuw/llm_compiled_model.cpp
    npuw/llm_compiled_model.hpp
    npuw/llm_compiled_model_utils.cpp
    npuw/llm_compiled_model_utils.hpp
    npuw/llm_continuous_kvcache_strategy.cpp
    npuw/llm_continuous_kvcache_strategy.hpp
    npuw/llm_eagle3_extension.cpp
    npuw/llm_eagle3_extension.hpp
    npuw/llm_infer_base_request.cpp
    npuw/llm_infer_base_request.hpp
    npuw/llm_infer_request.cpp
    npuw/llm_infer_request.hpp
    npuw/llm_kvcache_strategy.hpp
    npuw/llm_lora_states.hpp
    npuw/llm_prefix_caching.cpp
    npuw/llm_prefix_caching.hpp
    npuw/llm_stored_tokens_state.hpp
    npuw/logging.cpp
    npuw/logging.hpp
    npuw/moe/moe_config.hpp
    npuw/moe/moe_executor.cpp
    npuw/moe/moe_executor.hpp
    npuw/moe/moe_infer_utils.cpp
    npuw/moe/moe_infer_utils.hpp
    npuw/moe/moe_resources.cpp
    npuw/moe/moe_resources.hpp
    npuw/moe/moe_subgraph.cpp
    npuw/moe/moe_subgraph.hpp
    npuw/moe/moe_types.hpp
    npuw/moe_transformations/apply_moe_device_routed_transforms.cpp
    npuw/moe_transformations/apply_moe_device_routed_transforms.hpp
    npuw/moe_transformations/device_routed_moe_transform.cpp
    npuw/moe_transformations/device_routed_moe_transform.hpp
    npuw/moe_transformations/gather_to_2d_gather.cpp
    npuw/moe_transformations/gather_to_2d_gather.hpp
    npuw/moe_transformations/moe_transformation.cpp
    npuw/moe_transformations/moe_transformation.hpp
    npuw/moe_transformations/moe_transformation_utils.hpp
    npuw/moe_transformations/moe_unroll_patterns.cpp
    npuw/moe_transformations/moe_unroll_patterns.hpp
    npuw/npuw_transformations/add_position_ids_param.cpp
    npuw/npuw_transformations/add_position_ids_param.hpp
    npuw/npuw_transformations/collapse_unqdq.cpp
    npuw/npuw_transformations/collapse_unqdq.hpp
    npuw/npuw_transformations/convert_kvcache_to_precision.cpp
    npuw/npuw_transformations/convert_kvcache_to_precision.hpp
    npuw/npuw_transformations/conv_to_matmul.cpp
    npuw/npuw_transformations/conv_to_matmul.hpp
    npuw/npuw_transformations/decompose_gqa.cpp
    npuw/npuw_transformations/decompose_gqa.hpp
    npuw/npuw_transformations/drop_zp_subtract.cpp
    npuw/npuw_transformations/drop_zp_subtract.hpp
    npuw/npuw_transformations/kv_axes_position.hpp
    npuw/npuw_transformations/kv_cache_compressed.cpp
    npuw/npuw_transformations/kv_cache_compressed.hpp
    npuw/npuw_transformations/lora_stateful_to_stateless.cpp
    npuw/npuw_transformations/lora_stateful_to_stateless.hpp
    npuw/npuw_transformations/optimize_value_tensors.cpp
    npuw/npuw_transformations/optimize_value_tensors.hpp
    npuw/npuw_transformations/patch_sliding_window_mask.cpp
    npuw/npuw_transformations/patch_sliding_window_mask.hpp
    npuw/npuw_transformations/replace_deepstack_scatter_with_add.cpp
    npuw/npuw_transformations/replace_deepstack_scatter_with_add.hpp
    npuw/npuw_transformations/reshape_sliced_head_to_static.cpp
    npuw/npuw_transformations/reshape_sliced_head_to_static.hpp
    npuw/npuw_transformations/reshape_to_static.cpp
    npuw/npuw_transformations/reshape_to_static.hpp
    npuw/npuw_transformations/slice_out_embeds.cpp
    npuw/npuw_transformations/slice_out_embeds.hpp
    npuw/npuw_transformations/sliding_window_mask.cpp
    npuw/npuw_transformations/sliding_window_mask.hpp
    npuw/npuw_transformations/split_kvcache_into_blocks.cpp
    npuw/npuw_transformations/split_kvcache_into_blocks.hpp
    npuw/npuw_transformations/untangle_dq_scale.cpp
    npuw/npuw_transformations/untangle_dq_scale.hpp
    npuw/orc.cpp
    npuw/orc.hpp
    npuw/orc/schema_npuw.hpp
    npuw/partitioning/online/compiler.cpp
    npuw/partitioning/online/compiler.hpp
    npuw/partitioning/online/graph.cpp
    npuw/partitioning/online/graph.hpp
    npuw/partitioning/online/group.cpp
    npuw/partitioning/online/group.hpp
    npuw/partitioning/online/repeated.cpp
    npuw/partitioning/online/repeated.hpp
    npuw/partitioning/online/snapshot.cpp
    npuw/partitioning/online/snapshot.hpp
    npuw/partitioning/online/utils/attribute_visitor.hpp
    npuw/partitioning/online/utils/utils.cpp
    npuw/partitioning/online/utils/utils.hpp
    npuw/partitioning/partitioning.cpp
    npuw/partitioning/partitioning.hpp
    npuw/partitioning/patterns/avoid.cpp
    npuw/partitioning/patterns/avoid.hpp
    npuw/partitioning/patterns/compute.cpp
    npuw/partitioning/patterns/compute.hpp
    npuw/partitioning/patterns/dcoff.cpp
    npuw/partitioning/patterns/dcoff.hpp
    npuw/partitioning/patterns/fold_const.cpp
    npuw/partitioning/patterns/fold_const.hpp
    npuw/partitioning/patterns/gqa.cpp
    npuw/partitioning/patterns/gqa.hpp
    npuw/partitioning/patterns/moe.cpp
    npuw/partitioning/patterns/moe.hpp
    npuw/partitioning/patterns/opt.cpp
    npuw/partitioning/patterns/opt.hpp
    npuw/partitioning/patterns/pre_compute.cpp
    npuw/partitioning/patterns/pre_compute.hpp
    npuw/partitioning/patterns/sdpa.cpp
    npuw/partitioning/patterns/sdpa.hpp
    npuw/partitioning/traits.cpp
    npuw/partitioning/traits.hpp
    npuw/perf.cpp
    npuw/perf.hpp
    npuw/pipelines/kokoro/kokoro_compiled_model.cpp
    npuw/pipelines/kokoro/kokoro_compiled_model.hpp
    npuw/pipelines/kokoro/kokoro_infer_request.cpp
    npuw/pipelines/kokoro/kokoro_infer_request.hpp
    npuw/pipelines/kokoro/kokoro_model_transforms.cpp
    npuw/pipelines/kokoro/kokoro_model_transforms.hpp
    npuw/pipelines/kokoro/kokoro_split.cpp
    npuw/pipelines/kokoro/kokoro_split.hpp
    npuw/pipelines/kokoro/kokoro_utils.cpp
    npuw/pipelines/kokoro/kokoro_utils.hpp
    npuw/pyramid_attention.cpp
    npuw/pyramid_attention.hpp
    npuw/serialization.cpp
    npuw/serialization.hpp
    npuw/spatial.cpp
    npuw/spatial.hpp
    npuw/unfold_sync_infer_request.cpp
    npuw/unfold_sync_infer_request.hpp
    npuw/util.cpp
    npuw/util.hpp
    npuw/util_xarch.cpp
    npuw/util_xarch.hpp
    npuw/v1/elements/accuracy_checked.cpp
    npuw/v1/elements/accuracy_checked.hpp
    npuw/v1/elements/failsafe.cpp
    npuw/v1/elements/failsafe.hpp
    npuw/v1/subgraph_pipeline.hpp
    npuw/weights_bank.cpp
    npuw/weights_bank.hpp
    npuw/whisper/prepare_whisper_model.cpp
    npuw/whisper/prepare_whisper_model.hpp
    npuw/whisper/whisper_infer_request.cpp
    npuw/whisper/whisper_infer_request.hpp
)
