// Copyright (C) 2018-2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#if !ELTWISE_DENSE
#extension GL_EXT_shader_8bit_storage : require
#endif
#extension GL_GOOGLE_include_directive : require

#ifndef ELTWISE_DENSE_PUSH_CONSTANTS
#define ELTWISE_DENSE_PUSH_CONSTANTS 0
#endif

#ifndef ELTWISE_F32_VECTOR_WIDTH
#define ELTWISE_F32_VECTOR_WIDTH 0
#endif

#ifndef ELTWISE_F32_NO_TAIL
#define ELTWISE_F32_NO_TAIL 0
#endif

#ifndef ELTWISE_PACKED_VECTOR_WIDTH
#define ELTWISE_PACKED_VECTOR_WIDTH 0
#endif

#ifndef ELTWISE_PACKED_FLOAT16
#define ELTWISE_PACKED_FLOAT16 0
#endif

#ifndef ELTWISE_FAST_BROADCAST
#define ELTWISE_FAST_BROADCAST 0
#endif

#ifndef ELTWISE_FUSED_CHAIN
#define ELTWISE_FUSED_CHAIN 0
#endif

#ifndef ELTWISE_FUSED_BROADCAST
#define ELTWISE_FUSED_BROADCAST 0
#endif

#ifndef ELTWISE_FUSED_POST_OP
#define ELTWISE_FUSED_POST_OP 0
#endif

#ifndef ELTWISE_FIXED_FUSED_CHAIN_LENGTH
#define ELTWISE_FIXED_FUSED_CHAIN_LENGTH 0
#endif

#if ELTWISE_RESTRICT_OUTPUT && !ELTWISE_DENSE
#error ELTWISE_RESTRICT_OUTPUT requires the single-output dense ABI
#endif

#if ELTWISE_RESTRICT_OUTPUT
#define ELTWISE_OUTPUT_ALIAS_QUALIFIER restrict
#else
#define ELTWISE_OUTPUT_ALIAS_QUALIFIER
#endif
