"""
openvino module namespace, exposing factory functions for all ops and other classes.
"""
from __future__ import annotations
from openvino._ov_api import AsyncInferQueue
from openvino._ov_api import CompiledModel
from openvino._ov_api import Core
from openvino._ov_api import InferRequest
from openvino._ov_api import Model
from openvino._ov_api import compile_model
from openvino._pyopenvino import AxisSet
from openvino._pyopenvino import AxisVector
from openvino._pyopenvino import ConstOutput
from openvino._pyopenvino import Coordinate
from openvino._pyopenvino import CoordinateDiff
from openvino._pyopenvino import Dimension
from openvino._pyopenvino import DiscreteTypeInfo
from openvino._pyopenvino import Extension
from openvino._pyopenvino import Input
from openvino._pyopenvino import Layout
from openvino._pyopenvino import Node
from openvino._pyopenvino import OVAny
from openvino._pyopenvino import Output
from openvino._pyopenvino import PartialShape
from openvino._pyopenvino import ProfilingInfo
from openvino._pyopenvino import RTMap
from openvino._pyopenvino import Shape
from openvino._pyopenvino import Strides
from openvino._pyopenvino import Symbol
from openvino._pyopenvino import Tensor
from openvino._pyopenvino import Type
from openvino._pyopenvino import Version
from openvino._pyopenvino import get_batch
from openvino._pyopenvino import get_version
from openvino._pyopenvino import layout_helpers
from openvino._pyopenvino import save_model
from openvino._pyopenvino import serialize
from openvino._pyopenvino import set_batch
from openvino._pyopenvino import shutdown
from openvino.package_utils import deprecated
from openvino.utils.data_helpers.wrappers import tensor_from_file
import warnings as warnings
from . import exceptions
from . import ie_api
from . import op
from . import opset1
from . import opset10
from . import opset11
from . import opset12
from . import opset13
from . import opset14
from . import opset15
from . import opset16
from . import opset2
from . import opset3
from . import opset4
from . import opset5
from . import opset6
from . import opset7
from . import opset8
from . import opset9
from . import opset_utils
from . import properties
from . import utils
__all__ = ['AsyncInferQueue', 'AxisSet', 'AxisVector', 'CompiledModel', 'ConstOutput', 'Coordinate', 'CoordinateDiff', 'Core', 'Dimension', 'DiscreteTypeInfo', 'Extension', 'InferRequest', 'Input', 'Layout', 'Model', 'Node', 'OVAny', 'Output', 'PartialShape', 'ProfilingInfo', 'RTMap', 'Shape', 'Strides', 'Symbol', 'Tensor', 'Type', 'Version', 'compile_model', 'deprecated', 'exceptions', 'get_batch', 'get_version', 'ie_api', 'layout_helpers', 'op', 'opset1', 'opset10', 'opset11', 'opset12', 'opset13', 'opset14', 'opset15', 'opset16', 'opset2', 'opset3', 'opset4', 'opset5', 'opset6', 'opset7', 'opset8', 'opset9', 'opset_utils', 'properties', 'save_model', 'serialize', 'set_batch', 'shutdown', 'tensor_from_file', 'utils', 'warnings']
__version__: str = '2025.1.0-18196-f58124288d5-pyi_files'
__warningregistry__: dict = {'version': 5, ('The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.', DeprecationWarning, 10): True, ('The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.', DeprecationWarning): True}
