# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(CPU_UNIT_TESTS_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/caseless_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpu_tensor_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpu_tensor_test_ext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dnnl_memory_desc_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dnnl_memory_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dnnl_zero_dims_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pa_kv_reorder_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rt_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/dummy_node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/enforce_inference_precision_bf16_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/inplace_resolve_io.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/memory_state.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/merge_transpose_reorder_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/graph/resolve_edge_conflicts_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/memory_desc/empty_memory_desc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/nodes/reorder_node_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/common/cpu_runtime_configurator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/common/enforce_precision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/common/mul_add_to_fma.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/cpu_pinning_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/enable_ht_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/model_prefer_threads.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/scheduling_core_type_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/streams_e2e_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/streams_info_table_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/streams_rank_table_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/streams_info/update_proc_table_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_gather_matmul_to_compressed_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_matmul_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/convert_to_leaky_relu_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/disable_bf16_comp_cumsum_sin_gen_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/move_fc_reshape_to_weights.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/optimize_sequence_transposes_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/permute_slice_n_interpolation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/readvalue_subgraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/state_concat_sdpa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/swap_convert_transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/adaptive_avg_pool_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/adaptive_max_pool_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/assign_shape_inference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/augru_cell_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/augru_sequence_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/avg_pool_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/batch_norm_inference_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/batch_to_space_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/bec_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/bel_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/binary_convolution_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/binary_elementwise_arithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/broadcast_shape_inference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/bucketize_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/col2im_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/compare_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/concat_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/convolution_backprop_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/ctc_greedy_decoder_seq_len_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/ctc_greedy_decoder_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/ctc_loss_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/deformable_convolution_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/deformable_psroi_pooling_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/depth_to_space_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/detection_output_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/einsum_shape_infernce_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/elementwises.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/embedding_segments_sum_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/embeddingbag_offsets_sum_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/embeddingbag_packed_sum_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/experimental_detectron_detection_output_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/experimental_detectron_generate_proposal_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/experimental_detectron_prior_grid_generator_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/experimental_detectron_roi_feature_extractor_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/experimental_detectron_topkrois_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/extract_image_patches_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/eye_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/fft_base_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/gather_elements_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/gather_nd_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/gather_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/gather_tree_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/glu_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/grid_sample_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/group_convolution_backprop_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/group_convolution_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/gru_cell_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/gru_sequence_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/i420_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/identity_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/interpolate_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/inverse_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/istft_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/logical_not_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/lstm_cell_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/lstm_seq_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/make_shape_inference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/matmul_shape_inference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/matrix_nms_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/max_pool_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/multinomial_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/nms_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/nv12_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/one_hot_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/pad_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/paged_selective_ssm_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/prior_box_clustered_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/prior_box_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/proposal_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/psroi_pooling_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/random_uniform_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/range_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/read_value_shape_inference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/reduce_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/region_yolo_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/reorg_yolo_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/reshape_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/reverse_sequence_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/reverse_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/rms_norm_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/rnn_cell_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/rnn_seq_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/roi_align_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/roi_pooling_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/roll_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/scaled_dot_product_attention_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/scatter_elements_update_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/scatter_nd_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/scatter_update_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/search_sorted_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/segment_max_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/select_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/selective_ssm_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/shape_node_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/shuffle_channels_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/slice_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/space_to_batch_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/space_to_depth_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/sparse_fill_empty_rows_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/split_shape_inference_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/squeeze_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/static_shape_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/stft_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/strided_slice_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/string_tensor_pack_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/string_tensor_unpack_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/tile_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/topk_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/transpose_shape_infernece_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/unsqueeze_shape_inference_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/utils.hpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/variadic_split_shape_inference_tests.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/adaptive_avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/adaptive_max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/binary_elementwise_arithmetic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/color_covert_shape_inference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/custom_shape_infer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/custom_shape_infer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/elementwises.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/fullconnect.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/ngram.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/prior_box_clustered.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/scaled_attn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/shape_node.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/squeeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shape_inference_test/custom_shape_infer/unsqueeze.cpp
)

set(CPU_UNIT_TESTS_X64_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/brgemm_executor_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/jit_kernel_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/registers_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softmax_kernel_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xattention_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/nodes/eltwise_node_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/x64/brgemm_supported_precisions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/x64/fake_quantize_tokenization_test.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/x64/fuse_brgemm_cpu_postops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/x64/snipptes_mark_skipped.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/x64/lowered/brgemm_blocking.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/x64/lowered/buffer_allocation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/x64/convert_matmul_test_3d_weight.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/x64/convert_to_interaction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/x64/qkv_proj_fusion_test.cpp
)

set(CPU_UNIT_TESTS_ARM_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/align_unsupported_lp_conv_fq_precision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_conv_bias.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_fc_bias.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_group_conv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_group_conv1d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_matmul_test_3d_weight.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_reduce_multi_axis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/convert_reduce_no_keep_dims.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/deconv_1d_decomposition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/transformations/arm/grid_sample_decomposition.cpp
)

set(CPU_UNIT_TESTS_AARCH64_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/aarch64/snipptes_mark_skipped.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/aarch64/lowered/adjust_gemm_copy_b_loop_ports.cpp
    ${CMAKE_CURRENT_LIST_DIR}/snippets_transformations/aarch64/lowered/gemm_blocking.cpp
)

set(CPU_UNIT_TESTS_MLAS_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/gemm_api_test.cpp
)

set(CPU_UNIT_TESTS_CHECK_SOURCES_EXCLUDE_FILES)
if(ARM OR AARCH64)
    list(APPEND CPU_UNIT_TESTS_SRCS ${CPU_UNIT_TESTS_ARM_SRCS})
else()
    list(APPEND CPU_UNIT_TESTS_CHECK_SOURCES_EXCLUDE_FILES ${CPU_UNIT_TESTS_ARM_SRCS})
endif()

if(AARCH64)
    list(APPEND CPU_UNIT_TESTS_SRCS ${CPU_UNIT_TESTS_AARCH64_SRCS})
else()
    list(APPEND CPU_UNIT_TESTS_CHECK_SOURCES_EXCLUDE_FILES ${CPU_UNIT_TESTS_AARCH64_SRCS})
endif()

if(X86_64)
    list(APPEND CPU_UNIT_TESTS_SRCS ${CPU_UNIT_TESTS_X64_SRCS})
else()
    list(APPEND CPU_UNIT_TESTS_CHECK_SOURCES_EXCLUDE_FILES ${CPU_UNIT_TESTS_X64_SRCS})
endif()

if(ENABLE_MLAS_FOR_CPU)
    list(APPEND CPU_UNIT_TESTS_SRCS ${CPU_UNIT_TESTS_MLAS_SRCS})
else()
    list(APPEND CPU_UNIT_TESTS_CHECK_SOURCES_EXCLUDE_FILES ${CPU_UNIT_TESTS_MLAS_SRCS})
endif()
