# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(OPS_SRC
    ${CMAKE_CURRENT_LIST_DIR}/ops/abs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/adaptive_avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/adaptive_max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/assign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/binary_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bitwise_and.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bitwise_left_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bitwise_not.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bitwise_or.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bitwise_right_shift.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bitwise_xor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/ceiling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/col2im.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/convert.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/convert_color_nv12.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/convert_color_to_nv12.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/ctc_greedy_decoder_seq_len.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/deformable_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/deformable_psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/divide.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/elu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/embedding_bag_offsets.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/embedding_bag_offsets_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/embedding_bag_packed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/embedding_bag_packed_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/embedding_segments_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/equal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/erfinv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/exp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/experimental_detectron_proposal_single_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/experimental_detectron_roi_feature_extractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/experimental_detectron_topk_rois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/extract_image_patches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/fft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gated_delta_net.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/generate_proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/greater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/group_convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/group_convolution_backprop_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/group_normalization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/grouped_matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/gru_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/hard_sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/if.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/inverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/irdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/is_finite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/is_inf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/is_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/multiply.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/nms_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/normalize_l2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/paged_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/prelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/proposal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/psroi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/rdft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/read_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/reduce_mean.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/rms_internal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/rms_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/rnn_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/roi_align_rotated.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/scaled_dot_product_attention.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/scatter_nd_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/search_sorted.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/selu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/sequences.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/sigmoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/sign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/slice_scatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/softsign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/squared_difference.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/string_tensor_pack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/string_tensor_unpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/subtract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/tanh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/tensor_iterator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/unique.cpp
)

# Headers not already covered by ${SRC} or ${OPS_SRC}, needed for the clang-format target only.
set(BACKEND_EXTRA_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/evaluates_map.hpp
    ${CMAKE_CURRENT_LIST_DIR}/int_backend.hpp
    ${CMAKE_CURRENT_LIST_DIR}/int_executable.hpp
    ${CMAKE_CURRENT_LIST_DIR}/opset_int_tbl.hpp
    ${CMAKE_CURRENT_LIST_DIR}/perf_counter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/evaluate_node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/ops/ops_evaluates.hpp
)
