// Copyright (C) 2018-2022 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

#include "ngraph/op/op.hpp"
#include "snippets/emitter.hpp"
#include "ngraph/op/parameter.hpp"

namespace ngraph {
namespace snippets {
namespace op {

/**
 * @interface Tile
 * @brief Generated by Canonicalization and represents Loop in affine notation
 * @ingroup snippets
 */
class Tile : public ngraph::op::Op {
public:
    OPENVINO_OP("Tile", "SnippetsOpset");

    /// \brief Construct an Tile
    /// \param region The vector of pairs: emitters and the corresponding registers
    /// \param increment Tile size - count of elements to load and store.
    ///                  Vector Tile should have size of vector register and Scalar Tile should have 1
    /// \param num_inputs Count of inputs
    /// \param num_outputs Count of outputs
    /// \param io_dims Vector of last dimensions of inputs and outputs
    /// \param io_data_sizes Vector of data type sizes of inputs and outputs
    Tile(const std::vector<AllocatedEmitter>& region, size_t increment, size_t num_inputs, size_t num_outputs,
         const std::vector<size_t>& io_dims, const std::vector<size_t>& io_data_sizes);
    Tile() = default;
    std::vector<AllocatedEmitter> region;
    size_t increment = 0;
    size_t num_inputs = 0;
    size_t num_outputs = 0;
    std::vector<size_t> io_dims {};
    std::vector<size_t> io_data_size {};

    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& inputs) const override {
        return std::make_shared<Tile>(region, increment, num_inputs, num_outputs, io_dims, io_data_size);
    }
};

class TileBase : public ngraph::op::Op {
public:
    OPENVINO_OP("TileBase", "SnippetsOpset");
    TileBase(const std::vector<Output<Node>>& args, size_t dimension, size_t work_amount, size_t increment);
    TileBase() = delete;
    bool visit_attributes(AttributeVisitor& visitor) override;
    size_t get_work_amount() const;
    size_t get_increment() const;
    size_t get_dimension() const;
    bool get_evaluate_once() const;

protected:
    size_t dimension;
    size_t work_amount;
    size_t increment;
    bool evaluate_once; // true if the tile is executed only once, used to skip setting and testing the loop counter
};
class TileEnd;
class TileBegin : public TileBase {
    friend TileEnd;
public:
    OPENVINO_OP("TileBegin", "SnippetsOpset");
    explicit TileBegin(const std::vector<Output<Node>>& args);
    TileBegin() = delete;
    void validate_and_infer_types() override;
    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& inputs)  const override;
    std::shared_ptr<TileEnd> get_tile_end();
    // begin_address and input_regs are needed to communicate information between TileBegin and TileEnd emitters
    const uint8_t* begin_address;
    std::vector<size_t> input_regs;
private:
    void validate_and_infer_types_except_TileEnd();
    TileBegin(const std::vector<Output<Node>>& args, size_t dimension, size_t work_amount, size_t increment);
};

class TileEnd : public TileBase {
public:
    OPENVINO_OP("TileEnd", "SnippetsOpset");
    TileEnd(const std::vector<Output<Node>>& args, size_t dimension, size_t work_amount, size_t increment,
              std::vector<bool> apply_increment, std::vector<int64_t> finalization_offsets);
    TileEnd() = delete;
    std::shared_ptr<TileBegin> get_tile_begin();
    void validate_and_infer_types() override;
    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& inputs)  const override;
    const std::vector<int64_t>& get_finalization_offsets() const;
    const std::vector<bool>& get_apply_increment() const;
    void set_finalization_offsets(std::vector<int64_t> offsets);
    void set_apply_increment(std::vector<bool> apply_increment);
    void set_work_amount(size_t new_work_amount);
    void set_increment(size_t new_increment);
    void set_evaluate_once(bool once);
    // Used to propagate information about tile structure, needed to simplify some optimizations. For example,
    // to skip pointer increments when outer tile is empty, and work_amount == vector_size (one inner vector Tile)
    // true by default, the optimizations enabled if it's false;
    bool has_outer_tile;

private:
    std::vector<bool> apply_increment;
    std::vector<int64_t> finalization_offsets;
    size_t tile_io_size;
};

} // namespace op
} // namespace snippets
} // namespace ngraph