// Copyright (C) 2018-2022 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

#include "ngraph/op/op.hpp"
#include "snippets/emitter.hpp"
#include "ngraph/op/parameter.hpp"

namespace ngraph {
namespace snippets {
namespace op {

/**
 * @interface Tile
 * @brief Generated by Canonicalization and represents Loop in affine notation
 * @ingroup snippets
 */
class Tile : public ngraph::op::Op {
public:
    OPENVINO_OP("Tile", "SnippetsOpset");

    /// \brief Construct an Tile
    /// \param region The vector of pairs: emitters and the corresponding registers
    /// \param increment Tile size - count of elements to load and store.
    ///                  Vector Tile should have size of vector register and Scalar Tile should have 1
    /// \param num_inputs Count of inputs
    /// \param num_outputs Count of outputs
    /// \param io_dims Vector of last dimensions of inputs and outputs
    /// \param io_data_sizes Vector of data type sizes of inputs and outputs
    Tile(const std::vector<AllocatedEmitter>& region, size_t increment, size_t num_inputs, size_t num_outputs,
         const std::vector<size_t>& io_dims, const std::vector<size_t>& io_data_sizes);
    Tile() = default;
    std::vector<AllocatedEmitter> region;
    size_t increment = 0;
    size_t num_inputs = 0;
    size_t num_outputs = 0;
    std::vector<size_t> io_dims {};
    std::vector<size_t> io_data_size {};

    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& inputs) const override {
        return std::make_shared<Tile>(region, increment, num_inputs, num_outputs, io_dims, io_data_size);
    }
};

class TileBase : public ngraph::op::Op {
public:
    OPENVINO_OP("TileBase", "SnippetsOpset");
    TileBase(const std::vector<Output<Node>>& args, size_t dimension, size_t workAmount, size_t increment,
             std::vector<bool> apply_increment, std::vector<int64_t> finalization_offsets);
    TileBase() = delete;
    bool visit_attributes(AttributeVisitor& visitor) override;
    size_t get_work_amount() {return workAmount;}
    size_t get_increment() {return increment;}
    size_t get_dimension() {return dimension;}
    std::vector<int64_t> get_finalization_offsets() {return finalization_offsets; }
    const std::vector<bool>& get_apply_increment() {return apply_increment;}

protected:
    size_t dimension;
    size_t workAmount;
    size_t increment;
    std::vector<bool> apply_increment;
    std::vector<int64_t> finalization_offsets;
};
class TileEnd;
class TileBegin : public TileBase {
    friend class TileEnd;
public:
    OPENVINO_OP("TileBegin", "SnippetsOpset");
    TileBegin(const std::vector<Output<Node>>& args, size_t dimension, size_t workAmount, size_t increment,
              std::vector<bool> apply_increment, std::vector<int64_t> finalization_offsets);
    TileBegin() = delete;
    void validate_and_infer_types() override;
    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& inputs)  const override;
    const uint8_t** get_address_ptr() {return &begin_address;}
    std::vector<size_t>& get_input_regs() {return input_regs;}
    void set_work_amount(size_t new_work_amount) {workAmount = new_work_amount;}
    void set_increment(size_t new_increment) {increment = new_increment;}
    std::shared_ptr<TileEnd> get_tile_end();
    const uint8_t* begin_address;
    std::vector<size_t> input_regs;
private:
    void validate_and_infer_types_except_TileEnd();
//    std::vector<size_t> input_regs;
};

class TileEnd : public TileBase {
    friend class TileBegin;

public:
    OPENVINO_OP("TileEnd", "SnippetsOpset");
    // todo: hide this constructor, as this is not an intended way to create TileEnd
    explicit TileEnd(const std::vector<Output<Node>>& args);
    TileEnd() = delete;
    void validate_and_infer_types() override;
    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& inputs)  const override;
};

} // namespace op
} // namespace snippets
} // namespace ngraph