// Copyright (C) 2018-2021 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

#include <transformations_visibility.hpp>

#include <ngraph/op/op.hpp>

namespace ngraph {
namespace snippets {
namespace op {

/**
 * @interface Load
 * @brief Generated by Canonicalization step where explicit store instruction should be emmiteed
 * @ingroup snippets
 */
class TRANSFORMATIONS_API Store : public ngraph::op::Op {
public:
    NGRAPH_RTTI_DECLARATION;

    Store(const Output<Node>& x);
    Store() = default;

    bool visit_attributes(AttributeVisitor& visitor) override;

    std::shared_ptr<Node> clone_with_new_inputs(const OutputVector& new_args) const override;

    void validate_and_infer_types() override;

    bool evaluate(const HostTensorVector& output_values, const HostTensorVector& input_values) const override;
};

} // namespace op
} // namespace snippets
} // namespace ngraph