# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(GPU_OCL_IMPL_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/activation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/adaptive_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/arg_max_min.cpp
    ${CMAKE_CURRENT_LIST_DIR}/batch_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/border.cpp
    ${CMAKE_CURRENT_LIST_DIR}/broadcast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/concatenation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert_color.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convolution.hpp
    ${CMAKE_CURRENT_LIST_DIR}/crop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cum_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/custom_primitive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/deconvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/detection_output.hpp
    ${CMAKE_CURRENT_LIST_DIR}/dft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dynamic_quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/eltwise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/embedding_bag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_detection_output.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_generate_proposals_single_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_prior_grid_generator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_roi_feature_extractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/experimental_detectron_topk_rois.cpp
    ${CMAKE_CURRENT_LIST_DIR}/extract_image_patches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/eye.cpp
    ${CMAKE_CURRENT_LIST_DIR}/fully_connected.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_elements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_nd.hpp
    ${CMAKE_CURRENT_LIST_DIR}/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/gemm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generate_proposals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grid_sample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/grn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/istft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_helper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernel_selector_helper.h
    ${CMAKE_CURRENT_LIST_DIR}/kernels_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/kernels_cache.hpp
    ${CMAKE_CURRENT_LIST_DIR}/kv_cache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lstm_cell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/lstm_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/matrix_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multi_stage_primitive.hpp
    ${CMAKE_CURRENT_LIST_DIR}/multiclass_nms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mutable_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mvn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/non_max_suppression.hpp
    ${CMAKE_CURRENT_LIST_DIR}/non_zero.cpp
    ${CMAKE_CURRENT_LIST_DIR}/normalize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/permute.cpp
    ${CMAKE_CURRENT_LIST_DIR}/pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/primitive_base.hpp
    ${CMAKE_CURRENT_LIST_DIR}/prior_box.cpp
    ${CMAKE_CURRENT_LIST_DIR}/quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reduce.cpp
    ${CMAKE_CURRENT_LIST_DIR}/region_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/register.cpp
    ${CMAKE_CURRENT_LIST_DIR}/register.hpp
    ${CMAKE_CURRENT_LIST_DIR}/reorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reorder.hpp
    ${CMAKE_CURRENT_LIST_DIR}/reorg_yolo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/resample.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rnn_seq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/rnn_seq.hpp
    ${CMAKE_CURRENT_LIST_DIR}/roi_align.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roi_pooling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_elements_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_elements_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/scatter_update.hpp
    ${CMAKE_CURRENT_LIST_DIR}/search_sorted.cpp
    ${CMAKE_CURRENT_LIST_DIR}/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/shuffle_channels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/softmax.hpp
    ${CMAKE_CURRENT_LIST_DIR}/space_to_batch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stateless_kv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/swiglu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/unique.cpp
)
