# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""Tests for create_agent_pr.py.

The script has importable helper functions (get_op_names, compose_pr_body)
and a main() entry point guarded by ``if __name__ == "__main__"``.

Function-level tests (no external processes):
  - get_op_names: branch slug and title derived from co_located_ops / error_context
  - compose_pr_body: required AI-generation banner, human-review warning

CLI-level tests (subprocess):
  - Missing state file → exit 1
  - No patches in output dir → exit 0, no PR created
  - --dry-run with valid state + patches → exit 0, no git/gh commands executed
"""

import importlib.util
import json
import pathlib
import sys

import pytest

from conftest import SCRIPTS_DIR, run_script, write_json

SCRIPT = SCRIPTS_DIR / "create_agent_pr.py"


# ---------------------------------------------------------------------------
# Import helpers from the module without executing main()
# ---------------------------------------------------------------------------

def _import_module():
    spec = importlib.util.spec_from_file_location("create_agent_pr", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# The module defines only functions + `if __name__ == "__main__"` guard,
# so importing it is safe and produces no side effects.
_mod = _import_module()


# ---------------------------------------------------------------------------
# get_op_names
# ---------------------------------------------------------------------------

def _state(co_located_ops=None, error_context=""):
    return {
        "ov_orchestrator": {
            "co_located_ops": co_located_ops or [],
            "error_context": error_context,
        }
    }


class TestGetOpNames:
    def test_co_located_ops_used_when_present(self):
        ops, slug, title = _mod.get_op_names(_state(co_located_ops=["aten::erfinv"]))
        assert "erfinv" in slug
        assert "aten::erfinv" in title

    def test_multiple_co_located_ops_joined_in_slug(self):
        ops, slug, title = _mod.get_op_names(
            _state(co_located_ops=["aten::erfinv", "aten::logit"])
        )
        assert "erfinv" in slug
        assert "logit" in slug

    def test_slug_is_lowercase_hyphenated(self):
        ops, slug, title = _mod.get_op_names(_state(co_located_ops=["aten::MyCustomOp"]))
        assert slug == slug.lower()
        assert "::" not in slug
        assert "_" not in slug or "-" in slug  # colons replaced by hyphens

    def test_fallback_to_error_context_when_no_co_located_ops(self):
        ops, slug, title = _mod.get_op_names(
            _state(error_context="missing_conversion_rule/aten::erfinv")
        )
        assert len(ops) == 1
        assert "erfinv" in ops[0]

    def test_empty_state_returns_some_slug(self):
        """Must not crash on empty state — a slug is always returned."""
        ops, slug, title = _mod.get_op_names({})
        assert isinstance(slug, str)
        assert len(slug) > 0


# ---------------------------------------------------------------------------
# compose_pr_body
# ---------------------------------------------------------------------------

class TestComposePrBody:
    _REQUIRED_PHRASES = [
        "generated by",           # AI generation disclosure
        "human review",           # reviewer responsibility
        "sign-off",               # safety instruction (actual: 'do **not** merge without human sign-off')
        "draft",                  # must stay draft until reviewed
    ]

    def test_body_contains_ai_generation_banner(self):
        body = _mod.compose_pr_body(["aten::erfinv"], "aten::erfinv")
        lower = body.lower()
        for phrase in self._REQUIRED_PHRASES:
            assert phrase in lower, f"Missing required phrase: {phrase!r}"

    def test_body_contains_op_name(self):
        body = _mod.compose_pr_body(["aten::erfinv"], "aten::erfinv")
        assert "aten::erfinv" in body

    def test_body_contains_agent_name(self):
        body = _mod.compose_pr_body(["aten::erfinv"], "aten::erfinv")
        assert "enable-operator" in body

    def test_body_with_multiple_ops(self):
        ops = ["aten::erfinv", "aten::logit"]
        body = _mod.compose_pr_body(ops, ", ".join(ops))
        for op in ops:
            assert op in body

    def test_body_is_non_empty_string(self):
        body = _mod.compose_pr_body(["aten::erfinv"], "aten::erfinv")
        assert isinstance(body, str)
        assert len(body.strip()) > 0

    def test_important_callout_present(self):
        """The [!IMPORTANT] GitHub callout must be present."""
        body = _mod.compose_pr_body(["aten::erfinv"], "aten::erfinv")
        assert "IMPORTANT" in body


# ---------------------------------------------------------------------------
# CLI: missing state file → exit 1
# ---------------------------------------------------------------------------

def test_missing_state_file_exits_one(tmp_path):
    result = run_script(SCRIPT, tmp_path)
    assert result.returncode == 1


def test_missing_state_file_error_message(tmp_path):
    result = run_script(SCRIPT, tmp_path)
    assert "state" in result.stderr.lower() or "not found" in result.stderr.lower()


# ---------------------------------------------------------------------------
# CLI: no patches → exit 0 (nothing to publish)
# ---------------------------------------------------------------------------

def test_no_patches_exits_zero(tmp_path):
    write_json(tmp_path / "agent-results/pipeline_state.json", _state(
        co_located_ops=["aten::erfinv"],
    ))
    # patch dir exists but is empty
    (tmp_path / "agent-results/enable-operator/patches/openvino").mkdir(parents=True)
    result = run_script(SCRIPT, tmp_path)
    assert result.returncode == 0


# ---------------------------------------------------------------------------
# CLI: --dry-run with state + patches → exit 0, no git/gh mutation
# ---------------------------------------------------------------------------

def test_dry_run_with_patches_exits_zero(tmp_path):
    write_json(tmp_path / "agent-results/pipeline_state.json", _state(
        co_located_ops=["aten::erfinv"],
    ))
    patch_dir = tmp_path / "agent-results/enable-operator/patches/openvino"
    patch_dir.mkdir(parents=True)
    (patch_dir / "fe.patch").write_text("diff --git a/x b/x\n", encoding="utf-8")

    result = run_script(SCRIPT, tmp_path, "--dry-run")
    assert result.returncode == 0


def test_dry_run_prints_would_create_branch(tmp_path):
    write_json(tmp_path / "agent-results/pipeline_state.json", _state(
        co_located_ops=["aten::erfinv"],
    ))
    patch_dir = tmp_path / "agent-results/enable-operator/patches/openvino"
    patch_dir.mkdir(parents=True)
    (patch_dir / "fe.patch").write_text("diff", encoding="utf-8")

    result = run_script(SCRIPT, tmp_path, "--dry-run")
    assert "dry-run" in result.stdout.lower() or "would" in result.stdout.lower()


def test_dry_run_does_not_call_git_checkout(tmp_path, monkeypatch):
    """--dry-run must not issue any mutating git commands."""
    write_json(tmp_path / "agent-results/pipeline_state.json", _state(
        co_located_ops=["aten::erfinv"],
    ))
    patch_dir = tmp_path / "agent-results/enable-operator/patches/openvino"
    patch_dir.mkdir(parents=True)
    (patch_dir / "fe.patch").write_text("diff", encoding="utf-8")

    result = run_script(SCRIPT, tmp_path, "--dry-run")
    # In dry-run, gh CLI is never invoked — so if gh is absent the run still passes
    assert result.returncode == 0
