import openvino._pyopenvino
import typing
from functools import partial as partial
from openvino._pyopenvino import Node as Node
from openvino.utils.decorators import nameable_op as nameable_op
from openvino.utils.types import as_node as as_node, as_nodes as as_nodes, make_constant_node as make_constant_node

def interpolate(*args, **kwargs) -> openvino._pyopenvino.Node: ...
def is_finite(*args, **kwargs) -> openvino._pyopenvino.Node: ...
def is_inf(*args, **kwargs) -> openvino._pyopenvino.Node: ...
def is_nan(*args, **kwargs) -> openvino._pyopenvino.Node: ...
def unique(*args, **kwargs) -> openvino._pyopenvino.Node: ...

NodeInput: typing._UnionGenericAlias
