# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(LIBRARY_SRC
    ${root_dir}/src/helper_transforms/const_to_result_remover.cpp
    ${root_dir}/src/helper_transforms/embedding_segments_feature_fusing.cpp
    ${root_dir}/src/helper_transforms/saved_model_unused_remover.cpp
    ${root_dir}/src/helper_transforms/tensor_array_v3_replacer.cpp
    ${root_dir}/src/helper_transforms/tensor_list_ops_resolver.cpp
    ${root_dir}/src/op/addN.cpp
    ${root_dir}/src/op/adjust_contrast.cpp
    ${root_dir}/src/op/adjust_hue.cpp
    ${root_dir}/src/op/adjust_saturation.cpp
    ${root_dir}/src/op/angle.cpp
    ${root_dir}/src/op/approximate_equal_op.cpp
    ${root_dir}/src/op/argdef_ops.cpp
    ${root_dir}/src/op/arg_min_max.cpp
    ${root_dir}/src/op/atan2.cpp
    ${root_dir}/src/op/avg_pool.cpp
    ${root_dir}/src/op/bias_add.cpp
    ${root_dir}/src/op/binary_op.cpp
    ${root_dir}/src/op/bincount.cpp
    ${root_dir}/src/op/broadcast_args.cpp
    ${root_dir}/src/op/broadcast_to.cpp
    ${root_dir}/src/op/bucketize.cpp
    ${root_dir}/src/op/cast.cpp
    ${root_dir}/src/op/clip_by_value.cpp
    ${root_dir}/src/op/complex_abs.cpp
    ${root_dir}/src/op/complex.cpp
    ${root_dir}/src/op/concat.cpp
    ${root_dir}/src/op/conj_transpose.cpp
    ${root_dir}/src/op/const.cpp
    ${root_dir}/src/op/conv_2d_backprop.cpp
    ${root_dir}/src/op/conv_2d.cpp
    ${root_dir}/src/op/conv_3d_backprop.cpp
    ${root_dir}/src/op/conv_3d.cpp
    ${root_dir}/src/op/crop_and_resize.cpp
    ${root_dir}/src/op/ctc_greedy_decoder.cpp
    ${root_dir}/src/op/ctc_loss.cpp
    ${root_dir}/src/op/cumsum.cpp
    ${root_dir}/src/op/depth_to_space.cpp
    ${root_dir}/src/op/depthwise_conv_2d.cpp
    ${root_dir}/src/op/div.cpp
    ${root_dir}/src/op/div_no_nan.cpp
    ${root_dir}/src/op/dynamic_partition.cpp
    ${root_dir}/src/op/einsum.cpp
    ${root_dir}/src/op/elu.cpp
    ${root_dir}/src/op/erfc.cpp
    ${root_dir}/src/op/expand_dims.cpp
    ${root_dir}/src/op/expm1.cpp
    ${root_dir}/src/op/extract_image_patches.cpp
    ${root_dir}/src/op/fake_quant_min_max_vars.cpp
    ${root_dir}/src/op/fft.cpp
    ${root_dir}/src/op/fill.cpp
    ${root_dir}/src/op/fused_batch_norm.cpp
    ${root_dir}/src/op/gather.cpp
    ${root_dir}/src/op/gather_tree.cpp
    ${root_dir}/src/op/gelu.cpp
    ${root_dir}/src/op/hsv_to_rgb.cpp
    ${root_dir}/src/op/identity.cpp
    ${root_dir}/src/op/ifft.cpp
    ${root_dir}/src/op/interpolate.cpp
    ${root_dir}/src/op/inv.cpp
    ${root_dir}/src/op/invert_permutation.cpp
    ${root_dir}/src/op/irfft.cpp
    ${root_dir}/src/op/l2_loss.cpp
    ${root_dir}/src/op/leaky_relu.cpp
    ${root_dir}/src/op/linspace.cpp
    ${root_dir}/src/op/list_diff.cpp
    ${root_dir}/src/op/log1p.cpp
    ${root_dir}/src/op/log_softmax.cpp
    ${root_dir}/src/op/lrn.cpp
    ${root_dir}/src/op/matmul.cpp
    ${root_dir}/src/op/matrix_band_part.cpp
    ${root_dir}/src/op/matrix_diag.cpp
    ${root_dir}/src/op/matrix_inverse.cpp
    ${root_dir}/src/op/max_pool.cpp
    ${root_dir}/src/op/mul_no_nan.cpp
    ${root_dir}/src/op/multinomial.cpp
    ${root_dir}/src/op/non_max_suppression.cpp
    ${root_dir}/src/op/no_op.cpp
    ${root_dir}/src/op/one_hot.cpp
    ${root_dir}/src/op/ones_like.cpp
    ${root_dir}/src/op/pack.cpp
    ${root_dir}/src/op/pad.cpp
    ${root_dir}/src/op/parallel_dynamic_stitch.cpp
    ${root_dir}/src/op/placeholder.cpp
    ${root_dir}/src/op/random_uniform.cpp
    ${root_dir}/src/op/range.cpp
    ${root_dir}/src/op/rank.cpp
    ${root_dir}/src/op/real_imag.cpp
    ${root_dir}/src/op/reciprocal.cpp
    ${root_dir}/src/op/reduce.cpp
    ${root_dir}/src/op/relu_0_to_1.cpp
    ${root_dir}/src/op/relu_6.cpp
    ${root_dir}/src/op/reshape.cpp
    ${root_dir}/src/op/reverse.cpp
    ${root_dir}/src/op/reverse_sequence.cpp
    ${root_dir}/src/op/rfft.cpp
    ${root_dir}/src/op/rgb_to_hsv.cpp
    ${root_dir}/src/op/rint.cpp
    ${root_dir}/src/op/roll.cpp
    ${root_dir}/src/op/round.cpp
    ${root_dir}/src/op/rsqrt.cpp
    ${root_dir}/src/op/scatter_nd.cpp
    ${root_dir}/src/op/segment_max.cpp
    ${root_dir}/src/op/segment_sum.cpp
    ${root_dir}/src/op/select.cpp
    ${root_dir}/src/op/shape.cpp
    ${root_dir}/src/op/size.cpp
    ${root_dir}/src/op/slice.cpp
    ${root_dir}/src/op/softmax.cpp
    ${root_dir}/src/op/space_to_batch_nd.cpp
    ${root_dir}/src/op/space_to_depth.cpp
    ${root_dir}/src/op/sparse_fill_empty_rows.cpp
    ${root_dir}/src/op/sparse_segment_op.cpp
    ${root_dir}/src/op/sparse_tensor_dense_add.cpp
    ${root_dir}/src/op/sparse_tensor_dense_mat_mul.cpp
    ${root_dir}/src/op/sparse_to_dense.cpp
    ${root_dir}/src/op/split.cpp
    ${root_dir}/src/op/sqrt.cpp
    ${root_dir}/src/op/square.cpp
    ${root_dir}/src/op/squeeze.cpp
    ${root_dir}/src/op/strided_slice.cpp
    ${root_dir}/src/op/tensor_list_operations.cpp
    ${root_dir}/src/op/tensor_scatter_add.cpp
    ${root_dir}/src/op/tensor_scatter_update.cpp
    ${root_dir}/src/op/tile.cpp
    ${root_dir}/src/op/tobool.cpp
    ${root_dir}/src/op/top_k.cpp
    ${root_dir}/src/op/transpose.cpp
    ${root_dir}/src/op/truncate_div.cpp
    ${root_dir}/src/op/truncate_mod.cpp
    ${root_dir}/src/op/unary_op.cpp
    ${root_dir}/src/op/unique.cpp
    ${root_dir}/src/op/unique_with_counts.cpp
    ${root_dir}/src/op/unpack.cpp
    ${root_dir}/src/op/unravel_index.cpp
    ${root_dir}/src/op/unsorted_segment_max.cpp
    ${root_dir}/src/op/unsorted_segment_sum.cpp
    ${root_dir}/src/op/where.cpp
    ${root_dir}/src/op/xdivy.cpp
    ${root_dir}/src/op/xlog1py.cpp
    ${root_dir}/src/op/xlogy.cpp
    ${root_dir}/src/op/zeros_like.cpp
    ${root_dir}/src/place.cpp
    ${root_dir}/src/utils.cpp
)
set(LIBRARY_HEADERS
    ${root_dir}/include/common_op_table.hpp
    ${root_dir}/include/helper_ops/block_lstm.hpp
    ${root_dir}/include/helper_ops/complex_type_mark.hpp
    ${root_dir}/include/helper_ops/enter.hpp
    ${root_dir}/include/helper_ops/exit.hpp
    ${root_dir}/include/helper_ops/fifo_queue.hpp
    ${root_dir}/include/helper_ops/gru_block_cell.hpp
    ${root_dir}/include/helper_ops/internal_operation.hpp
    ${root_dir}/include/helper_ops/iterator.hpp
    ${root_dir}/include/helper_ops/keep_in_graph_op.hpp
    ${root_dir}/include/helper_ops/loop_cond.hpp
    ${root_dir}/include/helper_ops/merge.hpp
    ${root_dir}/include/helper_ops/next_iteration.hpp
    ${root_dir}/include/helper_ops/sparse_segment_ops.hpp
    ${root_dir}/include/helper_ops/switch.hpp
    ${root_dir}/include/helper_ops/tensor_array.hpp
    ${root_dir}/include/helper_ops/tensor_list_ops.hpp
    ${root_dir}/include/helper_ops/unsupported_constant.hpp
    ${root_dir}/include/helper_transforms/const_to_result_remover.hpp
    ${root_dir}/include/helper_transforms/embedding_segments_feature_fusing.hpp
    ${root_dir}/include/helper_transforms/saved_model_unused_remover.hpp
    ${root_dir}/include/helper_transforms/tensor_array_v3_replacer.hpp
    ${root_dir}/include/helper_transforms/tensor_list_ops_resolver.hpp
    ${root_dir}/include/place.hpp
    ${root_dir}/include/tf_framework_node.hpp
    ${root_dir}/include/utils.hpp
)
