# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(LIBRARY_SRC
    ${CMAKE_CURRENT_LIST_DIR}/helper_transforms/const_to_result_remover.cpp
    ${CMAKE_CURRENT_LIST_DIR}/helper_transforms/embedding_segments_feature_fusing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/helper_transforms/saved_model_unused_remover.cpp
    ${CMAKE_CURRENT_LIST_DIR}/helper_transforms/tensor_array_v3_replacer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/helper_transforms/tensor_list_ops_resolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/addN.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adjust_contrast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adjust_hue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/adjust_saturation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/angle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/approximate_equal_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/argdef_ops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/arg_min_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/atan2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/avg_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bias_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/binary_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bincount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/broadcast_args.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/broadcast_to.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/bucketize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/clip_by_value.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/complex_abs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/complex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/concat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/conj_transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/const.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/conv_2d_backprop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/conv_2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/conv_3d_backprop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/conv_3d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/crop_and_resize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_greedy_decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ctc_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/cumsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/depth_to_space.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/depthwise_conv_2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/div.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/div_no_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/dynamic_partition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/einsum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/elu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/erfc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/expand_dims.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/expm1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/extract_image_patches.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fake_quant_min_max_vars.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fill.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/fused_batch_norm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gather_tree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/gelu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/hsv_to_rgb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/identity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ifft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/interpolate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/inv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/invert_permutation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/irfft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/l2_loss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/leaky_relu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/linspace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/list_diff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/log1p.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/log_softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/lrn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matmul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matrix_band_part.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matrix_diag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/matrix_inverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/max_pool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/mul_no_nan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/multinomial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/non_max_suppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/no_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/one_hot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/ones_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/pack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/pad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/parallel_dynamic_stitch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/placeholder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/random_uniform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/range.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rank.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/real_imag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reciprocal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reduce.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/relu_0_to_1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/relu_6.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reshape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reverse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/reverse_sequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rfft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rgb_to_hsv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/roll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/round.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/rsqrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/scatter_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/segment_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/select.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/shape.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/size.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/softmax.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/space_to_batch_nd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/space_to_depth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_fill_empty_rows.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_segment_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_tensor_dense_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_tensor_dense_mat_mul.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sparse_to_dense.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/split.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/sqrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/square.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/squeeze.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/strided_slice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tensor_list_operations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tensor_scatter_add.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tensor_scatter_update.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/tobool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/top_k.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/transpose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/truncate_div.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/truncate_mod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unary_op.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unique.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unique_with_counts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unravel_index.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unsorted_segment_max.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/unsorted_segment_sum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/where.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/xdivy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/xlog1py.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/xlogy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/op/zeros_like.cpp
    ${CMAKE_CURRENT_LIST_DIR}/place.cpp
    ${CMAKE_CURRENT_LIST_DIR}/utils.cpp
)
set(LIBRARY_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/../include/common_op_table.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/block_lstm.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/complex_type_mark.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/enter.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/exit.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/fifo_queue.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/gru_block_cell.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/internal_operation.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/iterator.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/keep_in_graph_op.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/loop_cond.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/merge.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/next_iteration.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/sparse_segment_ops.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/switch.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/tensor_array.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/tensor_list_ops.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_ops/unsupported_constant.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_transforms/const_to_result_remover.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_transforms/embedding_segments_feature_fusing.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_transforms/saved_model_unused_remover.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_transforms/tensor_array_v3_replacer.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/helper_transforms/tensor_list_ops_resolver.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/place.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/tf_framework_node.hpp
    ${CMAKE_CURRENT_LIST_DIR}/../include/utils.hpp
)
