// Copyright (C) 2018-2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//
// tp_l0_call_cost — minimal reproducer for Level Zero host-side call cost
// collapsing under concurrent callers.
//
// Background.  Recording one AllReduce command list inside the TP_GPU plugin
// costs 1.29 ms on four ranks, and 87% of that is the Append* calls
// themselves rather than reset, close or queue drains — roughly 7 us per
// call.  The same calls measured in a single-threaded process cost 0.5 us.
// Inside the plugin the distribution is shifted uniformly (not one call
// below 5 us out of 6144) rather than skewed by a few slow ones, which rules
// out any property of the data, the buffers or the command list and points
// at a lock shared by the driver's entry points.
//
// This sample reproduces the effect without OpenVINO: it measures each API
// from one thread while N other threads call into the driver on their own
// command lists.  If the cost comes from a shared lock, every API degrades
// together and roughly in proportion to N.
//
// The recorded lists are never executed — appends are what is being timed,
// and a list of waits on events nobody signals would simply hang.
//
// Usage:
//   ./tp_l0_call_cost [calls_per_measurement] [num_ranks]

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <functional>
#include <iomanip>
#include <iostream>
#include <string>
#include <thread>
#include <vector>

#include <level_zero/ze_api.h>

#include "allreduce_sum_spv.h"  // generated by ocloc

#define ZE_CHECK(expr)                                                          \
    do {                                                                        \
        ze_result_t _r = (expr);                                                \
        if (_r != ZE_RESULT_SUCCESS) {                                          \
            std::cerr << "L0 error 0x" << std::hex << static_cast<uint32_t>(_r) \
                      << std::dec << " at " << __FILE__ << ":" << __LINE__      \
                      << " (" #expr ")" << std::endl;                           \
            std::exit(1);                                                       \
        }                                                                       \
    } while (0)

namespace {

using clk = std::chrono::steady_clock;

double ns_per_call(clk::time_point a, clk::time_point b, int calls) {
    return std::chrono::duration<double, std::nano>(b - a).count() / calls;
}

struct Rank {
    ze_device_handle_t device = nullptr;
    std::string name;
    uint32_t compute_ordinal = 0;
    ze_command_list_handle_t list = nullptr;
    ze_module_handle_t module = nullptr;
    ze_kernel_handle_t kernel = nullptr;
    void* buf_a = nullptr;
    void* buf_b = nullptr;
};

uint32_t first_compute_ordinal(ze_device_handle_t dev) {
    uint32_t count = 0;
    zeDeviceGetCommandQueueGroupProperties(dev, &count, nullptr);
    std::vector<ze_command_queue_group_properties_t> props(
        count, {ZE_STRUCTURE_TYPE_COMMAND_QUEUE_GROUP_PROPERTIES, nullptr});
    zeDeviceGetCommandQueueGroupProperties(dev, &count, props.data());
    for (uint32_t g = 0; g < count; ++g) {
        if (props[g].flags & ZE_COMMAND_QUEUE_GROUP_PROPERTY_FLAG_COMPUTE) {
            return g;
        }
    }
    std::cerr << "no compute queue group" << std::endl;
    std::exit(1);
}

void init_rank(ze_context_handle_t ctx, ze_device_handle_t dev, Rank& r, size_t bytes) {
    r.device = dev;
    ze_device_properties_t dp{ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES, nullptr};
    zeDeviceGetProperties(dev, &dp);
    r.name = dp.name;
    r.compute_ordinal = first_compute_ordinal(dev);

    ze_command_list_desc_t ld{ZE_STRUCTURE_TYPE_COMMAND_LIST_DESC, nullptr};
    ld.commandQueueGroupOrdinal = r.compute_ordinal;
    ZE_CHECK(zeCommandListCreate(ctx, dev, &ld, &r.list));

    ze_module_desc_t md{ZE_STRUCTURE_TYPE_MODULE_DESC, nullptr};
    md.format = ZE_MODULE_FORMAT_IL_SPIRV;
    md.inputSize = kAllReduceSumSpvSize;
    md.pInputModule = reinterpret_cast<const uint8_t*>(kAllReduceSumSpv);
    md.pBuildFlags = "-cl-std=CL2.0";
    ZE_CHECK(zeModuleCreate(ctx, dev, &md, &r.module, nullptr));

    ze_kernel_desc_t kd{ZE_STRUCTURE_TYPE_KERNEL_DESC, nullptr};
    kd.pKernelName = "allreduce_sum_f16";
    ZE_CHECK(zeKernelCreate(r.module, &kd, &r.kernel));
    ZE_CHECK(zeKernelSetGroupSize(r.kernel, 256, 1, 1));

    ze_device_mem_alloc_desc_t mad{ZE_STRUCTURE_TYPE_DEVICE_MEM_ALLOC_DESC, nullptr};
    ZE_CHECK(zeMemAllocDevice(ctx, &mad, bytes, 64, dev, &r.buf_a));
    ZE_CHECK(zeMemAllocDevice(ctx, &mad, bytes, 64, dev, &r.buf_b));
}

void destroy_rank(ze_context_handle_t ctx, Rank& r) {
    if (r.buf_a) zeMemFree(ctx, r.buf_a);
    if (r.buf_b) zeMemFree(ctx, r.buf_b);
    if (r.kernel) zeKernelDestroy(r.kernel);
    if (r.module) zeModuleDestroy(r.module);
    if (r.list) zeCommandListDestroy(r.list);
}

// Keeps `contenders` threads calling into the driver on their own command
// lists for as long as it is alive.  Each thread only appends: no submission,
// no device work, nothing the measuring thread shares except the driver.
class Contention {
public:
    Contention(ze_context_handle_t ctx, const Rank& on, void* dst, void* src,
               size_t bytes, int contenders)
        : m_ctx(ctx) {
        ze_command_list_desc_t ld{ZE_STRUCTURE_TYPE_COMMAND_LIST_DESC, nullptr};
        ld.commandQueueGroupOrdinal = on.compute_ordinal;
        for (int t = 0; t < contenders; ++t) {
            ze_command_list_handle_t l = nullptr;
            if (zeCommandListCreate(m_ctx, on.device, &ld, &l) != ZE_RESULT_SUCCESS) {
                break;
            }
            m_lists.push_back(l);
        }
        for (auto l : m_lists) {
            m_threads.emplace_back([this, l, dst, src, bytes] {
                while (!m_stop.load(std::memory_order_relaxed)) {
                    // Reset keeps the list from growing without bound; what
                    // matters is the rate of calls into the driver.
                    if (zeCommandListReset(l) != ZE_RESULT_SUCCESS) return;
                    for (int i = 0; i < 256; ++i) {
                        if (zeCommandListAppendMemoryCopy(l, dst, src, bytes,
                                                          nullptr, 0, nullptr) !=
                            ZE_RESULT_SUCCESS) {
                            return;
                        }
                    }
                }
            });
        }
        if (!m_threads.empty()) {
            // Let the contenders reach steady state before anything is timed.
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }
    }

    ~Contention() {
        m_stop.store(true, std::memory_order_relaxed);
        for (auto& t : m_threads) t.join();
        for (auto l : m_lists) zeCommandListDestroy(l);
    }

    Contention(const Contention&) = delete;
    Contention& operator=(const Contention&) = delete;

private:
    ze_context_handle_t m_ctx;
    std::vector<ze_command_list_handle_t> m_lists;
    std::vector<std::thread> m_threads;
    std::atomic<bool> m_stop{false};
};

}  // namespace

int main(int argc, char* argv[]) {
    const int calls = (argc > 1) ? std::stoi(argv[1]) : 512;
    const int want_ranks = (argc > 2) ? std::stoi(argv[2]) : 2;
    const size_t bytes = 4096;

    ZE_CHECK(zeInit(0));

    uint32_t dcount = 0;
    ZE_CHECK(zeDriverGet(&dcount, nullptr));
    std::vector<ze_driver_handle_t> drivers(dcount);
    ZE_CHECK(zeDriverGet(&dcount, drivers.data()));

    ze_driver_handle_t driver = nullptr;
    std::vector<ze_device_handle_t> devs;
    for (auto d : drivers) {
        uint32_t cnt = 0;
        zeDeviceGet(d, &cnt, nullptr);
        std::vector<ze_device_handle_t> all(cnt);
        zeDeviceGet(d, &cnt, all.data());
        std::vector<ze_device_handle_t> gpus;
        for (auto dh : all) {
            ze_device_properties_t prop{ZE_STRUCTURE_TYPE_DEVICE_PROPERTIES, nullptr};
            zeDeviceGetProperties(dh, &prop);
            if (prop.type == ZE_DEVICE_TYPE_GPU) gpus.push_back(dh);
        }
        if (static_cast<int>(gpus.size()) >= 2) {
            driver = d;
            devs.assign(gpus.begin(),
                        gpus.begin() + std::min<int>(want_ranks, static_cast<int>(gpus.size())));
            break;
        }
    }
    if (devs.size() < 2) {
        std::cerr << "Need at least 2 GPUs under a single L0 driver." << std::endl;
        return 1;
    }

    ze_context_desc_t cd{ZE_STRUCTURE_TYPE_CONTEXT_DESC, nullptr};
    ze_context_handle_t ctx = nullptr;
    ZE_CHECK(zeContextCreateEx(driver, &cd, static_cast<uint32_t>(devs.size()),
                               devs.data(), &ctx));

    std::vector<Rank> ranks(devs.size());
    for (size_t i = 0; i < devs.size(); ++i) {
        init_rank(ctx, devs[i], ranks[i], bytes);
    }

    // Events are created over every device so that signals and waits are the
    // cross-device kind the collective actually records.
    ze_event_pool_desc_t epd{ZE_STRUCTURE_TYPE_EVENT_POOL_DESC, nullptr};
    epd.flags = 0;
    epd.count = 4;
    ze_event_pool_handle_t pool = nullptr;
    ZE_CHECK(zeEventPoolCreate(ctx, &epd, static_cast<uint32_t>(devs.size()),
                               devs.data(), &pool));
    std::vector<ze_event_handle_t> events(epd.count);
    for (uint32_t i = 0; i < epd.count; ++i) {
        ze_event_desc_t ed{ZE_STRUCTURE_TYPE_EVENT_DESC, nullptr};
        ed.signal = ZE_EVENT_SCOPE_FLAG_DEVICE;
        ed.wait = ZE_EVENT_SCOPE_FLAG_DEVICE;
        ed.index = i;
        ZE_CHECK(zeEventCreate(pool, &ed, &events[i]));
    }

    Rank& r0 = ranks[0];
    Rank& r1 = ranks[1];

    std::cout << "tp_l0_call_cost\n"
              << "  ranks:             " << ranks.size() << "\n"
              << "  calls per measure: " << calls << "\n";
    for (size_t i = 0; i < ranks.size(); ++i) {
        std::cout << "  rank " << i << ": " << ranks[i].name << "\n";
    }
    std::cout << std::endl;

    // Kernel arguments are set once; the launch probe only times the append.
    uint64_t n64 = 1;
    ZE_CHECK(zeKernelSetArgumentValue(r0.kernel, 0, sizeof(void*), &r0.buf_b));
    ZE_CHECK(zeKernelSetArgumentValue(r0.kernel, 1, sizeof(void*), &r0.buf_a));
    ZE_CHECK(zeKernelSetArgumentValue(r0.kernel, 2, sizeof(void*), &r0.buf_a));
    ZE_CHECK(zeKernelSetArgumentValue(r0.kernel, 3, sizeof(n64), &n64));
    ze_group_count_t gc{1, 1, 1};

    // Every probe records into a freshly reset list, so only the call under
    // test is timed.  The mix is what recording one ring collective issues.
    struct Probe {
        const char* name;
        std::function<void()> call;
    };
    const std::vector<Probe> probes = {
        {"AppendMemoryCopy (peer)",
         [&] {
             ZE_CHECK(zeCommandListAppendMemoryCopy(r0.list, r1.buf_a, r0.buf_a, bytes,
                                                    nullptr, 0, nullptr));
         }},
        {"AppendMemoryCopy (local)",
         [&] {
             ZE_CHECK(zeCommandListAppendMemoryCopy(r0.list, r0.buf_b, r0.buf_a, bytes,
                                                    nullptr, 0, nullptr));
         }},
        {"AppendLaunchKernel",
         [&] {
             ZE_CHECK(zeCommandListAppendLaunchKernel(r0.list, r0.kernel, &gc,
                                                      nullptr, 0, nullptr));
         }},
        {"AppendWaitOnEvents",
         [&] { ZE_CHECK(zeCommandListAppendWaitOnEvents(r0.list, 1, &events[0])); }},
        {"AppendSignalEvent",
         [&] { ZE_CHECK(zeCommandListAppendSignalEvent(r0.list, events[1])); }},
        {"AppendEventReset",
         [&] { ZE_CHECK(zeCommandListAppendEventReset(r0.list, events[2])); }},
        {"AppendBarrier",
         [&] { ZE_CHECK(zeCommandListAppendBarrier(r0.list, nullptr, 0, nullptr)); }},
        {"KernelSetArgumentValue",
         [&] { ZE_CHECK(zeKernelSetArgumentValue(r0.kernel, 3, sizeof(n64), &n64)); }},
    };

    const std::vector<int> thread_counts = {0, 1, 2, 4, 8, 16};
    std::vector<std::vector<double>> us(probes.size(),
                                        std::vector<double>(thread_counts.size(), 0.0));

    for (size_t c = 0; c < thread_counts.size(); ++c) {
        Contention load(ctx, r0, r1.buf_b, r0.buf_b, bytes, thread_counts[c]);
        for (size_t p = 0; p < probes.size(); ++p) {
            // Whichever memory-copy probe runs first pays a one-off cost of
            // roughly 2 us per call; without a warm-up it lands on an
            // arbitrary row and looks like a property of that variant.
            ZE_CHECK(zeCommandListReset(r0.list));
            for (int i = 0; i < 64; ++i) {
                probes[p].call();
            }
            ZE_CHECK(zeCommandListReset(r0.list));
            auto t0 = clk::now();
            for (int i = 0; i < calls; ++i) {
                probes[p].call();
            }
            auto t1 = clk::now();
            us[p][c] = ns_per_call(t0, t1, calls) / 1000.0;
        }
        ZE_CHECK(zeCommandListReset(r0.list));
    }

    std::cout << "Host cost of one call, in microseconds, versus the number of\n"
                 "other threads calling the driver concurrently:\n"
              << std::endl;
    std::cout << "  " << std::left << std::setw(26) << "API";
    for (int t : thread_counts) {
        std::cout << std::right << std::setw(9) << (std::to_string(t) + " thr");
    }
    std::cout << std::right << std::setw(11) << "slowdown" << std::endl;

    for (size_t p = 0; p < probes.size(); ++p) {
        std::cout << "  " << std::left << std::setw(26) << probes[p].name;
        for (size_t c = 0; c < thread_counts.size(); ++c) {
            std::cout << std::right << std::setw(9) << std::fixed << std::setprecision(2)
                      << us[p][c];
        }
        const double base = us[p][0];
        const double worst = us[p][thread_counts.size() - 1];
        std::cout << std::right << std::setw(10) << std::fixed << std::setprecision(1)
                  << (base > 0 ? worst / base : 0.0) << "x" << std::endl;
    }
    std::cout << std::endl;

    for (auto& e : events) zeEventDestroy(e);
    zeEventPoolDestroy(pool);
    for (auto& r : ranks) destroy_rank(ctx, r);
    zeContextDestroy(ctx);
    return 0;
}
