#!groovy



properties([
    parameters([
        string(defaultValue: '',
               description: 'Pipeline shared library version (branch/tag/commit). Determined automatically if empty',
               name: 'library_version')
    ])
])

loadOpenVinoLibrary {
    potEntrypoint(this)
}
