// Copyright (C) 2018-2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#pragma once

#include "intel_npu/config/npuw.hpp"
#include "openvino/runtime/file_handle.hpp"
#include "openvino/runtime/intel_npu/properties.hpp"

namespace ov {
namespace intel_npu {

#define INTEL_NPU_NPUW_DECLARE_PROPERTY(Type, Name, Key) static constexpr ov::Property<Type> Name{Key};
#define INTEL_NPU_NPUW_IF_BUILD_ALL(SELECT, ...) SELECT(__VA_ARGS__)
#ifdef NPU_PLUGIN_DEVELOPER_BUILD
#define INTEL_NPU_NPUW_IF_BUILD_DEV(SELECT, ...) SELECT(__VA_ARGS__)
#else
#define INTEL_NPU_NPUW_IF_BUILD_DEV(SELECT, ...)
#endif

#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL

namespace npuw {
static constexpr ov::Property<ov::FileHandleProvider> weights_handle_provider{"NPUW_WEIGHTS_HANDLE_PROVIDER"};

#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL

namespace partitioning {
namespace online {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace online

#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace partitioning

namespace accuracy {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace accuracy

namespace dump {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace dump

namespace llm {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace llm

namespace whisper {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace whisper

namespace eagle {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace eagle

namespace text_embed {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace text_embed

namespace kokoro {
#define INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ROOT_NPUW(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_PARTITIONING(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_ACCURACY(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_DUMP(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_LLM(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_WHISPER(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_EAGLE(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_TEXT_EMBED(EMIT, ...)
#define INTEL_NPU_NPUW_IF_NS_KOKORO(EMIT, ...) EMIT(__VA_ARGS__)
#define INTEL_NPU_NPUW_SIMPLE_OPT(OPT, TYPE, DEFAULT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, TYPE, NAME, KEY)
#define INTEL_NPU_NPUW_STRING_ENUM_OPT(OPT, TYPE, TRAITS, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, std::string, NAME, KEY)
#define INTEL_NPU_NPUW_ANYMAP_OPT(OPT, NS, NAME, KEY, GROUP, SURFACE, CACHING, BUILD) \
    INTEL_NPU_NPUW_IF_BUILD_##BUILD(INTEL_NPU_NPUW_IF_NS_##NS, INTEL_NPU_NPUW_DECLARE_PROPERTY, ov::AnyMap, NAME, KEY)
#include "intel_npu/config/npuw_option_defs.inc"
#undef INTEL_NPU_NPUW_ANYMAP_OPT
#undef INTEL_NPU_NPUW_STRING_ENUM_OPT
#undef INTEL_NPU_NPUW_SIMPLE_OPT
#undef INTEL_NPU_NPUW_IF_NS_KOKORO
#undef INTEL_NPU_NPUW_IF_NS_TEXT_EMBED
#undef INTEL_NPU_NPUW_IF_NS_EAGLE
#undef INTEL_NPU_NPUW_IF_NS_WHISPER
#undef INTEL_NPU_NPUW_IF_NS_LLM
#undef INTEL_NPU_NPUW_IF_NS_DUMP
#undef INTEL_NPU_NPUW_IF_NS_ACCURACY
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING
#undef INTEL_NPU_NPUW_IF_NS_PARTITIONING_ONLINE
#undef INTEL_NPU_NPUW_IF_NS_ROOT_NPUW
#undef INTEL_NPU_NPUW_IF_NS_ROOT_GLOBAL
}  // namespace kokoro

}  // namespace npuw

#undef INTEL_NPU_NPUW_IF_BUILD_DEV
#undef INTEL_NPU_NPUW_IF_BUILD_ALL
#undef INTEL_NPU_NPUW_DECLARE_PROPERTY

}  // namespace intel_npu
}  // namespace ov
