# type: ignore
from __future__ import annotations
import openvino._pyopenvino
import typing
"""
openvino.properties.intel_cpu submodule that simulates ov::intel_cpu
"""
__all__: list[str] = ['TbbPartitioner', 'denormals_optimization', 'sparse_weights_decompression_rate', 'tbb_partitioner']
class TbbPartitioner:
    """
    Members:
    
      STATIC
    
      AUTO
    """
    AUTO: typing.ClassVar[TbbPartitioner]  # value = <TbbPartitioner.AUTO: 2>
    STATIC: typing.ClassVar[TbbPartitioner]  # value = <TbbPartitioner.STATIC: 1>
    __members__: typing.ClassVar[dict[str, TbbPartitioner]]  # value = {'STATIC': <TbbPartitioner.STATIC: 1>, 'AUTO': <TbbPartitioner.AUTO: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
@typing.overload
def denormals_optimization() -> str:
    ...
@typing.overload
def denormals_optimization(arg0: bool) -> tuple[str, openvino._pyopenvino.OVAny]:
    ...
@typing.overload
def sparse_weights_decompression_rate() -> str:
    ...
@typing.overload
def sparse_weights_decompression_rate(arg0: typing.SupportsFloat) -> tuple[str, openvino._pyopenvino.OVAny]:
    ...
@typing.overload
def tbb_partitioner() -> str:
    ...
@typing.overload
def tbb_partitioner(arg0: TbbPartitioner) -> tuple[str, openvino._pyopenvino.OVAny]:
    ...
