get_property(GRAPH_COMPILER_LIBS GLOBAL PROPERTY GRAPH_COMPILER_LIBS)
if (NOT DEFINED GRAPH_COMPILER_LIBS)
    if (DEFINED GraphCompiler_DIR AND EXISTS "${GraphCompiler_DIR}/GraphCompilerTargets.cmake")
      include("${GraphCompiler_DIR}/GraphCompilerTargets.cmake")
    elseif (DEFINED GraphCompiler_ROOT)
      include("${GraphCompiler_ROOT}/lib/cmake/GraphCompiler/GraphCompilerTargets.cmake")
    else()
      find_package(GraphCompiler REQUIRED)
    endif()

    if(LLVM_DYLINK)
      set(GRAPH_COMPILER_LIBS GcInterface GraphCompiler)
    else()
      set(GRAPH_COMPILER_LIBS GcInterface MLIRLinalgx GcGpuOclRuntime)
    endif()
    set_property(GLOBAL PROPERTY GRAPH_COMPILER_LIBS ${GRAPH_COMPILER_LIBS})
endif ()

get_target_property(GRAPH_COMPILER_INCLUDES GcInterface INTERFACE_INCLUDE_DIRECTORIES)
get_target_property(GRAPH_COMPILER_COMPILE_OPTIONS GcInterface INTERFACE_COMPILE_OPTIONS)
