# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(OV_RPI_TOOLCHAIN_PREFIX "aarch64-none-linux-gnu" CACHE STRING "GNU target triplet prefix")
set(OV_RPI_SYSROOT "" CACHE PATH "Optional Raspberry Pi ARM64 sysroot")
set(_ov_rpi_template_dir "${CMAKE_CURRENT_LIST_DIR}/rpi_cross")

foreach(_ov_tool gcc g++ strip ar ranlib nm objcopy objdump readelf as ld)
    string(TOUPPER "${_ov_tool}" _ov_tool_upper)
    find_program(OV_RPI_${_ov_tool_upper}
        NAMES "${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_tool}.exe" "${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_tool}"
        DOC "Path to ${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_tool}")
endforeach()

if(NOT OV_RPI_GCC OR NOT OV_RPI_G++)
    message(FATAL_ERROR
        "Cannot find ${OV_RPI_TOOLCHAIN_PREFIX}-gcc / ${OV_RPI_TOOLCHAIN_PREFIX}-g++. "
        "Install Arm GNU Toolchain for Windows or set OV_RPI_TOOLCHAIN_PREFIX.")
endif()

set(CMAKE_C_COMPILER "${OV_RPI_GCC}" CACHE FILEPATH "Raspberry Pi ARM64 C compiler")
set(CMAKE_CXX_COMPILER "${OV_RPI_G++}" CACHE FILEPATH "Raspberry Pi ARM64 C++ compiler")

if(OV_RPI_STRIP)
    set(CMAKE_STRIP "${OV_RPI_STRIP}" CACHE FILEPATH "Raspberry Pi ARM64 strip")
endif()
if(OV_RPI_AR)
    set(CMAKE_AR "${OV_RPI_AR}" CACHE FILEPATH "Raspberry Pi ARM64 ar")
endif()
if(OV_RPI_RANLIB)
    set(CMAKE_RANLIB "${OV_RPI_RANLIB}" CACHE FILEPATH "Raspberry Pi ARM64 ranlib")
endif()
if(OV_RPI_NM)
    set(CMAKE_NM "${OV_RPI_NM}" CACHE FILEPATH "Raspberry Pi ARM64 nm")
endif()
if(OV_RPI_OBJCOPY)
    set(CMAKE_OBJCOPY "${OV_RPI_OBJCOPY}" CACHE FILEPATH "Raspberry Pi ARM64 objcopy")
endif()
if(OV_RPI_OBJDUMP)
    set(CMAKE_OBJDUMP "${OV_RPI_OBJDUMP}" CACHE FILEPATH "Raspberry Pi ARM64 objdump")
endif()
if(OV_RPI_READELF)
    set(CMAKE_READELF "${OV_RPI_READELF}" CACHE FILEPATH "Raspberry Pi ARM64 readelf")
endif()
if(OV_RPI_LD)
    set(CMAKE_LINKER "${OV_RPI_LD}" CACHE FILEPATH "Raspberry Pi ARM64 linker")
endif()

find_program(OV_RPI_PKG_CONFIG
    NAMES "${OV_RPI_TOOLCHAIN_PREFIX}-pkg-config.exe" "${OV_RPI_TOOLCHAIN_PREFIX}-pkg-config" pkg-config pkgconf
    DOC "pkg-config executable for the ARM64 target")
if(OV_RPI_PKG_CONFIG)
    set(PKG_CONFIG_EXECUTABLE "${OV_RPI_PKG_CONFIG}" CACHE FILEPATH "Path to ARM64 pkg-config")
endif()

if(OV_RPI_SYSROOT)
    file(TO_CMAKE_PATH "${OV_RPI_SYSROOT}" OV_RPI_SYSROOT)
    set(CMAKE_SYSROOT "${OV_RPI_SYSROOT}" CACHE PATH "Raspberry Pi ARM64 sysroot")
    set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" CACHE STRING "CMake target find roots")

    set(_ov_rpi_wrapper_dir "${CMAKE_BINARY_DIR}/rpi-aarch64-linux-toolchain")
    file(MAKE_DIRECTORY "${_ov_rpi_wrapper_dir}")
    set(_ov_rpi_grep_exe "${_ov_rpi_wrapper_dir}/grep.exe")
    if(NOT EXISTS "${_ov_rpi_grep_exe}")
        set(_ov_rpi_grep_source "${_ov_rpi_template_dir}/windows-grep.cs")
        file(TO_NATIVE_PATH "${_ov_rpi_grep_source}" _ov_rpi_grep_source_native)
        file(TO_NATIVE_PATH "${_ov_rpi_grep_exe}" _ov_rpi_grep_exe_native)
        execute_process(COMMAND powershell -NoProfile -ExecutionPolicy Bypass
                                -Command "Add-Type -Path '${_ov_rpi_grep_source_native}' -OutputAssembly '${_ov_rpi_grep_exe_native}' -OutputType ConsoleApplication"
                        RESULT_VARIABLE _ov_rpi_grep_result
                        ERROR_VARIABLE _ov_rpi_grep_error)
        if(NOT _ov_rpi_grep_result EQUAL 0)
            message(FATAL_ERROR "Failed to generate grep.exe for Windows-hosted Raspberry Pi ARM64 cross build: ${_ov_rpi_grep_error}")
        endif()
    endif()
    set(ENV{PATH} "${_ov_rpi_wrapper_dir};$ENV{PATH}")

    set(_ov_rpi_sysroot_flags "--sysroot=\"${CMAKE_SYSROOT}\"")
    if(EXISTS "${CMAKE_SYSROOT}/usr/include/aarch64-linux-gnu")
        set(_ov_rpi_multiarch_include "${CMAKE_SYSROOT}/usr/include/aarch64-linux-gnu")
        string(APPEND _ov_rpi_sysroot_flags " -isystem \"${_ov_rpi_multiarch_include}\"")
        foreach(_ov_rpi_flags_var CMAKE_C_FLAGS_INIT CMAKE_CXX_FLAGS_INIT CMAKE_ASM_FLAGS_INIT)
            if(NOT "${${_ov_rpi_flags_var}}" MATCHES "(^| )-isystem ${_ov_rpi_multiarch_include}($| )")
                string(APPEND ${_ov_rpi_flags_var} " -isystem ${_ov_rpi_multiarch_include}")
            endif()
        endforeach()
    endif()

    foreach(_ov_rpi_lib_dir
            "${CMAKE_SYSROOT}/lib64"
            "${CMAKE_SYSROOT}/usr/lib64"
            "${CMAKE_SYSROOT}/lib/aarch64-linux-gnu"
            "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu")
        if(EXISTS "${_ov_rpi_lib_dir}")
            foreach(_ov_rpi_linker_flags_var
                    CMAKE_EXE_LINKER_FLAGS_INIT
                    CMAKE_SHARED_LINKER_FLAGS_INIT
                    CMAKE_MODULE_LINKER_FLAGS_INIT)
                if(NOT "${${_ov_rpi_linker_flags_var}}" MATCHES "(^| )-L${_ov_rpi_lib_dir}($| )")
                    string(APPEND ${_ov_rpi_linker_flags_var} " -L${_ov_rpi_lib_dir}")
                endif()
                if(NOT "${${_ov_rpi_linker_flags_var}}" MATCHES "(^| )-B${_ov_rpi_lib_dir}($| )")
                    string(APPEND ${_ov_rpi_linker_flags_var} " -B${_ov_rpi_lib_dir}")
                endif()
            endforeach()
        endif()
    endforeach()

    set(_ov_rpi_glibc_major "2")
    set(_ov_rpi_glibc_minor "0")
    foreach(_ov_rpi_features_header
            "${CMAKE_SYSROOT}/usr/include/features.h"
            "${CMAKE_SYSROOT}/include/features.h")
        if(EXISTS "${_ov_rpi_features_header}")
            file(STRINGS "${_ov_rpi_features_header}" _ov_rpi_features_lines
                REGEX "^#[ \t]*define[ \t]+__GLIBC(_MINOR)?__[ \t]+[0-9]+")
            foreach(_ov_rpi_features_line IN LISTS _ov_rpi_features_lines)
                if(_ov_rpi_features_line MATCHES "^#[ \t]*define[ \t]+__GLIBC__[ \t]+([0-9]+)")
                    set(_ov_rpi_glibc_major "${CMAKE_MATCH_1}")
                elseif(_ov_rpi_features_line MATCHES "^#[ \t]*define[ \t]+__GLIBC_MINOR__[ \t]+([0-9]+)")
                    set(_ov_rpi_glibc_minor "${CMAKE_MATCH_1}")
                endif()
            endforeach()
            break()
        endif()
    endforeach()

    foreach(_ov_rpi_tool_name gcc g++)
        string(TOUPPER "${_ov_rpi_tool_name}" _ov_rpi_tool_upper)
        set(OV_RPI_WRAPPER_REAL_TOOL "${OV_RPI_${_ov_rpi_tool_upper}}")
        set(OV_RPI_WRAPPER_FLAGS "${_ov_rpi_sysroot_flags}")
        set(_ov_rpi_wrapper "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_rpi_tool_name}.cmd")
        if(_ov_rpi_tool_name STREQUAL "g++")
            set(OV_RPI_WRAPPER_GLIBC_MAJOR "${_ov_rpi_glibc_major}")
            set(OV_RPI_WRAPPER_GLIBC_MINOR "${_ov_rpi_glibc_minor}")
            configure_file("${_ov_rpi_template_dir}/windows-cxx-wrapper.cmd.in" "${_ov_rpi_wrapper}" @ONLY)
        else()
            configure_file("${_ov_rpi_template_dir}/windows-tool-wrapper.cmd.in" "${_ov_rpi_wrapper}" @ONLY)
        endif()
    endforeach()
    foreach(_ov_rpi_tool_name strip ar ranlib nm objcopy objdump readelf as ld)
        string(TOUPPER "${_ov_rpi_tool_name}" _ov_rpi_tool_upper)
        if(OV_RPI_${_ov_rpi_tool_upper})
            if(_ov_rpi_tool_name STREQUAL "ar")
                set(OV_RPI_WRAPPER_REAL_TOOL "${OV_RPI_AR}")
                set(_ov_rpi_ar_wrapper_ps1 "${_ov_rpi_wrapper_dir}/ar-rsp-normalize.ps1")
                configure_file("${_ov_rpi_template_dir}/ar-rsp-normalize.ps1.in" "${_ov_rpi_ar_wrapper_ps1}" @ONLY)
                file(TO_NATIVE_PATH "${_ov_rpi_ar_wrapper_ps1}" _ov_rpi_ar_wrapper_ps1_native)
                file(TO_NATIVE_PATH "${OV_RPI_WRAPPER_REAL_TOOL}" _ov_rpi_real_tool_native)
                set(OV_RPI_AR_WRAPPER_PS1_NATIVE "${_ov_rpi_ar_wrapper_ps1_native}")
                set(OV_RPI_WRAPPER_REAL_TOOL_NATIVE "${_ov_rpi_real_tool_native}")
                set(_ov_rpi_wrapper "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_rpi_tool_name}.cmd")
                configure_file("${_ov_rpi_template_dir}/windows-ar-wrapper.cmd.in" "${_ov_rpi_wrapper}" @ONLY)
            elseif(_ov_rpi_tool_name STREQUAL "as")
                set(OV_RPI_WRAPPER_REAL_TOOL "${OV_RPI_GCC}")
                set(OV_RPI_WRAPPER_FLAGS "${_ov_rpi_sysroot_flags} -x assembler-with-cpp -c")
                set(_ov_rpi_wrapper "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_rpi_tool_name}.cmd")
                configure_file("${_ov_rpi_template_dir}/windows-tool-wrapper.cmd.in" "${_ov_rpi_wrapper}" @ONLY)
            else()
                set(OV_RPI_WRAPPER_REAL_TOOL "${OV_RPI_${_ov_rpi_tool_upper}}")
                set(OV_RPI_WRAPPER_FLAGS "")
                set(_ov_rpi_wrapper "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-${_ov_rpi_tool_name}.cmd")
                configure_file("${_ov_rpi_template_dir}/windows-tool-wrapper.cmd.in" "${_ov_rpi_wrapper}" @ONLY)
            endif()
        endif()
    endforeach()

    find_program(OV_RPI_REAL_SCONS
        NAMES scons.exe scons
        DOC "SCons executable used by the Windows-hosted Raspberry Pi ARM64 cross toolchain")
    if(OV_RPI_REAL_SCONS)
        set(_ov_rpi_scons_site_dir "${_ov_rpi_wrapper_dir}/scons-site")
        file(MAKE_DIRECTORY "${_ov_rpi_scons_site_dir}")
        configure_file("${_ov_rpi_template_dir}/scons-site-init.py" "${_ov_rpi_scons_site_dir}/site_init.py" COPYONLY)

        file(TO_NATIVE_PATH "${OV_RPI_REAL_SCONS}" _ov_rpi_real_scons_native)
        file(TO_NATIVE_PATH "${_ov_rpi_scons_site_dir}" _ov_rpi_scons_site_dir_native)
        set(OV_RPI_REAL_SCONS_NATIVE "${_ov_rpi_real_scons_native}")
        set(OV_RPI_SCONS_SITE_DIR_NATIVE "${_ov_rpi_scons_site_dir_native}")
        set(_ov_rpi_scons_wrapper "${_ov_rpi_wrapper_dir}/scons-rpi-aarch64-linux.cmd")
        configure_file("${_ov_rpi_template_dir}/scons-rpi-aarch64-linux.cmd.in" "${_ov_rpi_scons_wrapper}" @ONLY)
        set(SCONS "${_ov_rpi_scons_wrapper}" CACHE FILEPATH "SCons wrapper for Raspberry Pi ARM64 cross build" FORCE)
    endif()

    set(ARM_COMPUTE_TOOLCHAIN_PREFIX "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-" CACHE STRING
        "Arm Compute Library toolchain prefix for Windows-hosted Raspberry Pi ARM64 cross build" FORCE)

    set(CMAKE_C_COMPILER "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-gcc.cmd" CACHE FILEPATH "Raspberry Pi ARM64 C compiler" FORCE)
    set(CMAKE_CXX_COMPILER "${_ov_rpi_wrapper_dir}/${OV_RPI_TOOLCHAIN_PREFIX}-g++.cmd" CACHE FILEPATH "Raspberry Pi ARM64 C++ compiler" FORCE)

    set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
    set(ENV{PKG_CONFIG_LIBDIR}
        "${CMAKE_SYSROOT}/usr/lib64/pkgconfig:${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

unset(_ov_rpi_lib_dir)
unset(_ov_rpi_linker_flags_var)
unset(_ov_rpi_multiarch_include)
unset(_ov_rpi_flags_var)
unset(_ov_rpi_features_header)
unset(_ov_rpi_features_line)
unset(_ov_rpi_features_lines)
unset(_ov_rpi_grep_error)
unset(_ov_rpi_grep_exe)
unset(_ov_rpi_grep_exe_native)
unset(_ov_rpi_grep_result)
unset(_ov_rpi_grep_source)
unset(_ov_rpi_grep_source_native)
unset(_ov_rpi_glibc_major)
unset(_ov_rpi_glibc_minor)
unset(_ov_rpi_ar_wrapper_ps1)
unset(_ov_rpi_ar_wrapper_ps1_native)
unset(_ov_rpi_real_tool_native)
unset(_ov_rpi_real_tool)
unset(_ov_rpi_real_scons_native)
unset(_ov_rpi_scons_site_dir)
unset(_ov_rpi_scons_site_dir_native)
unset(_ov_rpi_scons_wrapper)
unset(_ov_rpi_sysroot_flags)
unset(_ov_rpi_template_dir)
unset(_ov_rpi_tool_name)
unset(_ov_rpi_wrapper)
unset(_ov_rpi_wrapper_dir)
unset(_ov_tool)
unset(_ov_tool_upper)
unset(OV_RPI_AR_WRAPPER_PS1_NATIVE)
unset(OV_RPI_REAL_SCONS_NATIVE)
unset(OV_RPI_SCONS_SITE_DIR_NATIVE)
unset(OV_RPI_WRAPPER_FLAGS)
unset(OV_RPI_WRAPPER_GLIBC_MAJOR)
unset(OV_RPI_WRAPPER_GLIBC_MINOR)
unset(OV_RPI_WRAPPER_REAL_TOOL)
unset(OV_RPI_WRAPPER_REAL_TOOL_NATIVE)
