# Copyright (C) 2018-2020 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
function(ie_gen_default_header gen_header)
    file(WRITE "${gen_header}" "#define GraphGen(...) 1")
endfunction()

function(ie_gen_header gen_header itt_traces itt_domains)
    if(itt_traces)
        file(WRITE "${gen_header}" "## This code is auto generated\n")
        file(APPEND "${gen_header}" "#ifdef GraphGen\n")
        file(APPEND "${gen_header}" "#error \"GraphGen already defined\"\n")
        file(APPEND "${gen_header}" "#else\n")
        file(APPEND "${gen_header}" "#define GraphGen(impl) impl\n")
        file(APPEND "${gen_header}" "#endif\n")
    file(GLOB files "${itt_traces}/*.csv")
    LIST(LENGTH files FILESCOUNT)
    if (FILESCOUNT LESS_EQUAL 0)
        message(FATAL_ERROR "No traces are found in ${itt_traces}")
    endif()
    foreach(file ${files})
        FILE(READ "${file}" contents)
        STRING(REPLACE ";" "\\\\;" contents "${contents}")
        STRING(REPLACE "\n" ";" contents "${contents}")
        foreach(line ${contents})
            STRING(REPLACE "," ";" line "${line}")
            LIST(GET line 0 DOMAIN)
            LIST(FIND itt_domains "${DOMAIN}" DOMAIN_FOUND)
            if(DOMAIN_FOUND GREATER_EQUAL 0)
                LIST(GET line 1 DEFINED_VALUE)
                STRING(REPLACE "::" "_" DEFINED_VALUE "${DEFINED_VALUE}")
                STRING(REPLACE "." "_" DEFINED_VALUE "${DEFINED_VALUE}")
                set(DEFINED_VALUE "Gen_${DEFINED_VALUE}")
                file(APPEND "${gen_header}" "#ifndef ${DEFINED_VALUE}\n")
                file(APPEND "${gen_header}" "#define ${DEFINED_VALUE} 1\n")
                file(APPEND "${gen_header}" "#endif\n")
            endif()
        endforeach()
    endforeach()
    else()
        file(WRITE "${gen_header}" "#define GraphGen(...) 0")
    endif()
endfunction()


function(ie_forced_include target gen_header compression_mode)
    if(MSVC)
        set(forced_include "/FI ${gen_header}")
    else()
        set(forced_include "-imacros ${gen_header}")
        if(compression_mode)
            set(forced_include "${forced_include} -Wno-undef")
        endif()
    endif()
    set_target_properties(${target} PROPERTIES COMPILE_FLAGS ${forced_include})
endfunction()
