# Copyright (C) 2018-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(LIBRARY_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/src/emitter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/kernel_executor_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/expression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/expression_factory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/expression_port.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/expressions/buffer_expression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/linear_ir_builder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/linear_ir.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/loop_info.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/loop_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/loop_port.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/allocate_buffers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/assign_registers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/brgemm_blocking.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/clean_repeated_ptr_shifts.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/cleanup_loop_offsets.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/compute_buffer_allocation_size.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/define_buffer_clusters.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/extract_loop_invariants.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/fuse_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/init_buffers_default.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/init_live_ranges.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/init_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/init_registers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_broadcastmove.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_buffers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_load_store.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_reg_spills.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_specific_iterations.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/iter_handler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/load_movebroadcast_to_broadcastload.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/mark_invariant_shape_path.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/mark_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/mha_parallel_wa_optimizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/move_result_out_of_loop.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/move_scalar_to_consumer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/normalize_buffer_reg_groups.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/normalize_loop_ids.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/optimize_domain.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/optimize_loop_single_evaluation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/pass_config.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/pass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/propagate_buffer_offset.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/reduce_decomposition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/serialize_base.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/serialize_control_flow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/serialize_data_flow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/set_buffer_reg_group.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/set_dynamic_wa_to_outermost_loop.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/set_load_store_scalar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/solve_buffer_memory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/split_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/validate_buffers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/validate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/validate_expanded_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/validate_shapes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/validate_unified_loops.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/port_connector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/port_descriptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/specific_loop_iter_handlers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/target_machine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/brgemm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/broadcastload.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/broadcastmove.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/convert_saturation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/convert_truncation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/fill.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/horizon.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/horizon_max.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/horizon_sum.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/kernel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/load.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/loop.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/memory_access.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/nop.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/online_softmax.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/online_softmax_update_max.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/online_softmax_update_sum.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/rank_normalization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/reduce.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/reg_spill.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/reorder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/reshape.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/result.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/scalar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/serialization_node.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/store.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/subgraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/op/vector_buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/align_element_types.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/analyze_broadcastable_inputs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/broadcast_to_movebroadcast.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/canonicalization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/collapse_subgraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/common_optimizations.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/convert_constants.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/convert_power_to_powerstatic.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/explicit_transpose_matmul_inputs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/extract_constants.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/extract_reshapes_from_mha.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/extract_unsupported_transposes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/fc_tokenization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/fq_decomposition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/fuse_transpose_brgemm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/gated_mlp_tokenization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/gn_decomposition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/gn_tokenization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/hash.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/matmul_to_brgemm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/mha_tokenization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/mlp_seq_tokenization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/online_softmax_decomposition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/positioned_pass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/propagate_precision.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/reduce_to_snippets_reduce.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/softmax_decomposition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/softmax_reshape_elimination.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/subgraph_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/tokenization.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/transform_convert.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/transpose_decomposition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pass/validate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/runtime_configurator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/shape_inference/shape_inference.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/shape_inference/shape_infer_instances.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/loop_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/tokenization_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/utils.cpp
)

set(PUBLIC_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/emitter.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/generator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/itt.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/kernel_executor_table.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/expression_factory.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/expression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/expression_port.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/expressions/buffer_expression.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/linear_ir_builder.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/linear_ir.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/loop_info.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/loop_manager.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/loop_port.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/allocate_buffers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/assign_registers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/brgemm_blocking.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/clean_repeated_ptr_shifts.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/cleanup_loop_offsets.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/compute_buffer_allocation_size.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/define_buffer_clusters.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/extract_loop_invariants.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/fuse_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/init_buffers_default.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/init_live_ranges.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/init_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/init_registers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_broadcastmove.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_buffers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_load_store.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_reg_spills.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_specific_iterations.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/iter_handler.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/load_movebroadcast_to_broadcastload.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/mark_invariant_shape_path.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/mark_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/mha_parallel_wa_optimizer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/move_result_out_of_loop.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/move_scalar_to_consumer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/normalize_buffer_reg_groups.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/normalize_loop_ids.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/optimize_domain.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/optimize_loop_single_evaluation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/pass_config.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/pass.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/propagate_buffer_offset.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/reduce_decomposition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/runtime_optimizer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/serialize_base.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/serialize_control_flow.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/serialize_data_flow.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/set_buffer_reg_group.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/set_dynamic_wa_to_outermost_loop.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/set_load_store_scalar.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/solve_buffer_memory.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/split_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/validate_buffers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/validate_expanded_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/validate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/validate_shapes.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/validate_unified_loops.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/port_connector.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/port_descriptor.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/reg_manager.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/specific_loop_iter_handlers.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/specific_loop_iter_types.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/brgemm.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/broadcastload.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/broadcastmove.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/buffer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/convert_saturation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/convert_truncation.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/fill.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/horizon.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/horizon_max.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/horizon_sum.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/kernel.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/load.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/loop.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/memory_access.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/nop.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/online_softmax.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/online_softmax_update_max.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/online_softmax_update_sum.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/powerstatic.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/rank_normalization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/reduce.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/reg_spill.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/reorder.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/reshape.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/result.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/scalar.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/serialization_node.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/shape_infer_op.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/store.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/subgraph.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/vector_buffer.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/align_element_types.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/analyze_broadcastable_inputs.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/broadcast_to_movebroadcast.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/canonicalization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/collapse_subgraph.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/common_optimizations.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/convert_constants.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/convert_power_to_powerstatic.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/explicit_transpose_matmul_inputs.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/extract_constants.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/extract_reshapes_from_mha.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/extract_unsupported_transposes.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/fc_tokenization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/fq_decomposition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/fuse_transpose_brgemm.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/gated_mlp_tokenization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/gn_decomposition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/gn_tokenization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/hash.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/manager.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/matmul_to_brgemm.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/mha_tokenization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/mlp_seq_tokenization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/online_softmax_decomposition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/positioned_pass.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/propagate_precision.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/reduce_to_snippets_reduce.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/softmax_decomposition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/softmax_reshape_elimination.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/subgraph_manager.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/subgraph_pass.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/tokenization_config.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/tokenization.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/transform_convert.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/transpose_decomposition.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/pass/validate.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/remarks.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/runtime_configurator.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/shape_inference/shape_inference.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/shape_inference/shape_infer_instances.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/shape_types.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/snippets_isa_tbl.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/target_machine.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/utils/linear_ir_pass_dumper.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/utils/loop_utils.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/utils/reg_utils.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/utils/tokenization_utils.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/utils/utils.hpp
)

if(ENABLE_SNIPPETS_DEBUG_CAPS)
    list(APPEND LIBRARY_SRC
        ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_perf_count.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/lowered/pass/insert_perf_count_verbose.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/op/perf_count.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/src/utils/debug_caps_config.cpp
    )

    list(APPEND PUBLIC_HEADERS
        ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_perf_count.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/lowered/pass/insert_perf_count_verbose.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/op/perf_count.hpp
        ${CMAKE_CURRENT_SOURCE_DIR}/include/snippets/utils/debug_caps_config.hpp
    )
endif()
