// Copyright (C) 2018-2022 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//

#include <vector>
#include "single_layer_tests/batch_to_space.hpp"
#include "common_test_utils/test_constants.hpp"

using namespace ov::test::subgraph;

namespace {

BatchToSpaceTestParams bts_only_test_cases[] = {
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 1, 1, 1}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::f32,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 3, 1, 1}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::f32,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 1, 2, 2}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::f32,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{8, 1, 1, 2}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::f32,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{24, 1, 2, 1, 2}}),
                               {1, 1, 3, 2, 2}, {0, 0, 1, 0, 3}, {0, 0, 2, 0, 0},
                                ov::element::Type_t::f32,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 1, 1, 1}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::i8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 3, 1, 1}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::i8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 1, 2, 2}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::i8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{8, 1, 1, 2}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::i8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{24, 1, 2, 1, 2}}),
                               {1, 1, 3, 2, 2}, {0, 0, 1, 0, 3}, {0, 0, 2, 0, 0},
                               ov::element::Type_t::i8,
                               ov::element::Type_t::undefined,
                               ov::element::Type_t::undefined,
                               CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 1, 1, 1}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::u8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 3, 1, 1}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::u8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{4, 1, 2, 2}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::u8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{8, 1, 1, 2}}),
                               {1, 1, 2, 2}, {0, 0, 0, 0}, {0, 0, 0, 0},
                                ov::element::Type_t::u8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU),
        BatchToSpaceTestParams(ov::test::static_shapes_to_test_representation({{24, 1, 2, 1, 2}}),
                               {1, 1, 3, 2, 2}, {0, 0, 1, 0, 3}, {0, 0, 2, 0, 0},
                                ov::element::Type_t::u8,
                                ov::element::Type_t::undefined,
                                ov::element::Type_t::undefined,
                                CommonTestUtils::DEVICE_GPU)
};

INSTANTIATE_TEST_SUITE_P(smoke_CLDNN, BatchToSpaceLayerTest, ::testing::ValuesIn(bts_only_test_cases),
                        BatchToSpaceLayerTest::getTestCaseName);
}  // namespace
