name: Handle Issue Assignments

on:
  issue_comment:
    types: [created]
  issues:
    types: [assigned, unassigned]

permissions:
  issues: write
  repository-projects: write

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Process issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const LABEL = "good first issue";
            const COLUMNS = {
              todo: "Contributors needed",
              inProgress: "Assigned",
              done: "Closed"
            };

            const issue = context.payload.issue;

            async function getProjectId() {
              try {
                const projects = await github.rest.projects.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo
                });
                const project = projects.data.find(p => p.name === "Good first issues");
                if (!project) throw new Error("Project not found");
                return project.id;
              } catch (err) {
                console.log("Error fetching project ID:", err);
                throw err;
              }
            }

            async function moveIssue(columnName) {
              if (!issue.labels?.some(l => l.name.toLowerCase() === LABEL)) {
                console.log(`Issue #${issue.number} - not a good first issue, skipping`);
                return;
              }

              try {
                const PROJECT_ID = await getProjectId();
                const columns = await github.rest.projects.listColumns({ project_id: PROJECT_ID });
                const column = columns.data.find(c => c.name === columnName);
                if (!column) throw new Error(`Can't find column ${columnName}`);

                const cards = await github.rest.projects.listCards({ column_id: column.id });
                const existingCard = cards.data.find(c => c.content_url.endsWith(`/issues/${issue.number}`));

                if (existingCard) {
                  await github.rest.projects.moveCard({
                    card_id: existingCard.id,
                    position: "top",
                    column_id: column.id
                  });
                } else {
                  await github.rest.projects.createCard({
                    column_id: column.id,
                    content_id: issue.id,
                    content_type: "Issue"
                  });
                }

                console.log(`Updated issue #${issue.number} to ${columnName}`);
              } catch (err) {
                console.log(`Error updating issue #${issue.number}:`, err);
                throw err;
              }
            }

            if (context.payload.comment) {
              const comment = context.payload.comment.body.trim();
              const user = context.payload.comment.user.login;

              if (comment === ".take") {
                await moveIssue(COLUMNS.inProgress);
                await github.rest.issues.addAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  assignees: [user]
                });
              }

              if (comment === ".release") {
                const assignees = issue.assignees.map(a => a.login).filter(a => a !== user);
                await github.rest.issues.removeAssignees({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  assignees: [user]
                });

                if (assignees.length === 0) {
                  await moveIssue(COLUMNS.todo);
                }
              }
            }

            if (context.payload.action === "assigned" || context.payload.action === "unassigned") {
              const hasAssignee = issue.assignees?.length > 0;
              await moveIssue(hasAssignee ? COLUMNS.inProgress : COLUMNS.todo);
            }
