name: Code coverage
run-name: ${{ github.event_name == 'schedule' && 'Code coverage - Nightly' || 'Code coverage' }}
on:
  schedule:
    # run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      run-cpu-tests:
        description: 'Run the standard CPU coverage lanes'
        type: boolean
        required: false
        default: true
      run-gpu-tests:
        description: 'Build with GPU support and run the GPU coverage lanes'
        type: boolean
        required: false
        default: true

concurrency:
  group: ${{ github.event_name == 'pull_request' && github.run_id || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: false

permissions: read-all

env:
  ENABLE_BRANCH_COVERAGE: 'false'
  LCOV_CAPTURE_TIMEOUT_SECONDS: '3600'
  NODE_VERSION: '21'
  NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/IntelProxyRootCA-Base64.crt
  IGPU_DRIVER_PACKAGES: |-
    https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.15985.7/intel-igc-core_1.0.15985.7_amd64.deb
    https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.15985.7/intel-igc-opencl_1.0.15985.7_amd64.deb
    https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-level-zero-gpu_1.3.28454.6_amd64.deb
    https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/intel-opencl-icd_24.05.28454.6_amd64.deb
    https://github.com/intel/compute-runtime/releases/download/24.05.28454.6/libigdgmm12_22.3.11_amd64.deb
  DGPU_DRIVER_PACKAGES: |-
    https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.17791.9/intel-igc-core_1.0.17791.9_amd64.deb
    https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.17791.9/intel-igc-opencl_1.0.17791.9_amd64.deb
    https://github.com/intel/compute-runtime/releases/download/24.39.31294.12/intel-level-zero-gpu_1.6.31294.12_amd64.deb
    https://github.com/intel/compute-runtime/releases/download/24.39.31294.12/intel-opencl-icd_24.39.31294.12_amd64.deb
    https://github.com/intel/compute-runtime/releases/download/24.39.31294.12/libigdgmm12_22.5.2_amd64.deb

jobs:
  Docker:
    name: Coverage Docker Images
    if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event.inputs.run-cpu-tests == 'true' || github.event.inputs.run-gpu-tests == 'true' }}
    runs-on: aks-linux-4-cores-16gb-docker-build-ab
    container:
      image: openvinogithubactions.azurecr.io/docker_build:0.2
      volumes:
        - /mount:/mount
    outputs:
      images: ${{ steps.handle_docker.outputs.images }}
    steps:
      - name: Checkout
        uses: ababushk/checkout@dd591a6a2ac25618db4eda86e7e0d938f88cf01b # cherry_pick_retries
        timeout-minutes: 15

      - uses: ./.github/actions/handle_docker
        id: handle_docker
        with:
          images: |
            ov_build/ubuntu_22_04_x64
            ov_test/ubuntu_22_04_x64
            ov_test/ubuntu_22_04_x64_igpu
          registry: 'openvinogithubactions.azurecr.io'
          dockerfiles_root_dir: '.github/dockerfiles'
          changed_components: '{"docker_env":false,"dockerfiles":false}'

  Build:
    name: Coverage Build Artifacts
    needs: Docker
    if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event.inputs.run-cpu-tests == 'true' || github.event.inputs.run-gpu-tests == 'true' }}
    uses: ./.github/workflows/job_build_linux.yml
    with:
      runner: 'aks-linux-16-cores-32gb-ab'
      image: ${{ fromJSON(needs.Docker.outputs.images).ov_build.ubuntu_22_04_x64 }}
      affected-components: '{"JS_API":true}'
      event-name: ${{ github.event_name }}
      os: 'ubuntu_22_04'
      build-js: true
      build-additional-python-packages: false
      build-debian-packages: false
      upload-coverage-notes: true
      use_latest_onednn: false
      cmake-options: >-
        -G 'Ninja Multi-Config'
        -DENABLE_NCC_STYLE=OFF
        -DENABLE_TESTS=ON
        -DENABLE_FUNCTIONAL_TESTS=ON
        -DENABLE_STRICT_DEPENDENCIES=OFF
        -DENABLE_SYSTEM_OPENCL=ON
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCPACK_GENERATOR=TGZ
        -DENABLE_WHEEL=ON
        -DENABLE_PYTHON=ON
        -DENABLE_JS=ON
        -DENABLE_COVERAGE=ON
        -DENABLE_OV_ONNX_FRONTEND=ON
        -DENABLE_OV_PADDLE_FRONTEND=ON
        -DENABLE_OV_PYTORCH_FRONTEND=ON
        -DENABLE_OV_TF_FRONTEND=ON
        -DENABLE_OV_TF_LITE_FRONTEND=ON
        -DENABLE_INTEL_NPU=OFF
        ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event.inputs.run-gpu-tests == 'true') && '-DENABLE_INTEL_GPU=ON' || '-DENABLE_INTEL_GPU=OFF' }}
        ${{ (github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event.inputs.run-gpu-tests == 'true') && '-DENABLE_ONEDNN_FOR_GPU=ON' || '-DENABLE_ONEDNN_FOR_GPU=OFF' }}

