on:
  workflow_call:

permissions: read-all

jobs:
  dummy_job:
    name: Dummy Job
    timeout-minutes: 2
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Dummy Step
        run: |
          echo "Dummy Step"